### ISSUE TITLE
prośba o podpięcie wskazanych gmin do innych powiatów i województw

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#1008]
@dzejkobi o tym wspominałam na spotkaniu - mamy bałagan w bazie i pozamieniane miejscami niektóre gminy.  Miałabym prośbę, żebyś pozmieniał przypisanie gmin do powiatów, które wysyłam w załączeniu.

Jedną gminę trzeba też usunąć, a 11 dodać. Wszystko jest w oddzielnych, opisanych zakładach:

[Uploading urzędy do usunięcia,dodania i poprawienia w fedrowaniu.xls…]()

**Comment by AgnieszkaZdanowicz** [comment]
hm... widzę, że plik się nie załączył. To podesłałam Ci załącznik mailem przed chwilą

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi 

Ad1. nie wiem, co Wy tam robicie w tą bazą teryt ;) i dlatego nie bardzo rozumiem, co zostało zmienione i czy to jakoś wpłynęło na wyświetlane dane? Jeśli to za dużo tłumaczenia, żeby pisać, to możemy zapamiętać, żeby o tym pogadać na następnym spotkaniu, bo chętnie dowiem się, jak zarządzana jest baza instytucji w powiązaniu z bazą z GUSu.

Ad2. W sumie moja powyższa uwaga odnosi się też do tego punktu. Zgadzam się, że przy edycji gminy warto byłoby podać użytkownikowi takie dane, żeby był pewny, że zaznacza właściwą gminę - tak więc jak najbardziej jestem za zmianami w interfejsie. Czy identyfikator JST to jest właśnie TERYT? To się chyba pokrywa z prośbą Kasi z ostatniego spotkania - jak dodajemy nową JST, to nie ma miejsca na wpisanie tego TERYTu, tylko jest pole na. REGON: https://github.com/watchdogpolska/feder/issues/1014
A czy nie lepiej, zamiast identyfikować gminę po terycie, pozwolić użytkownikowi wybrać nazwę gminy, powiatu, województwa i rodzaj gminy (miejska/wiejska etc.)? Moja wątpliwość wynika chyba z tego, że ja z tym TERYTem nie jest za bardzo zapoznana, a może jego jest łatwo odnaleźć w jakieś bazie?

Ne wiem, jakie konsekwencje niosłoby przeszukanie naszej bazy i porównanie jej z GUSową, więc na to pytanie nie potrafię odpowiedzieć. Czy to pozwoli zweryfikować, czy wyłapałam zarówno wszystkie "nadmiarowe" gminy u nas w bazie i te, których u nas brakuje? Boję się, żeby system nam czegoś nie skasował bez naszej wiedzy.

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz

Ad1. Aktualną bazę teryt można pobrać ze strony GUSu i zaimportować do naszej bazy, ale tym razem dodałem rekordy ręcznie wg arkusza.

Ad2. Ok, w takim razie poprawię interfejs.
Odnośnie bazy JST, w panelu admina dostępna jest tutaj: https://fedrowanie.siecobywatelska.pl/admin/teryt_tree/jednostkaadministracyjna/
Kod teryt to ID odpowiedniej jednostki administracyjnej (JST). Nie za bardzo rozumiem, w którym miejscu jest problem z przypisaniem JST do instytucji? Można to zrobić w aplikacji i w panelu admina. Różnica jest taka, że w aplikacji wybieramy w polu "Jednostka podziału terytorialnego" nazwę z listy rozwijanej, a w panelu admina podajemy bezpośrednio Kod teryt.
Musimy się opierać na terycie, bo instytucja (w tym przypadku samorząd gminy) ma przypisany tylko kod teryt i na tej podstawie określany jest powiat i województwo.
Bazę teryt GUSu można przeglądać/przeszukiwać tutaj: https://eteryt.stat.gov.pl/eTeryt/rejestr_teryt/udostepnianie_danych/baza_teryt/uzytkownicy_indywidualni/wyszukiwanie/wyszukiwanie.aspx?contrast=default

Z tego, co się orientuję, baza teryt GUSu ulega zmianie, więc warto by było naszą bazę co pewien czas aktualizować. Nie musimy usuwać rekordów, możemy tylko deaktywować te nieaktualne, nie wiem jak to wpłynie na instytucje przypisane do tych kodów, trzeba by przetestować.

**Comment by dzejkobi** [comment]
Gotowe.

Co zostało zrobione:
* zmiana w interfejsie - więcej informacji w polu wyboru jednostki teryt.
* aktualizacja bazy teryt
* aktualizacja bazy instytucji

Można przetestować i jeśli wszystko ok, to proponuję zamknąć zadanie.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi wszystko sprawdzone i się zgadza. dzięki wielkie, zamykam

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m rozmawiałyśmy w zeszłym tygodniu z dziewczynami o SJJ i przy okazji o fedrowaniu. Wyszło nam, że w Wykazie instytucji byłoby nam łatwiej odnajdować właściwe instytucje, gdyby wyświetlało się o nich więcej informacji. Piszę o tym w tym wątku, bo byłam przekonana, że Kuba wprowadzał tę zmianę, ale nie mogę jej znaleźć. Weszłam na staging i tam to wygląda tak, jak byśmy chciały. Być może rzeczywiście nie doprowadziliśmy procesu do końca, chociaż wydaje mi się to dziwne. 

Na produkcji wyświetlają się takie dane o instytucji:

![image](https://user-images.githubusercontent.com/36925935/149754052-1bd76fec-b773-4c77-ac00-1d2a8cdf8f37.png)


A na demo takie:

![image](https://user-images.githubusercontent.com/36925935/149754118-68be3f4e-2ad5-44a2-bf3b-5b3624a7e88e.png)

Czy Ty może jesteś w stanie w jakiś prosty sposób przekopiować tę zmianę z demo na produkcję?

**Comment by dzejkobi** [comment]
Cześć. Dawno się nie odzywałem, ale widzę, że to jakaś zaszłość po mnie, więc mogę zerknąć i przenieść zmianę. Mniej więcej kojarzę sprawę.

**Comment by AgnieszkaZdanowicz** [comment]
Hej Kubo! Ja mam napisane w Twojej tabelce, że to miało status "gotowe" i wydawało mi się, że to działało, jak trzeba. Ale gdybyś mógł spojrzeć, czy to da się łatwo zaimplementować, to byłoby super :)

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Tak, prawdopodobnie czegoś nie przeniosłem. Spojrzę na to, tylko muszę się ogarnąć z bieżącymi sprawami.

**Comment by ad-m** [comment]
Ja też bardzo chętnie na to spojrzę, bo do wcześniejszego wykonania pamiętam, że miałem wątpliwości co do wydajności (wydaje mi się, że nie uwzględniono kwestii złączeń na bazie danych w podejściu na stagingu) , więc chętnie bym spojrzał na to w najbliższy weekend.

**Comment by dzejkobi** [comment]
@ad-m Ok, w takim razie wstrzymam się z mergem i poczekam na feedback.

**Comment by ad-m** [comment]
@dzejkobi podstawowy test, który będzie dla mnie istotny to lista z kilkoma instytucjami z rozbudowanymi jednostkami terytorialnymi, która nie powinna generować mnóstwa zapytań. Wykorzystałbym do tego `assertNumQueriesLessThan` z django-test-plus. 

Wywołuje we mnie także niepokój, aby metoda `__str__` wykonywała zapytania, bo może to zaskakiwać przy wydajności, więc szukałbym innego podejścia (wydaje się, że takie problemy w którymś momencie wystąpiły, stąd fe9532abba2efe6ac31775fee30646e7d6fbca2e ).

**Comment by dzejkobi** [comment]
@ad-m Ok, w takim razie pozostawiam Tobie implementację, bo jeśli chodzi o zmergowanie istniejącego rozwiązania, nie ma większego problemu, natomiast na implementację od zera niestety nie znajdę w tej chwili czasu.

**Comment by dzemeuksis** [comment]
@PiotrIw , pierwsza część tego zgłoszenia jest nieaktualna a o kwestii poruszonej w drugiej części, tj. wyświetlaniu większej ilości informacji o instytucjach rozmawialiśmy przy jakiejś okazji. Okazuje się, że tu jakaś zmiana była, ale nie została ostatecznie przeniesiona, jak na obrazku wyżej:
![obraz](https://github.com/watchdogpolska/feder/assets/33778688/d4bfb623-5d38-4ab2-bb08-68b4a0e12a3b)
Co się z tym ostatecznie zadziało, to nie wiem. Na obecnym stagingu już tego nie ma. Ale generalnie coś takiego byłoby przydatne, chociaż jak to zrealizować to nie wiem, bo do tamtej implementacji Adam miał jakieś zastrzeżenia natury chyba wydajnościowej.

**Comment by PiotrIw** [comment]
rozwinięte nazwy JST w widoku instytucji zaimplementowane w v1.1.11
