### ISSUE TITLE
Dodanie w panelu administracyjnym pola TERYT

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#1014]
@dzejkobi 

Zgodnie z rozmową, prośba o to by można było zobaczyć/dopisać TERYT, jeśli jest

**Comment by dzejkobi** [comment]
@KatarzynaBatko

Nie jestem pewien, czy dobrze zrozumiałem, gdzie brakuje tej funkcji?

Sama baza TERYT jest edytowalna z panelu admina, albo można ją zaktualizować skryptem na podstawie bazy GUSu.

Natomiast jeśli chodzi o instytucje, to w panelu admina w widoku instytucji jest pole "Jednostka podziału terytorialnego" i tam wpisuje się kod TERYT bezpośrednio, a jeśli już jest przypisany, to obok pojawia się jego nazwa.

W widoku listy instytucji też mamy "Jednostka podziału terytorialnego:", po ostatniej modyfikacji oprócz nazwy wyświetla się cała hierarchia: `województwo / powiat / gmina (kod TERYT, kategoria)`.

W widoku szczegółów instytucji kod TERYT nigdzie się nie wyświetla i tu rzeczywiście można go dodać (np. po lewej obok tagu i e-maila).

W widoku edycji instytucji też jest "Jednostka podziału terytorialnego" jako pole wyboru z funkcją autouzupełniania.

Czy gdzieś jeszcze brakuje kodu TERYT, czy tylko w tym jednym miejscu, w widoku listy spraw dla danej instytucji?

**Comment by AgnieszkaZdanowicz** [comment]
@KatarzynaBatko ustaliliśmy dziś na spotkaniu, że tutaj nie jest potrzebne oddzielne pole TERYT przy dodawaniu instytucji, bo tam jest pole "jednostka samorządu..." i tam jest wszyty TERYT. Zresztą teraz Kuba dodał funkcjonalność, że jak się wybiera daną jednostkę, to przy jej nazwie ten TERYT się wyświetla.
Tak więc zamykam ten issue, a gdyby Ci chodziło jednak o coś innego, to otwórz, proszę.
