### ISSUE TITLE
prośba o ułożenie alfabetycznie instytucji

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#1023]
@dzejkobi tak, jak dziś rozmawialiśmy - jak się wchodzi w instytucje, to pierwsze, które się wyświetlają tzn. marszałkowie są ułożone alfabetycznie. Ale jak już wybiorę tag "ministerstwa", to wyniki nie wyświetlają się według nie wiem jakiej reguły. Mam prośbę o sprawienie, żeby wszystko było alfabetycznie. Jeszcze spojrzę, co nie jest tak ułożone, ale już to chyba sprawdzałam i tego nie wyłapałam. Więc wszystko wychodzi w praniu.

**Comment by dzemeuksis** [comment]
@PiotrIw , tak, to byłoby przydatne. Być może jest dobry powód, dla którego tego sortowania nie ma, ale faktycznie to bywa zgubne, jeśli mimochodem założysz, że masz coś posortowane i nie zajrzysz na kolejne strony.

**Comment by PiotrIw** [comment]
zaimplementowane w v1.1.11
