### ISSUE TITLE
Dodanie zaznaczania przy wysyłce

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#1045]
Kiedy przypisuje się podmioty do wysłania i zaznacza przy "Nazwa" wszystkie, to nie widać które są zaznaczone i trochę wysyła się w ciemno. Nie ma z tym dramatu, gdyż można nacisnąć "wyślij" i wiadomo wtedy do kogo poszło. Ale może na jakimś etapie to można zrobić bardziej czytelnym. 

@dzejkobi

**Comment by PiotrIw** [comment]
@dzemeuksis - proponuję zamiast checkboxa obok Nazwa, dodać:
- licznik zaznaczonych (Nazwa - zaznaczone 12)
- obok przycisku "Przypisz wybrane..." dodać drugi "Przypisz wszystkie odfiltrowane 123 instytucje ...."

**Comment by dzemeuksis** [comment]
@PiotrIw , brzmi dobrze.

**Comment by PiotrIw** [comment]
zaimplementowane w v1.1.21
![image](https://github.com/watchdogpolska/feder/assets/36678620/203500f8-2b13-4d78-ae7f-f72e5f3c983d)

**Comment by dzemeuksis** [comment]
Jakie warunki trzeba spełnić, żeby móc zaznaczyć checkbox "Wybierz ręcznie..."? Pytam, bo nie mogę tego zrobić.

**Comment by dzemeuksis** [comment]
@PiotrIw , pojąłem o co chodzi po rozmowie telefonicznej. Po namyśle i analizie toku mojego rozumowania, które mnie doprowadziło w krzaki, proponuję zredagować widoczny na zrzucie komunikat w taki sposób:
> Do masowego zaznaczenia odfiltruj mniej niż 500 (odfiltrowane: ...)

No chyba że to z kolei dla Ciebie brzmi dziwnie, to na razie zostawmy.

**Comment by PiotrIw** [comment]
A może:

> Do masowego zaznaczenia odfiltruj mniej niż 500 (odfiltrowane: ...) lub zaznacz poszczególne instytucje na liście poniżej.

**Comment by dzemeuksis** [comment]
Jak się zmieści, to ok.
