### ISSUE TITLE
Subskrypcja danego obszaru

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#108]
Należy umożlwić zapisanie się na "newsletter" z aktualności danego obszaru.

**Comment by ad-m** [comment]
django-nyt?

**Comment by ad-m** [comment]
Warto pomyśleć nad tym, żeby te subskrypcje były powiadomieniami do przeglądania on-line, a także dostępnymi przez e-mail dla użytkowników zarejestrowanych. Zawsze to jakaś motywacja do rejestracji. A może więcej back-endów powiadomień typu Telegram też? 

Mamy poza tym kanały RSS dla monitoringów i spraw. Dla obszarów nie.

**Comment by AgnieszkaZdanowicz** [comment]
W tej chwili nie zakładamy, że ludzie będą się rejestrować, ale to ciekawe, żeby była jakaś opcja newslettera i wybrania obszaru, w którym jak coś nowego się pojawi, to ktoś dostaje wiadomość.

**Comment by AgnieszkaZdanowicz** [comment]
moim zdaniem nie rozwijamy tego narzędzia aż tak (i w najbliższych planach nie będziemy), żeby taki mechanizm wprowadzać. No i nie planujemy masowej rejestracji. Zamykam.
