### ISSUE TITLE
Ucięte odpowiedzi w Fedrowaniu

### ISSUE THREAD

**Issue by Roksana90** [watchdogpolska/feder#1137]
Jeśli odpowiedź urzędu jest przedstawiana w ten sposób:
https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-80
![image](https://user-images.githubusercontent.com/16541446/148095735-998be010-30ca-413e-b96f-f93c158080da.png)
to bardzo często ucina się gdzieś w okolicy 8 pytania albo nawet wcześniej. Wydaje mi się, że to nie problem z nieuważnością urzędów, tylko coś się cała odpowiedź nie zaciąga.
Przykłady innych takich odpowiedzi: 
https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-2222
https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-772
https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-957
https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-1838
W efekcie do SJJ wysyłaliśmy niepełne dokumenty.

**Comment by Roksana90** [comment]
Martyna mnie uświadomiła, że w trzeba klikać czerwoną ikonkę  z plusem - Pokaż cytat i tam jest cała odpowiedź. Ale gorzej, że do SJJ nie pobrała się całość.

**Comment by Roksana90** [comment]
Ale bywają takie, że i w cytacie nie ma całej odp https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-958

**Comment by Roksana90** [comment]
@mrbojko @ad-m Zerkniecie na to?

**Comment by ad-m** [comment]
> Ale bywają takie, że i w cytacie nie ma całej odp https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-958

Szczerze mówiąc, nie wiem czego Ci brakuje w tej odpowiedzi. Proszę dokładnie kopie e-maila ( https://files.jawne.info.pl/private_html/2022_01_iaz0ceiv5Peethah0ailaeth8Eu1eena8cahnun1Shuug3eip9 ). To jest dostępne w Fedrowaniu do pobrania dla każdego, ale ma pewną usterkę z powodu #1069 .

**Comment by Roksana90** [comment]
Adamie, widzę tyle co w Fedrowaniu.
U góry gmina odnosi się w treści do naszych pytań. Powyżej pytania 8.2 już nie więcej odpowiedzi.  A w cytacie jest tylko treść naszego wniosku.
![image](https://user-images.githubusercontent.com/16541446/148210204-91d98e24-b57b-42de-80ac-8eaf3ecb262e.png)


A kopii nie mogę pobrać, chrome w ogóle nie reaguje a Edge informuje, że to pliki niebezpieczne.
![image](https://user-images.githubusercontent.com/16541446/148210009-cf86075f-1d2b-4b24-85b5-12ba6f1b7e71.png)

**Comment by ad-m** [comment]
@Roksana90 nie ma dalej odpowiedzi: https://files.jawne.info.pl/private_html/2022_01_ohhihah7ungu7iegiegoP9ahsiodieyata4keix2aithai9aid

**Comment by ad-m** [comment]
@mrbojko czy możesz sprawdzić na skrzynce w zenbox czy na pewno wiadomość nie zniekształciła się w transporcie?

**Comment by Roksana90** [comment]
@ad-m hm, to nie wiem, może akurat w tym konkretnym przypadku gmina zignorowała część pytań. Ale nie zmienia to faktu, że gdy w Fedrowaniu odpowiedź jest przedstawiana tak jak na moim pierwszym zrzucie ekranu w wątku, to do SJJ zaciągamy niekompletne odpowiedzi, nawet jeśli w cytacie są kompletne. Wiem, bo natknęłam się na to, przeglądając bazę danych z SJJ już po oznaczeniu odpowiedzi przez użytkowników.

**Comment by mrbojko** [comment]
> @mrbojko czy możesz sprawdzić na skrzynce w zenbox czy na pewno wiadomość nie zniekształciła się w transporcie?

Sprawa jest dosyć zagadkowa, bowiem w main4 nie ma tej wiadomości. Zagadkowa w tym sensie, że coś/ktoś musiało usunąć te wiadomości ze skrzynki według jakichś dosyć dziwnych reguł:
![obraz](https://user-images.githubusercontent.com/47541542/148367464-7fc42113-462f-4842-8f6b-4885f92f4588.png)
W sierpniu wygląda na to, że są wiadomości, z lipca cztery, z czerwca jedna, potem jedna grudzień 2020, jedna maj 2020...
Ewentualnie wiadomości zostały usunięte z automatu, a te starsze to są odzyskane niedawno po usunięciu błędów w imap-to-webhook

**Comment by mrbojko** [comment]
@Roksana90 
> A w cytacie jest tylko treść naszego wniosku. 

Ale wiadomość kończy się słowami POZDRAWIAMY i stopką (w formacie graficznym). Tak jakby gość olał dalsze pytania.

> 
> A kopii nie mogę pobrać, chrome w ogóle nie reaguje a Edge informuje, że to pliki niebezpieczne.

To mechanizm zabezpieczający przed atakami zewnątrz. Co do zasady nawet rozumiem, że twój komputer boi się Adama, on faktycznie jest groźny. Firefox pozwala ominąć te zabezpieczenia. Jest zrezygnowany i nieszczęśliwy, ale przynajmniej pozwala pobrać wiadomość. Co wiele nie zmienia - wygląda prawie tak samo jak w fedrowaniu.

**Comment by ad-m** [comment]
> Ewentualnie wiadomości zostały usunięte z automatu, a te starsze to są odzyskane niedawno po usunięciu błędów w imap-to-webhook

Nie usuwamy wiadomości automatycznie, ale robimy to sporadycznie manualnie (piszę ci w tym sprawie wiadomości), gdy mamy wiarę, że importowanie działa. Możliwe, że jest to zbyt stara wiadomość. Te kilka bardzo starych wiadomości to też przypuszczam, że zmiany wokół imap-to-webhook.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m @mrbojko podbijam temat. 

Problem polega na tym, że czasem jak urzędy odpisują, to ich odpowiedzi w ogóle albo częściowo nie widać w tym podstawowym polu wyświetlającym odpowiedź:

![image](https://user-images.githubusercontent.com/36925935/149756270-4cab5e21-eaba-4b32-9563-55ef1025113a.png)
(powyżej odpowiedź kończy się na pytaniu 3 i dalej już się nie da zjechać suwakiem)

Ale jak się kliknie w "pokaż cytat", to wtedy  widoczna jest pełna odpowiedź:

![image](https://user-images.githubusercontent.com/36925935/149756631-d2eb6b7a-83d9-414d-9ee7-db2ca8005512.png)
(powyżej widać odpowiedź na pyt. 4 i można dalej zjechać suwakiem, gdzie są dalsze odpowiedzi - obydwa screeny dotyczą tej samej odpowiedzi i sprawy https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-957)

Czasem odpowiedź widać tylko w "pokaż cytat".

Problem jest taki, że to co jest widoczne pod "pokaż cytat" nie jest zaciągane do SJJ, więc trafiają tam odpowiedzi niepełne.

Próbowałam pobrać te listy, które wskazywała Roksana, jako przykłady powyższych sytuacji, ale nie mogę dodać eml na github. A Adam prosił o przesłanie tych wiadomości inaczej - niestety nie wiem, co mam zrobić.

Żebym pamiętała, o które sprawy chodzi, wklejam linki raz jeszcze, a Wy dajcie znać, w jakiej formie tych maili potrzebujecie albo co powinnam jeszcze dopisać, żeby problem był dla Was lepiej zrozumiały.

https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-2222
https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-772
https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-957
https://fedrowanie.siecobywatelska.pl/sprawy/kto-zabiera-glos-na-facebooku-1838

**Comment by mrbojko** [comment]
@ad-m niestety maile nie zachowały się na Zenboksie :-(, natomiast "my educated guess" to błędna interpretacja tagu kończącego cytat przez pareser na Fedrowaniu. Programy pocztowe robią z tymi tagami niezły bałagan, a wygląda na to, że fedrowanie szuka pierwszego tagu </blockquote> i na nim urywa wiadomość:

Tak to wygląda w fedrowaniu:
![obraz](https://user-images.githubusercontent.com/47541542/149763484-a5cc064d-afea-4c0c-8045-90b10893015c.png)


A tak HTML maila z tego miejsca:
![obraz](https://user-images.githubusercontent.com/47541542/149763445-0c53b741-4f9c-4962-8b34-fb4d7b1bb08e.png)

**Comment by Roksana90** [comment]
Podobne podejrzenie (odpowiedź w cytacie, która chyba przez to nie trafiła do analizy w SJJ) miałam w przypadku tego dokumentu:
https://fedrowanie.siecobywatelska.pl/sprawy/raport-o-stanie-gminy-jak-jest-tworzony-1519
W Fajnych danych jest FD wystąpiło 3 razy, na jednym jest tylko przewodnie info: ,,W odpowiedzi na Państwa wniosek przekazujemy informację odnośnie poniższych punktów. Właściwe odpowiedzi
zostały podkreślone.", potem 2 pozostałe to puste dokumenty. Brakuje za to czegokolwiek z odpowiedzią.

**Comment by PiotrIw** [comment]
po przejściu na wyświetlanie zartości html, treść listów nie jest obcinana

**Comment by dzemeuksis** [comment]
@PiotrIw , prawdę mówiąc te przykłady podane w komentarzach nadal wyglądają tak samo, tj. na obcięte. Więc jeśli miałeś na myśli, że nowe listy od czasu zmiany, o której wspominasz, są już pełne, to ok. Ale jeśli przejście na wyświetlanie zawartości html miało pomóc również wstecznie, to tak się nie zadziało.

**Comment by PiotrIw** [comment]
@dzemeuksis - założyłem (może błędnie) że monitoring jest już zamknięty i nie analizowałem wstecznie.
@Roksana90 - czy sprawdzić i naprawić jeśli możliwe te historyczne maile?
