### ISSUE TITLE
Wprowadzenie możliwości archiwizacji instytucji

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1141]
Potrzebna jest możliwość oznaczenia instytucji, jako zarchiwizowanej. A za tym:
1. Zablokowanie możliwości wysłania czegokolwiek do takiej instytucji.
2. Zablokowanie możliwości przypisania takiej instutucji do nowego monitoringu.
3. Przemigrowanie instytucji oznaczonych, jako archiwalne w inny sposób.

Szczegóły powyżśzych do ustalenia w toku dyskusji i propozycji.

**Comment by dzemeuksis** [comment]
@PiotrIw 
Temat pozostaje aktualny (acz nie pilny), przykład realnej sytuacji z życia, gdzie taki mechanizm byłby przydatny widać w #1142. Być może należy tę koncepcję rozpatrywać w dodatkowym kontekście #1151

**Comment by dzemeuksis** [comment]
Nie jestem do końca pewny na ten moment, jak sytuacje stojące za tym zgłoszeniem powinny być modelowo obsługiwane. Zamykam na razie, najwyżej jak temat wróci, to się odgrzebie.

**Comment by PiotrIw** [comment]
@dzemeuksis a co z naszym ustalenim że na razie robimy tylko blokadę nowej wysyłki dla instytucji zarchiwizowanej, a pojawia się nadal w starych monitoringach?

**Comment by dzemeuksis** [comment]
Racja. Jak masz przestrzeń, by to zrobić i masz poczucie, że to ma sens, to tak zrób.

**Comment by PiotrIw** [comment]
zaimplementowane w v1.1.18
-instytucja archiwalna pokazuje się na liście lecz nie można jej wybrać do wysyłki w istniejącym monitoringu, nie ma jej naliście do przypisania dla nowego monitoringu, nie można do niej pisać maili:
![image](https://github.com/watchdogpolska/feder/assets/36678620/fc4e0d63-c9ee-4899-bb9c-96a6acb5e38d)
![image](https://github.com/watchdogpolska/feder/assets/36678620/d42020d9-b340-43e6-b10b-071a5a09c115)

**Comment by dzemeuksis** [comment]
Nie wiem, czy to problem, ale można ręcznie założyć sprawę dla archiwalnej instytucji:
![obraz](https://github.com/watchdogpolska/feder/assets/33778688/e71ec7af-7555-49e5-81b4-46496ba679ee)

**Comment by dzemeuksis** [comment]
Tu na stagingu dokończyłem i się udało:
![obraz](https://github.com/watchdogpolska/feder/assets/33778688/b0c45393-3042-4eda-a7ee-555fed3ea8e7)
Ale chyba bym to tak zostawił, jako taki ręczny myk w razie potrzeby.

**Comment by dzemeuksis** [comment]
Co się stanie, jeśli w istniejącym monitoringu wyślemy wiadomość masową na podstawie tagu przypisanego do instytucji zanim została oznaczona, jako archiwalna? Czy przy takiej wysyłce taka instytucja zostanie pominięta?

**Comment by PiotrIw** [comment]
Tak zostanie pominięta. Filtr jest założony dwa razy:
- w widoku listy do przypisywania tagów
- w funkcji definiowania spraw do wysyłki dla wybranych tagów

:)
