### ISSUE TITLE
Problem z wymuszaniem parametru "created=" w celu uzyskania kompletu wyników

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1144]
Referując dyskusję ze Slacka:

Ekipa SJJ zaczęła dostawać puste wyniki dla monitoringu. Przyczyną okazało się wymuszenie parametru "created" na poziomie URLa, którego domyślnie nie podawali a wówczas system wyświetlał domyślnie sprawy wyłącznie z 2022 roku. Żeby tego uniknąć musieliby wdrożyć u siebie zmianę, polegającą na standardowym przekazywaniu tego parametru, ale pustego, co oceniają, jako błędogenne:

> Wolałbym nie ustawiać daty w URLu, bo będziemy podatni na błędy, lepiej wyświetlać wszystkie możliwe wyniki w ramach monitoringu, bo już i tak filtrujemy względem powiatu. Ewentualnie mogę ustawić datę na pustą, żeby usunąć filtrowanie - to jest dla mnie znacznie wygodniejsze i bezpieczniejsze.

Proponują zatem, by Fedrowanie nie wymuszało podania tego parametru dla zwrócenia kompletu wyników, tylko w przypadku braku jego podania nie filtrowało po dacie wcale:

> Mógłbym zmodyfikować linki tak, żeby filtrowanie zawierało created= ,ale szczerze mówiąc bardziej eleganckie byłoby usunięcie tego domyślnego filtra na Fedrowaniu.

Jeśli chcemy ograniczyć domyślne wyświetlanie zbyt wielu spraw ze względów wydajnościowych, to żeby wilk był syty i owca cała, można by może nakładać go z poziomu frontendu, czyli to pole listy rozwijanej z wyborem daty domyślnie mogłoby mieć wybrany bieżący rok (czyli użytkownik świadomie musiałby to zmienić), ale już na poziomie URLa nie wymuszać podawania pustego parametru. 

@ad-m , ustosunkujesz się do tego, albo podpowiesz z kim o tym rozmawiać?

**Comment by ad-m** [comment]
Czy mogę prosić o przykłady tych linków?

śr., 23 lut 2022, 13:24 użytkownik dzemeuksis ***@***.***>
napisał:

**Comment by dzemeuksis** [comment]
> po wejściu w konkretny powiat, np. tutaj: https://fedrowanie.siecobywatelska.pl/sprawy/?monitoring=57&voivodeship=24&county=2401(...) dostajemy puste wyniki. 

Na to zaradziłem dodając pusty created: https://fedrowanie.siecobywatelska.pl/sprawy/?monitoring=57&voivodeship=24&county=2401&created=

**Comment by dzemeuksis** [comment]
SSJ poradzili sobie na razie wdrażając zmianę po swojej stronie. Przy czym zrobili to tak, żeby być przygotowanym na to, że ten parametr przestanie być wymuszany dla niefiltrowania po dacie.

**Comment by dzemeuksis** [comment]
@PiotrIw , w skrócie dla wyszukiwań takich jak:
https://fedrowanie.siecobywatelska.pl/sprawy/?monitoring=57&voivodeship=24&county=2401
nie dostaniesz wyników, jeśli nie rozszerzysz urla o parametr created, nawet jeśli zostanie pusty, czyli tak:
https://fedrowanie.siecobywatelska.pl/sprawy/?monitoring=57&voivodeship=24&county=2401&created=

Czyli tutaj moglibyśmy chyba bez szkody dla niczego nie wymagać podania created, skoro i tak pozwalamy podać go pustego. Nie jest to ani pilne ani ważne, ale ma chyba sens, więc zostawiam.

**Comment by PiotrIw** [comment]
@dzemeuksis , a dlaczego oni nie korzystają z API? łatwiej niż skrobać front, API do tego jest stworzone :)
https://fedrowanie.siecobywatelska.pl/api/cases/?monitoring=57&voivodeship=24&county=2401

**Comment by dzemeuksis** [comment]
W sumie racja, zamykam zatem.
