### ISSUE TITLE
Nieprawidłowe dane w cytacie do "Wiadomości masowej"

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1146]
Do domyślnego cytatu wysyłanego w ramach "Wiadomości masowej" zdaje się wskakiwać na sztywno data, godzina i adres email urzędu, z którym korespondencja jest kontynuowana. Problem w tym, że przy masowej wysyłce te dane będą w najlepszym razie pasowały do jednego urzędu a w przypadku wszystkich pozostałych mogą być mylące.

![niepasujacy_email_data_godzina](https://user-images.githubusercontent.com/33778688/155347305-28c14de9-3563-4264-b9ae-25233b01fa53.png)

Jeśli da się to jakoś łatwo zrobić, to sugeruję, żeby te dane usunąć i zostawić jedynie: "W nawiązaniu do pisma" i dalej cytat.

**Comment by dzemeuksis** [comment]
https://fedrowanie.siecobywatelska.pl/monitoringi/udzial-gmin-w-ochronie-lasow-2/~wiadomosc-masowa

**Comment by ad-m** [comment]
Problem jest tu https://github.com/watchdogpolska/feder/blob/869a17b8242ec2851623708d99089c3089395517/feder/monitorings/forms.py#L111-L117 ale dziś już się tym nie zajmę.

**Comment by dzemeuksis** [comment]
Gdyby to było wykonywane osobno dla każdej z masowo wysyłanych wiadomości (a nie że tylko idzie do foremki na frontend i stamtąd się przekleja to samo do wszystkich), to zgaduję, że w drugiej linijce cytowanego kodu trzeba by przed _order_by_ dodać _filter_ na _email_, albo _instiution_id_, czy coś w tym rodzaju. Dobrze kombinuję?

Niestety analiza cytatów załączanych do ponawianych masowo monitoringów pokazuje, że to nie jest wykonywane dla każdej instytucji osobno, tylko raz wykonane leci do wszystkich to samo. Czyli nawiązanie do emaila i daty w nagłówku cytatu jest niemal zawsze błędne i mylące.

Dlatego według mnie poprawienie filtrowania we wskazanym miejscu zmieni tylko tyle, że jeśli będziemy ponawiać wysyłkę dla jednego podmiotu, to taki przypadek będzie poprawnie obsłużony. Jeśli jednak do wysłania będzie wskazana więcej niż jedna instyutucja, to znowu prawidłowy wyjdzie tylko jeden przypadek a wszystkie pozostałe instytucje dostaną mylący nagłówek, bo odnoszący się do innej instytucji.

Dlatego wydaje mi się, że najprościej na szybko po prostu zmienić:
https://github.com/watchdogpolska/feder/blob/869a17b8242ec2851623708d99089c3089395517/feder/letters/forms.py#L17
Na:
`QUOTE_TPL = "W nawiązaniu do pisma:\n{quoted}" `

To drugie rozwiązanie jest de facto tym, co obecnie należy zrobić ręcznie przed wysłaniem, żeby nie wysyłać mylących danych i co pozwoliłem sobie zrobić wysyłając do gmin doprecyzowanie monitoringu dla LiO.

**Comment by dzemeuksis** [comment]
@PiotrIw , tu nadal jest problem. Ponieważ jego opis jest skomplikowany a jednocześnie istnieje ręczny workaround (tylko trzeba o nim pamiętać), to zweryfikuj jedynie, czy moja propozycja jest bezpieczna (i odwołuje się do właściwego miejsca w kodzie) i jeśli tak, to ją wdróż przy okazji, tj.:

Po prostu zmień:
https://github.com/watchdogpolska/feder/blob/869a17b8242ec2851623708d99089c3089395517/feder/letters/forms.py#L17
Na:
`QUOTE_TPL = "W nawiązaniu do pisma:\n{quoted}" `
Albo ogólnie, albo dla wiadomości masowej stwórz osobny szablon i tę zmianę zrealizuj tylko w nim.

Czyli wywal z szablonu odniesienie do daty i adresu oryginalnego pisma, bo - jak pisałem - w przypadku wiadomości masowej wskakują te same dane (data i email) do wszystkich, a więc nie mogą być prawdziwe.

Ten szablon działa dobrze i sensownie w przypadku kiedy klikasz "Odpowiedz" na konkretną wiadomość, ale stosowanie go w wiadomości masowej jest z jakiegoś powodu błędnie zrealizowane. Przy odpowiadaniu ma sens, oto przykład:

![obraz](https://github.com/watchdogpolska/feder/assets/33778688/566cf107-fb9f-4341-948c-c3c3a91acd8e)

**Comment by PiotrIw** [comment]
poprawione w wersji 1.1.12 (prawidłowa data i osobny mail do każdej sprawy)
