### ISSUE TITLE
Sposób wysyłania załączników poprzez "Wiadomość masową"

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1148]
Lasy i Obywatele napotkały problem z wnioskami do nadleśnictw, polegający na zakwestionowaniu mejlowej formy wniosku, jako nie dającej pewności doręczenia. Doszło więc do ponownej wysyłki z załączeniem elektronicznie podpisanego PDFa i jego skompresowanej wersji. Niestety tym razem nadlleśnictwa zgłaszają, że załączniki widzą, jako linki a ich informatycy zabraniają takich kilkać ze względów bezpieczeństwa. W związku z tym nasuwają się następujące pytania:

1. Czy tak jest w istocie, że załączniki do wiadomości wychodzą z Fedrowania, jako linki?
2. Czy jest racjonalnym dodać opcjonalną możliwość załączania załączników, jako faktycznych załączników?
3. Czy jest jakiś sposób, żeby doraźnie, jednorazowo, przez jakąś zmianę w konfiguracji, wymusić wysyłkę realnych załączników (to byłoby niecałe 300 KB do 321 nadleśnictw)?

Chodzi o te załączniki dodawane tutaj: https://fedrowanie.siecobywatelska.pl/monitoringi/udzial-gmin-w-ochronie-lasow-2/~wiadomosc-masowa
![obraz](https://user-images.githubusercontent.com/33778688/155523417-fd23aebf-d7dc-4a15-a4f8-0280a7a6b2bc.png)

**Comment by ad-m** [comment]
1/ Tak. Uwzględniając #1069 możesz pobrać kopie każdej wysłanej przez nas wiadomości.
2/ Możliwe.
3/ Nie ma takiej możliwości w Fedrowaniu obecnie. Wymaga to zmiany w logice wysyłki. Dokładniej to w tym pliku https://github.com/watchdogpolska/feder/blob/857f0b28e34f0ced9f74cf35770e25b151f1c8d5/feder/letters/models.py#L253-L270 . 

A także plikach tu wskazanych:

https://github.com/watchdogpolska/feder/blob/857f0b28e34f0ced9f74cf35770e25b151f1c8d5/feder/letters/models.py#L249-L250

**Comment by dzemeuksis** [comment]
Wygląda ok, na prywatny adres doszło (na sieciowym dostałem hardbounce).
Wygląda, że załączniki przechodzą (zip i pdf testowałem).

**Comment by ad-m** [comment]
Dlaczego dostałeś hard bounce?

pon., 28 lut 2022, 16:37 użytkownik dzemeuksis ***@***.***>
napisał:

**Comment by dzemeuksis** [comment]
Nie wiem tego. Czy można to jakoś sprawdzić (poza dostępem do panelu emailabs, do którego dostępu nie mam)?

**Comment by ad-m** [comment]
Codziennie logi emaillabs pobieramy do Fedrowania, więc w zakładce z
raportami doręczenia

pon., 28 lut 2022, 19:38 użytkownik dzemeuksis ***@***.***>
napisał:

**Comment by dzemeuksis** [comment]
Aaa, zaglądałem tam, ale za wcześnie, kiedy jeszcze logów dla tych mejli nie było, dzięki!

W obu przypadkach przyczyną był:
"hardbounce_desc": "host aspmx.l.google.com[108.177.14.27] said: 550-5.1.1 The email account that you tried to reach does not exist. Please try 550-5.1.1 double-checking the recipient's email address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1  https://support.google.com/mail/?p=NoSuchUser p1-20020ac246c1000000b004437db41c2esi8842555lfo.298 - gsmtp (in reply to RCPT TO command)",

No i okazuje się... że nie dałem kropki między imieniem i nazwiskiem...

Zatem mój był błąd tutaj.
