### ISSUE TITLE
Wątpliwości związane z zarządzaniem zmianami "Units of administrative division"

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1151]
1. Natrafiłem na nową, istniejącą od niedawna "Units of administrative division", której nie ma na Fedrowaniu. Co teraz? Jak najlepiej dodać nową "Units of administrative division"? Widzę że jest do tego formularz w panelu Django, ale pytanie, czy to jest właściwy sposób i procedura, czy można po prostu ją tam dodać? Czy mogę to zrobić? Czy to wystarczy w tamtym miejscu, czy może prowadzimy gdzieś jakąś ewidencję zmian "Units of administrative division" i taka zmiana powinna być gdzieś jeszcze zgłoszona/odnotowana (np. na potrzeby integracji z SJJ)?

2. W bazie Fedrowania znajduje się niekatywna "Units of administrative division". Co teraz? Widzę, że w edycji danych JST na Fedrowaniu w panelu Django jest "ptaszek" Active oraz przycisk "Usuń". Którego z nich należy w tej sytuacji użyć? I dalej, ponawiam w tym kontekście pytania z poprzedniego punktu, czyli czy mogę to zrobić, czy to wystarczy w tamtym miejscu, czy może prowadzimy gdzieś jakąś ewidencję zmian "Units of administrative division" i taka zmiana powinna być gdzieś jeszcze zgłoszona/odnotowana (np. na potrzeby integracji z SJJ)?

3. Do "Units of administrative division", która jest już nieaktywna i którą chcę w taki, czy inny sposób odpowiednio oznaczyć/usunąć jest na Fedrowaniu przypisana instytucja. Co teraz? Widzę, że chyba jest możliwość po prostu zaktualizowania przypisania "Units of administrative division" dla instytucji w panelu Django, więc nasuwa się żeby to w ten sposób zrobić. Pytanie, czy to będzie ok i czy będzie wystarczające ze względu na logikę systemu Fedrowanie, potrzeby audytowe, jego integrację z SJJ? Może w takiej sytuacji lepiej jest oznaczyć daną instytucję jako archiwalną i utworzyć dla niej nowy, osobny rekord na Fedrowaniu, wraz z właściwym obecnie "Units of administrative division"?

@ad-m , @AgnieszkaZdanowicz , @KatarzynaBatko ?

**Comment by dzemeuksis** [comment]
@ad-m napisał: 
> Michale, mamy polecenie konsoli pochodzące z django-teryt-tree, które służy do importowania i aktualizowania bazy TERYT. Lepiej nie wprowadzać zmian ręcznie.

Pytanie, czy to wyjaśnia wszystkie moje wątpliwości wyżej wyrażone? W sensie, że odpalamy te polecenie (gdzie, jak, kiedy, gdzie go szukać?) i możemy się niczym więcej nie martwić?

**Comment by dzemeuksis** [comment]
Poprawiłem temat i treść pytań, ponieważ omyłkowo używałem akronimu JST mając na myśli "Units of administrative division" identyfikowaną kodem teryt.

**Comment by ad-m** [comment]
1/ Jak wyżej. Formularza w Django lepiej nie używać.
2/ Nie usuwamy JST, a deaktywujemy.
3/ Zaktualizować Instytucje.
4/ Zgodnie z dokumentacją https://github.com/watchdogpolska/django-teryt-tree . Do wymaga bezpośredniego dostępu do serwera.

PS. JST = "Units of administrative division.

**Comment by ad-m** [comment]
Baza danych TERC została zaimportowana: https://fedrowanie.siecobywatelska.pl/admin/teryt_tree/jednostkaadministracyjna/?q=Kamieniec+Z%C4%85bkowicki

**Comment by dzemeuksis** [comment]
Dziękuję! To jeszcze jedno pytanie.

Po tym imporcie pojawiły się trzy nowe, obecnie właściwe dla Kamieńca Ząbkowickiego jednostki podziału terytorialnego, ale ta, którą zastąpiły, już obecnie nieistniejąca w sensie prawnym (id [0224032](https://fedrowanie.siecobywatelska.pl/admin/teryt_tree/jednostkaadministracyjna/0224032/change/?_changelist_filters=q%3DKamieniec%2BZ%25C4%2585bkowicki)), pozostała w bazie w statusie "active".

Pytanie zatem brzmi, czy to nie przeszkadza i tak ją już zostawiamy, czy może raczej ręcznie, z poziomu Django "odptaszkowujemy" status "active"?

**Comment by ad-m** [comment]
To należałoby zgłosić w projekcie django-teryt-tree , aby naprawiono to w importerze tam. To z korzyścią także dla innych projektów SOWP, które korzystają z tej biblioteki np. small-eod.

**Comment by dzemeuksis** [comment]
Rozumiem, zgłosiłem tam.

Pozostaje kwestia, czy tymczasem warto dezaktywować archiwalny teryt ręcznie z poziomu Django czy lepiej nie ruszać?

Bo np. co się wtedy stanie z powiązaną z nim instytucją? Czy ona będzie nadal widoczna? Czy jeśli w przyszłości spłynie do niej jakaś odpowiedź z jakiegoś monitoringu, to czy zostanie do niej prawidłowo przypisana? Nic się nie wysypie?

Czy może jakimś magicznym sposobem można przekierować automatycznie sprawy na "nową wersję" danej istytucji, przypisanej do nowego, właściwego dla niej terytu?

Zdaję sobie sprawę, że odpowiedzi na te pytania mogą wymagać głębszej analizy kodu lub dokumentacji, więc teraz tylko luźno pytam na wypadek, gdyby to było jednak oczywiste.

**Comment by dzemeuksis** [comment]
@PiotrIw , to zagadnienie pozostaje - przynajmniej w części - do przemyślenia, ale chyba bardziej na poziomie technicznym, niż funkcjonalnym. Trochę o tym rozmawialiśmy kiedyś przez telefon przy aktualizacji TERCów. Co z sytuacjami, kiedy zmienia się TERC jednostki samorządu terytorialnego? Czy powinno się utworzyć nową jednostkę z nowym TERCiem? Jeśli tak, to co dotychczasową korespondencją z tą JST? Przepinać, archiwizować, inaczej? Trzeba przy tym pamiętać, że użytkownika końcowego nie obchodzą żadne TERCI - kiedy wchodzi w gminę Kamieniec Ząbkowicki, to chce mieć od razu widok na całą koresponedncję z tym podmiotem. A nie że jak się kiedyś tam zmienił TERC, to trzeba szukać części korespondencji gdzieś indziej - to nielogiczne, użytkownik może o tym nawet nie wiedzieć, że takie rzeczy się dzieją, zresztą nawet jakby wiedział, to nadal jest kompletnie zbędną komplikacją z jego punktu widzenia. Ponieważ jednak część kwestii z tego wątku jest jakoś tam wyjaśniona/nadmiarowa, to dla porządku na teraz zamknę a najwyżej kiedyś wrócimy do tematu.
