### ISSUE TITLE
Spam podpina się do niektórych spraw

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1154]
Zauważyłem, że do niektórych spraw podpina się automatycznie sporo spamu, np.:
https://fedrowanie.siecobywatelska.pl/sprawy/sedziowie-w-sadach-powszechnych-149

Pytanie, czy coś z tym można/-gę/trzeba robić?

**Comment by dzemeuksis** [comment]
Zamknąłem, bo duplikat: https://github.com/watchdogpolska/feder/issues/940

**Comment by ad-m** [comment]
Moglibyśmy rozszerzyć Fedrowanie, aby flagować jakoś wiadomości w starych
sprawach, zważywszy, że prawdopodobieństwo zwykłej odpowiedzi w nich jest
niskie.

czw., 17 mar 2022, 11:14 użytkownik dzemeuksis ***@***.***>
napisał:
