### ISSUE TITLE
ukrycie monitoringu Samorządy o liczbę wniosków 2017

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#1156]
@ad-m czy Ty wyjąłeś ten monitoring z kwarantanny? Ja go oczyściłam z danych osobowych, ale tylko tych, które wskazał Pan składający na nas skargę. Co do reszty nie mam pewności, a nie chcę, żebyśmy mieli więcej problemów. Dlatego lepiej potrzymać ten monitoring jako ukryty. Nie wiem, jak ukryć cały monitor - czy ja to mogę sama zrobić?

**Comment by AgnieszkaZdanowicz** [comment]
przepraszam, już sprawdziłam, że jego widać tylko, jak jestem zalogowana. Zamykam sprawę.

**Comment by ad-m** [comment]
Nie ma mechanizmu ukrywania monitoringu, tylko kwarantanna spraw.

pon., 4 kwi 2022, 06:43 użytkownik AgnieszkaZdanowicz <
***@***.***> napisał:
