### ISSUE TITLE
HTTP 404 rzucane przez API

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1157]
Dziwna sprawa. Jak się wejdzie na stronę: https://fedrowanie.siecobywatelska.pl/api/records/?case=&o=&page=1187 to tam z poziomu przeglądarki wszystko wygląda w porządku. Jest obecnie 1187 stron do przewinięcia i każda zdaje się zawierać właściwy content. Kiedy jednak pytam z poziomu Pythona, to poprawne odpowiedzi dostaję do strony 1040 włącznie.

Czyli przykładowo wykonanie kodu:
> import json
> import urllib.request
> url = "https://fedrowanie.siecobywatelska.pl/api/records/?case=&o=&page=1040"
> webURL = urllib.request.urlopen(url)

zakończy się sukcesem. Podobnie jak dla, jak się zdaje, każdej strony mniejszej niż 1040ta.

Jednak w przypadku 1041 i większej (aż do 1187) skrypt wyrzuca błąd urllib.error.HTTPError: HTTP Error 404: Not Found.

O co tu może chodzić?

**Comment by dzemeuksis** [comment]
Już wiem, o co chodzi. Strony do 1040 są dostępne publicznie, kolejne jednak już tylko dla zalogowanych użytkowników (i być może z jakąś określoną rolą, ale to nieistotne).

@ad-m , można coś z tym zrobić?

**Comment by PiotrIw** [comment]
Przetestowałem, działa poprawnie do samego końca (1160) bez zalogowania - może chodziło o timeout w urllib?

**Comment by dzemeuksis** [comment]
@PiotrIw , zerknij na poprzedni komentarz. Natomiast ja nie twierdzę, że to trzeba poprawiać, bo nie jestem na ten moment pewny, w którą stronę, tzn. które z opisanych zachowań jest porządane i powinno dotyczyć spójnie całości.

**Comment by PiotrIw** [comment]
@dzemeuksis - a ja sprawdzałem czy to samo widzi niezalogowany w przeglądarce i w urrlib - dostają to samo.
Jeśli chodzi o różnicę ilości rekordów dla niezalogowanych i zalogowanych to jest to działanie zamerzone, niektóre monitoringi są ukryte dla niezalogowanych. Nie widać ich na web ani na API, stąd krótsza lista, jednak jak poparzysz na osttni rekord z listy API to będzie ten sam dla zalogowanych i niezalogowanych (177842 w momencie mojego testu).
![image](https://user-images.githubusercontent.com/36678620/236865127-6902d151-df5a-4791-b17b-1c36515f99f2.png)

**Comment by dzemeuksis** [comment]
Rozumiem, teraz jasne.
