### ISSUE TITLE
Zakład Usług Komunalnych w Mieleszynie dostaje korespondencję z Oleśnicy

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1159]
Ta oto instytucja: https://fedrowanie.siecobywatelska.pl/instytucje/zaklad-uslug-komunalnych-i-rolniczych-sp-z-oo
ma wszystkie dane wskazujące na instytucję o tej nazwie z Mieleszyna w powiecie Gnieźnieńskim... poza emailem do kontaktu, który wskazuje na insytucję o tej samej nazwie, ale w Oleszycy w powiecie Lubaczowskim.

I teraz tak, istnieje już korespondencja z tym podmiotem, który na nią nawet odpowiedział. Tzn. z tym w Oleszycy, bo do niego prowadzi email.

Jak to najlepiej wyprostować? Jeśli podmienię email na prawidłowy dla instytucji, tzn. wskazującej na Zakład w Mieleszynie, to nadal pozostanie skojarzona z tym podmiotem korespondencja, która powinna być przypisana do Zakładu w Oleszycy (na ten moment nie istniejącego w naszej bazie).

Jeśli zostawię email a podmienię dane... no właśnie, czy w ogóle da się podmienić podstawowe dane, czy wtedy to już z definicji powstanie nowy podmiot? A jeśli tak, to czy można potem przepisać do niego korespondencję przypisaną błędnie do Mieleszyna?

Jak do tego najlepiej podejść w kontekście modelu danych i struktury Fedrowania?

@ad-m, @KatarzynaBatko , @AgnieszkaZdanowicz , mieliście w przeszłości podobne sytuacje? Jak do nich podchodziliście?

**Comment by AgnieszkaZdanowicz** [comment]
@dzemeuksis ja miałam podobnie z kilkoma gminami, ale tam było prościej, bo te wszystkie urzędy gmin już istniały i były w monitoringu, tylko maile do nich były na odwrót. I wtedy "przepinałam" listy do właściwej sprawy - wiesz, co mam na myśli?

Tutaj to jest problem, że nie ma tej instytucji właściwej w ogóle, już nie mówiąc, że w tym monitoringu. Stworzyć ją można zawsze, ale żeby dodać do monitoringu, to trzeba by wysłać wniosek, co jest bez sensu, bo oni już przecież wniosek dostali.

Podsumowując, nie wiem, jak to rozwiązać niestety przy aktualnych możliwościach. Mamy podobny problem w Wydanych Danych, gdzie do 10 gmin wnioski nie poszły, bo nie mieliśmy ich w bazie w ogóle, a jak to odkryliśmy, to wnioski już składaliśmy przez ePUAP. Więc tych 10 gmin nie ma w monitoringu.

**Comment by dzemeuksis** [comment]
> I wtedy "przepinałam" listy do właściwej sprawy - wiesz, co mam na myśli?

Prawdę mówiąc nie. W sensie że jest taka opcja, żeby przepiąć list z jednej sprawy do innej? Podpowiesz, jak to zrobić?

**Comment by AgnieszkaZdanowicz** [comment]
Ad1) Jak "przepinam" listy - wchodzę w list, klikam "edytuj" i tam jest m.in. pole "sprawa", w którym wybieram tę sprawę, do której list powinien był trafić. Żeby wybrać tę sprawę, wpisuję w pole "sprawa" nazwę instytucji i ona się pokazuje razem z nazwami monitoringów - wtedy wybieram ten właściwy. Problem jest tylko, jak jest kilka instytucji o tej samej nazwie - to wtedy trzeba jeszcze sprawdzić ten numerek po # - nie wiem, czy dobrze to tłumaczę. Jeśli nie, to napisz, spróbuję może z printscreenami.

Ad2) W sensie, że edytować monitoring i treść wysyłanej w ramach monitoringu wiadomości (czyli "szablon")? No nie wpadałbym na to! Tylko trzeba potem pamiętać, żeby zmienić po wysyłce na pierwotny wniosek, bo jak ktoś inny nie będzie wiedział, że treść jest zmieniona, a będzie chciał jednak zrobić jeszcze wysyłkę do kolejnych gmin, to te inne mogą dostać życzenia świąteczne w lipcu ;)

**Comment by dzemeuksis** [comment]
Ad. 1 - Mechanizm właściwego dobrania sprawy do przypisania jest dla mnie jasny, bo na co dzień przypisuję zagubione listy i tam często są tego typu sytuacje, że trzeba zwracać uwagę na numer. Nie wiedziałem jedynie, jak przepisać taki list już ze sprawą skojarzony. Teraz już wiem, dziękuję!

Ad. 2 - To prawda, ale wydaje mi się, że zmiana treści wysyłanego wniosku zdarzała się już w przeszłości na Fedrowaniu. Zresztą ktoś może to niechcący zmienić, więc chyba zawsze warto sprawdzać przed wysłaniem, co się de facto wyśle. Oczywiście lepiej świadomie nie zostawiać takich ewentualnych zaślepkowych listów z życzeniami, czy czymś tam, to jasne - w razie czego będę uważał. :)

**Comment by dzemeuksis** [comment]
Prędzej, czy później, jakoś trzeba będzie to wyprostować.

@KatarzynaBatko , czy mogę wysłać do kilku spółek komunalnych z poziomu Fedrowania i monitoringu "Jawność w spółkach komunalnych" wiadomość tego typu:
> Tytuł: Wiadomość techniczna - niewymagane działanie
> Treść:
> Uwaga: to jest wiadmość techniczna, żadne działanie nie jest wymagane.
> Z jawnościowym pozdrowieniem!
> Stopka: oryginalna
Ewentualnie czy masz lepszy pomysł na treść takiej wiadomości?

@ad-m , czy dostrzegasz inne wyjście? Czy jest możliwe/sensowne z poziomu bazy danych przypisać określone instytucje (na podstawie listy - zebrałbym na raz wszystko, co zaobserwowałem) do wskazanego monitoringu, żeby uniknąć wysyłania takich technicznych wiadomości? Jeśli tak, to kto może to zrobić? Ty, @mrbojko , ktoś inny?

**Comment by dzemeuksis** [comment]
@AgnieszkaZdanowicz , @KatarzynaBatko , @ad-m , chyba udało mi się znaleźć legitny sposób, nie wymagający kombinowania, jak koń pod górę. :)

Wydaje mi się, że w takiej sytuacji można skorzystać z opcji "Utwórz sprawę" w ramach danego monitoringu, np.: https://fedrowanie.siecobywatelska.pl/sprawy/~utworz-44 ? Wygląda na to, że w ten sposób dodam nową instytucję do monitoringu zupełnie bezinwazyjnie. Przetestowałem to na lokalnie postawionej instancji Fedrowania i tak to się właśnie wydaje działać! Jedyna kwestia wymagająca ostrożności, to zgodne z konwencją nadanie nazwy sprawie.

Nie trzeba wówczas wysyłać żadnych bezsensownych wiadomości, ani kombinować na poziomie bazy danych, wszystko dam radę ogarnąć. Przydałoby się tylko potwierdzenie od Was, że mogę użyć tej opcji w ten sposób, że do tego służy.

**Comment by dzemeuksis** [comment]
Dobra, jestem już pewny, że to tak działa. Wyprostowałem na produkcji jeden skomplikowany przypadek - akurat nie ten z tego opisu, ale podobny. I jest git, wszystko wygląda tak, jak powinno. Zamykam wątek.
