### ISSUE TITLE
Filtrowanie spraw na ekranie monitoringu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#116]
![zaznaczenie_856](https://cloud.githubusercontent.com/assets/3618479/18619725/610c9c22-7e04-11e6-9475-0097fc34f9fb.png)

**Comment by ad-m** [comment]
To wymaga bardzo dobrej znajomości SQL, albo silnego cache.

**Comment by kbiernat** [comment]
Albo rest-api i kawałka kodu we frontendzie

24 sie 2017 21:52 "Adam Dobrawy" <notifications@github.com> napisał(a):

**Comment by ad-m** [comment]
@kbiernat , nie wiem co by pomogło REST API. Problem wynika z tego, że tam jest nested-tree, a w dodatku nie masz bezpośredniej relacji.
Masz strukturę JST:
- mazowieckie,
  - warszawski
    - Warszawa
    - sąsiad Warszawy

To jest opakowane w django-mptt.
Z JST masz relacje do ``Institution``, a z ``Institution`` do ``Case``. Prawidłowo zatem należy wyświetlać:

- mazowieckie (4 +3),
  - warszawski (4 +3),
    - Warszawa (4)
    - sąsiad Warszawy (3)

Takie zapytania przy nested-tree nie są trywialne, jeżeli mają być wydajne.

Nie możesz wyświetlić całego drzewka naraz. Musisz wyświetlać nadrzędnych + 1 poziom niżej, aby zachować czytelność wyświetlenia kilku tysięcy gmin w Polsce.

**Comment by AgnieszkaZdanowicz** [comment]
To aktualne

**Comment by dzemeuksis** [comment]
@PiotrIw , chyba mówiłeś o czymś takim i miałeś jakiś pomysł, żeby to zrobić, nie?

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz @dzemeuksis 
zaimplementowane w v1.1.11, 
dodałem także liczniki na stronach województw, oraz tabelę z licznikami spraw i instytucji na głównej:
![image](https://github.com/watchdogpolska/feder/assets/36678620/896d5736-43a0-40da-a338-591ab15dae55)
![image](https://github.com/watchdogpolska/feder/assets/36678620/2952a1b3-d90f-4eb5-b26d-5222c2cda931)
![image](https://github.com/watchdogpolska/feder/assets/36678620/77f4e1ae-984a-4e38-b9e0-1ea38736fb42)
