### ISSUE TITLE
mechanizm do akceptacji pism przed opublikowaniem

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#1160]
Mamy problem z tym, że instytucje potrafią nam udostępnić informacje zawierające dane osobowe - z tego względu chcielibyśmy wprowadzić mechanizm, który wymusi na nas przejrzenie odpowiedzi zanim zostaną opublikowane na stronie. Może to co prawda nas zalać, jak trzeba będzie zweryfikować kilka tysięcy odpowiedzi. Dlatego to trzeba dobrze zaprojektować - może żeby można było wybrać, czy  w danym monitoringu chcemy weryfikować odpowiedzi przed publikacją. Bo czasem zadajemy takie pytania, że w odpowiedziach na pewno nie pojawią się żadne dane chronione i wtedy nie ma potrzeby weryfikacji.

**Comment by dzemeuksis** [comment]
Prawdopodonie jednym z najprostszych do wykonania rozwiązań (o ile dobrze rozumiem niuanse Federowania, wciąż się uczę) byłoby dodanie na poziomie mointoringu flagi odpowiedzialnej za "domyślne ustawianie spraw jako "poddanych kwarantannie". Jeśli ta opcja na poziomie monitoringu byłaby "zaptaszkowana", to każda sprawa, która powstałaby w ramach tego monitoringu, otrzymywałaby "na dzień dobry" status "poddana kwarantannie". Który to status oczywiście w edycji sprawy, po uprzedniej jej weryfikacji, można by było odptaszkować.

@AgnieszkaZdanowicz , czy myślisz, że byłoby to wystarczające?

**Comment by AgnieszkaZdanowicz** [comment]
@dzemeuksis brzmi jak dokładnie to, o co nam chodzi!

**Comment by dzemeuksis** [comment]
Wydaje mi się, że zrealizowałem to wymaganie. Przetestowałem, na ile mogłem, lokalnie i wydaje się, że niczego nie psuje i jednocześnie realizuje wymaganie w opisanym wyżej kształcie.

Szczegółowy opis rozwiązania podlinkował się automatycznie powyżej (https://github.com/watchdogpolska/feder/pull/1161, trochę wyszedł bełkot, bo mieszam kwestie techniczne z funkcjonalnymi, ale jak coś niejasne, to mogę rozwinąć).

Wdrożenie rozwiązania wymaga, jak się zdaje, zaakceptowania przez @ad-m Nie jest to bagatelne, ponieważ nie wiem, na ile zaproponowane rozwiązanie wpisuje się w model i logikę aplikacji, na ile spełnia standardy kodowania, dobre praktyki, na ile mieści się we wzorcu projektowym i filozofii Django i tak dalej.

**Comment by dzemeuksis** [comment]
Pisząc o testach automatycznych miałem na myśli testy Django odpalane lokalnie. Teraz widzę jednak że niestety testy automatyczne pull requesta wywaliły się z jakiegoś powodu, chyba na dodaniu pola na bazie danych. Tu już tylko Adam może pomóc.

**Comment by dzemeuksis** [comment]
@PiotrIw , to jest zrealizowane, ale tu nie mam mocy zamknąć.

**Comment by PiotrIw** [comment]
jw
