### ISSUE TITLE
Adres @ gminy Cisna

### ISSUE THREAD

**Issue by Roksana90** [watchdogpolska/feder#1162]
Hej,
przy sprawdzaniu problematycznych odp. ze SJJ zauważyłam, że dostaliśmy automatyczny mail o zmianie adresu do korespondencji.
UPRZEJMIE INFORMUJEMY, IŻ Z DNIEM 6 KWIETNIA 2021 R. NASTĄPIŁA ZMIANA ADRESU POCZTY ELEKTRONICZNEJ URZĘDU GMINY CISNA.

WSZELKĄ KORESPONDENCJĘ PROSZĘ KIEROWAĆ NA NOWY ADRES E-MAIL:  [sekretariat@gminacisna.pl](mailto:sekretariat@gminacisna.pl)
https://fedrowanie.siecobywatelska.pl/sprawy/raport-o-stanie-gminy-jak-jest-tworzony-1395

A my mamy w fedrowaniu jeszcze stary: https://fedrowanie.siecobywatelska.pl/instytucje/cisna

Możesz to zmienić? @dzemeuksis

**Comment by dzemeuksis** [comment]
Zmieniłem, dziękuję za cynk. :)

**Comment by Roksana90** [comment]
Dzięki!
