### ISSUE TITLE
Przypomnienie hasła wydaje się nie działać

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1218]
Zarówno ja, jak i inni użytkownicy mają takie doświadczenia, że próba przypomnienia hasła nie powoduje ani jego resetu ani przypomnienia mejlem. Innymi słowy nic zauważalnego się nie zadziewa. Mowa o opcji "Zapomniałeś hasła?" na dole obrazka:
![obraz](https://user-images.githubusercontent.com/33778688/221137377-4b55110d-ed71-4aee-922a-dcf210241417.png)

**Comment by PiotrIw** [comment]
wpisałem trzy maile do przypomnienia hasła:  dwa dla nieistniejącego użytkownika i jeden dla istniejącego, za każdym razem dostałem prawidłowego maila,, dwa z informacją że nie ma użytkownika nz takim mailem i trzeci z linkiem do resetu.
