### ISSUE TITLE
Dodanie do raportu z monitoringu na Fedrowaniu kolumny z linkiem do sprawy

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1221]
Fajnie, jakby dodać do raportu CSV z wyników monitoringu, generowanego tutaj: https://fedrowanie.siecobywatelska.pl/monitoringi/sesje-zdalne-dogrywka/raport (przykład dla monitoringu _Sesji zdalnych - dogrywka_, chodzi o ten sam raport, co w tym zgłoszeniu: #1197) kolumnę z linkiem do sprawy. Chodzi o te linki, co są tam widoczne bezpośrednio na stronie skryte w nazwach instytucji:
![obraz](https://user-images.githubusercontent.com/33778688/230729907-8e5e13ec-751a-4a5c-a6e3-c6f53a0bad1c.png)

**Comment by dzemeuksis** [comment]
To w połączeniu z terytem (który już jest) pozwoli właściwie kilkoma kliknięciami generować mapę monitoringu ze znacznikami na każdej gminie, zawierającymi linki do spraw im właściwych.

**Comment by dzemeuksis** [comment]
Nie mam mocy przypisania chyba, więc summonuję: @PiotrIw

**Comment by PiotrIw** [comment]
"....kilkoma kliknięciami generować mapę monitoringu ze znacznikami na każdej gminie, zawierającymi linki do spraw im właściwych."  - a nie lepiej taką mapę wygenerować na stronie?

**Comment by dzemeuksis** [comment]
Ustaliliśmy, że wystarczy to wystawić na API.
