### ISSUE TITLE
Dodać do admina

### ISSUE THREAD

**Issue by PiotrIw** [watchdogpolska/feder#1286]
- dodać model ReputableLetterEmailTLD? ['aero', 'fm', 'pl', 'eu', 'tv', 'net', 'org', 'info', 'biz', 'com']
- filtr Letter z TLD inne niż ReputableLetterEmailTLD
- filtr LetterEmailDomain z TLD  innych niż ReputableLetterEmailTLD
- akcję dla instytucji "oznacz/odznacz jako archiwalną"

**Comment by PiotrIw** [comment]
zaimplementowane w v1.1.24

**Comment by PiotrIw** [comment]
@dzemeuksis 
dodałem reputowane TLD do admina: https://fedrowanie.siecobywatelska.pl/admin/letters/reputableletteremailtld/
oraz stosowny filtr w adminie domen adresów mailowych:
![image](https://github.com/watchdogpolska/feder/assets/36678620/598203dd-ab6b-46b6-bbcc-06518c43e1ae)

**Comment by dzemeuksis** [comment]
![obraz](https://github.com/watchdogpolska/feder/assets/33778688/945e4a1a-4785-4cb9-8dc6-f0d755aa01ae)
Co robi ten ostatni "Zapisz"?

**Comment by dzemeuksis** [comment]
Jeśli chodzi o nazwę, to może "Wiarygodne domeny"?
