### ISSUE TITLE
Ukryć mejl do sprawy w cytacie

### ISSUE THREAD

**Issue by PiotrIw** [watchdogpolska/feder#1306]
Tu (https://fedrowanie.siecobywatelska.pl/listy/186984) wylazł adres sprawy w cytacie a w zwykłej wiadomości ładnie to maskujemy:

![obraz](https://github.com/watchdogpolska/feder/assets/36678620/97c0c652-4517-49b6-931d-ce5d91043576)
Fajnie byłoby też tutaj.

**Comment by PiotrIw** [comment]
@dzemeuksis - zaimplementowane w v1.1.27

**Comment by dzemeuksis** [comment]
Zerknąłem na ten przypadek i podobne, wygląda ok. Dzięki!
