### ISSUE TITLE
500 na przy próbie przepięcia spraw

### ISSUE THREAD

**Issue by PiotrIw** [watchdogpolska/feder#1307]
MZ: Dostaję po kliknięciu "Aktualizuj" w edycji listu, po tym, jak próbuję go przepiąć do właściwej sprawy, na przykład tutaj: https://fedrowanie.siecobywatelska.pl/listy/186483/~edytuj

![obraz(2)](https://github.com/watchdogpolska/feder/assets/36678620/aa0851ff-5c21-400c-9f6b-91575b85aa21)

**Comment by PiotrIw** [comment]
@dzemeuksis - poprawione w v1.1.27

**Comment by dzemeuksis** [comment]
Przepinanie działa, dziękuję!
