### ISSUE TITLE
utrata formatowania przy ponowieniu

### ISSUE THREAD

**Issue by PiotrIw** [watchdogpolska/feder#1308]
MZ: Drobiazg, ale zauważyłem, że ponowienie emaila przyciskiem w prawym górnym rogu:

![obraz(3)](https://github.com/watchdogpolska/feder/assets/36678620/dd23270b-7ef2-4aed-b473-1d2b0d854cf3)

Powoduje utratę formatowania (na górze widać fragment ponowionego a na dole ponownie wysłany):
![obraz(4)](https://github.com/watchdogpolska/feder/assets/36678620/ba6d6e61-3171-471a-bb5a-f4724d024a22)

**Comment by PiotrIw** [comment]
@dzemeuksis - poprawione w v1.1.27

**Comment by dzemeuksis** [comment]
Jest git!
