### ISSUE TITLE
Błędny komunikat o braku uprawnień w pustych monitoringach (bez spraw)

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1330]
W nowych monitoringach, które nie mają jeszcze spraw, pojawia się mylący komunikat:
![obraz](https://github.com/watchdogpolska/feder/assets/33778688/26a94c04-39c2-4dde-b064-3de97819aaca)
Pojawia się on nawet dla konta superusera, więc raczej sensu nie ma.

**Comment by dzemeuksis** [comment]
Fajnie.

**Comment by PiotrIw** [comment]
fix v1.2.5
