### ISSUE TITLE
Rozróżnianie instytucji przy ręcznym dodawaniu spraw

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1334]
Przy ręcznym tworzeniu spraw (przycisk "Utwórz sprawę" w centrum zrzutu):

![image](https://github.com/watchdogpolska/feder/assets/33778688/08f0fabc-401e-42b9-9fd4-840e556b102c)

ciężko rozróżnić instytucję o tej samej nazwie:

![Screenshot from 2023-09-25 10-19-12](https://github.com/watchdogpolska/feder/assets/33778688/3f2feaaf-e085-4792-8f25-73aed9fdae88)

Między innymi z tego powodu jakiś czas temu zacząłem sukcesywnie modyfikować nazwy instytucji w taki sposób, żeby uniknąć tego typu niejednoznaczności, niechybnie prowadzących do błędów. Konwencja, którą przyjąłem, oznaczałaby, że w przypadku Brzeźnicy do jednej z nich dodałbym w nawiasie "woj. małopolskie" a do drugiej "woj. lubuskie", oczywiście w zgodzie z tym, na co wskazują ich teryty.

Natomiast dzięki zmianom, które zostały wdrożone, w wielu miejscach systemu jest już widoczne województwo i powiat, co sprawia, że to dłubanie przy nazwach staje się zbyteczne. Wprawdzie dla mnie było to całkiem ok. od strony praktycznej, ale jednak z punktu widzenia technicznego chyba niezbyt eleganckie.

Pytanie więc, czy można i tutaj jakoś ujednoznacznić na tej liście instytucje (do rozważenia też inne podobne miejsca, jeśli są).

**Comment by PiotrIw** [comment]
Czy tak będzie lepiej?

![image](https://github.com/watchdogpolska/feder/assets/36678620/0c2ccc42-6d47-49f6-96e8-13bd31ee7283)

**Comment by dzemeuksis** [comment]
Czadowo!

**Comment by PiotrIw** [comment]
zaimplementowane w v1.2.5
