### ISSUE TITLE
Może by tak AND zamiast OR w tagach instytucji?

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1432]
Filtrowanie instytucji po tagach działa (najpewniej z założenia) tak, jakby tam był OR:

Wyszukanie:
![image](https://github.com/watchdogpolska/feder/assets/33778688/de3baaaa-aed6-4311-bb90-a900b8686bbd)
Wynik:
![image](https://github.com/watchdogpolska/feder/assets/33778688/d4084c89-6bef-4a3a-bcd0-2975f2e9319b)
No tylko że i tak nigdy do tej pory mi się nie zdarzyło, żebym filtrując instytucje użył więcej niż jednego tagu.
Być może jednak wkrótce okaże się to przydatne... o ile będzie działało jak AND.

Potrzeba taka pojawiła się wraz z dodaniem do bazy placówek oświatowych. Przykładowo może zajść potrzeba odpytania szkół podstawowych (tag RSPO_Szkoła podstawowa), ale wyłącznie o charakterze specjalnym (RSPO_specjalna). Gdyby tagi instytucji filtrowały z operatorem AND, to byłoby trywialne. Tak jak to działa obecnie, czyli z OR jest to właściwie niemożliwe i nadawanie szczegółowych tagów staje się bez sensu, bo nie mogą być łatwym punktem odniesienia nawet do ręcznego przeklikania (w sensie że w wyszukaniu np. wybieram szkoły podstawowe, ale z wyników zaznaczam tylko specjalne), bo w wynikach tagi się nie pojawiają.

Wnioski o informację w określonej wersji przypisuje się i wysyła zasadniczo do instytucji ściśle określonego rodzaju. Niewiele jest scenariuszy, w których chcielibyśmy wyszukać różne rodzaje instytucji posiłkując się OR-em i do wszystkich nich za jednym zamachem wysłać dokładnie taki sam wniosek. A nawet w takich przypadkach czysto organizacyjnie lepiej jest wysłać osobno.

Zatem jeśli zmiana operatora między tagami instytucji w filtrowaniu instytucji z OR na AND jest łatwa do zrobienia i nie ma co do niej technicznych przeciwwskazań, to tak bym to zmienił. Niech tam będzie AND.

**Comment by dzemeuksis** [comment]
W sumie idealnie by było, jakby tam był jakiś switch między AND a OR. Bo czasem potrzebne takie działanie a czasem to drugie.

**Comment by PiotrIw** [comment]
zaimplementowane v1.3.9

**Comment by dzemeuksis** [comment]
Super!

**Comment by dzemeuksis** [comment]
@PiotrIw, wygląda na to, że to działa na wyświetlaniu wyników, ale kiedy pobieramy je jako CSV, to tam są wyniki "OR", nawet jeśli wyszukiwaliśmy "AND".
