### ISSUE TITLE
Ignorowanie/ukrywanie wybranych typów plików

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1438]
Potrzebny mechanizm pozwalający zdefiniować rozszerzenia/typy(?) plików do zignorowania przy podpinaniu na Fedrowanie odpowiedzi instytucji oraz ukrywania już podpiętych (chyba że prościej będzie ręcznie usuwać uzgodnioną akcją).

**Comment by PiotrIw** [comment]
Zostanie zaimplementowany dostęp do pobierania plików na poziomie uprawnień pojedynczego użytkownika.
