### ISSUE TITLE
Dostępność plików w ukrytym monitoringu

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1439]
Wygląda na to, że dokumenty załączone do wiadomości są dostępne po bezpośrednich linkach dla każdego, nawet jeśli monitoring został ukryty (i pewnie też, jak sprawa została poddana kwarantannie, chociaż tego nie sprawdziłem). Przykład linka do załącznika w ukrytym monitoringu: https://fedrowanie.siecobywatelska.pl/listy/zalacznik/11185/14903

1. Czy można to zmienić tak, żeby niezalogowane osoby nie miały dostępu również do plików ukrytych monitoringów/spraw?
2. Czy można tym wysterować bardziej, tj. żeby nie widziały ich również osoby zalogowane, jeśli nie mają do danego monitoringu stosownych uprawnień?

**Comment by PiotrIw** [comment]
Dodam autentykację dostępu do mediów na NGINX.
Ponadto dodam w https://fedrowanie.siecobywatelska.pl/monitoringi/praworzadnosc-szkol/~uprawnienia-*** definiowanie uprawnieć dostępu do zalącznikow

**Comment by PiotrIw** [comment]
zaimplementowane v1.3.11
