### ISSUE TITLE
Widoczność monitoringów po zalogowaniu

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1440]
Nawet po zalogowaniu użytkownik powinien widzieć tylko publiczne monitoringi oraz te, do których dostał uprawnienia. Teraz widzi, jak się wydaje, wszystkie, nawet na domyślnych uprawnieniach nadawanych automatycznie przy samodzielnym zakładaniu konta.

**Comment by AgnieszkaZdanowicz** [comment]
@dzemeuksis rozmawiałam z Patrykiem i już wiem, o co chodzi. Nowy użytkownik po zalogowaniu rzeczywiście nie widzi monitoringów - ale problem jest taki, że jak jest zalogowany i wpisuje w google jakieś hasło z fedrowania, to dostaje wyniki i może wejść z maila nawet z ukrytego monitoringu

**Comment by dzemeuksis** [comment]
W takim razie zgłoszenie do zamknięcia, bo tę kwestię zaadresowałem innym zgłoszeniem.
