### ISSUE TITLE
Klauzula RODO

### ISSUE THREAD

**Issue by PiotrIw** [watchdogpolska/feder#1444]
Dodać do mediów i strony workaround z serwera.

**Comment by PiotrIw** [comment]
zaimplementowane v1.3.7

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw nie mam pewności, czy mogę sama podmienić klauzulę RODO podlinkowaną na fedrowaniu, bo niby jest coś w tinycontent na ten temat, ale nie wiem, jak tam podmienić - więc wysyłam nową klauzulę tutaj z prośbą o instrukcję, jak mam ją sama podmienić albo o podmiankę :)

[11_KLAUZULA - dane z udip na stronach www i w mediach społ..pdf](https://github.com/watchdogpolska/feder/files/14847662/11_KLAUZULA.-.dane.z.udip.na.stronach.www.i.w.mediach.spol.pdf)

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz podmieniłem klauzulę. Tym razem wymagana była rekonfiguracja NGINX. Kolejne zmiany wystarczy zrobić w adminie. Przy okacji pokażę Ci jak to zrobić.
