### ISSUE TITLE
Domyślne ukrywanie widoczności załączników dla niezalogowanych i nieuprawnionych z zostawieniem maszynowego odczytania

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1452]
Chciałbym rozważyć opcję dorobienia ukrywania widoczności wszystkich załączników dla osób niezalogowanych i nieuprawnionych do danego monitoringu. Przy czym nadal mógłby być widoczny efekt odczytania maszynowego treści załączników, bo tam już chyba wrażliwe informacje z podpisu nie są widoczne, a to właśnie jest problemem (np. podpisane elektronicznie PDFy).

**Comment by PiotrIw** [comment]
Do zaimplementowania: niezalogowany użytkownik nie może pobierać załączników, będzie widział tylko ich treść pod guzikiem "Pokaż cytat"

**Comment by dzemeuksis** [comment]
Jeszcze detal, ale ważny. Tam by trzeba było dodać gdzieś w tooltipie albo nagłówku albo może jeszcze innym miejscu zastrzeżenie o treści coś w rodzaju: "Uwaga: treść załącznika została odczytana maszynowo, więc może zawierać błędy związane  z nieprawidłowym odczytaniem znaków, a także błędną interpretacji układu tekstu na stronie. Jeśli potrzebujesz dostępu do oryginału, skontaktuj się z biurem SOWP."

**Comment by PiotrIw** [comment]
zaimplementowane v1.3.11

**Comment by dzemeuksis** [comment]
@PiotrIw , a to osobne uprawnienie na poziomie monitoringu do ściągania/podglądu oryginałów załączników, to jak się nazywa? Czy to jeszcze będziesz potem dorabiał?

**Comment by PiotrIw** [comment]
@dzemeuksis uprawnienia do do ściągania/podglądu oryginałów załączników mają superuserzy oraz użytkownicy z 
![image](https://github.com/watchdogpolska/feder/assets/36678620/bd115f27-ad17-4833-b037-f874eb8e9996)
:)

**Comment by dzemeuksis** [comment]
> Do zaimplementowania: niezalogowany użytkownik nie może pobierać załączników, będzie widział tylko ich treść pod guzikiem "Pokaż cytat"

Da się ten przycisk inaczej nazwać w odniesieniu do treści załączników? Np. "Treść załącznika"?
