### ISSUE TITLE
Problem z aktualizacją statusów spraw w monitoringach

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1454]
Wrócił problem z aktualizacją statusów spraw w monitoringach, ale nie wiem, czy ma to jakiś związek z #1332 , czy to coś zupełnie nowego. W każdym razie robię nowe zgłoszenie zgodnie z ustaleniami.

**Comment by dzemeuksis** [comment]
Mam podejrzenie, że brakuje konfiguracji dla domeny info.szkolajestnasza.pl i problem dotyczy tylko jej.

**Comment by dzemeuksis** [comment]
Moje podejrzenie okazało się trafne i konfiguracja po stronie Zenbox została uzupełniona. Być może zatem nie ma tu już czego inwestygować.

**Comment by PiotrIw** [comment]
Statusy się przycięły bo maile wychodzą z 'DopaminaLab <[sprawa-64413@info.szkolajestnasza.pl](mailto:sprawa-64413@info.szkolajestnasza.pl)>' a statusy są logowane do maili spraw czyli '[sprawa-64413@info.szkolajestnasza.pl](mailto:sprawa-64413@info.szkolajestnasza.pl)'. To dotyczy wszystkich przypadków gdzie jest ustawiona Organizacja w domenie z której się wysyła....
Poprawiam, i od razu dodam deduplikację logów z emaillabs, bo się ich nazbierało 13,5 miliona co zamula bazę.

Poprawione w v1.3.6
