### ISSUE TITLE
Ukrycie formularza rejestracyjnego

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1498]
Na ten moment po prostu ukryjmy formularz rejestracyjny.

Dodatkowo prośba o wystawienie w panelu administracyjnym możliwości zbiorowego usuwania użytkowników i filtrowania po datach (założenia, ostatniego logowania) i domenie.

**Comment by PiotrIw** [comment]
zaimplementowane v1.3.10
