### ISSUE TITLE
Dodanie możliwości ręcznego ustawienia/zmiany klasyfikacji wiadomości

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1633]
Czasami LLM mylnie klasyfikuje wiadomości zawierające odpowiedzi, jako jakieś inne i w najbliższej perspektywie pewnie trudno będzie tego uniknąć. Potrzebna jest zatem możliwość ręcznej korekty klasyfikacji wiadomości oraz żeby zmiana na A wywoływała normalizację odpowiedzi (jeśli tak się nie da, to jakoś inaczej wywoływane).

**Comment by dzemeuksis** [comment]
@PiotrIw , to chyba już jest, można zamknąć.

**Comment by PiotrIw** [comment]
Zaimplementowane w v1.5.21
