### ISSUE TITLE
Nie zOCRował się PDF z odpowiedzią

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1644]
https://fedrowanie.siecobywatelska.pl/listy/250069

Nie z OCRowała się odpowiedź z PDFa. Jest wprawdzie obrazem, ale stosunkowo czytelna.

**Comment by dzemeuksis** [comment]
Odnotowuję inny przykład, zauważony przez Piotrka: https://fedrowanie.siecobywatelska.pl/listy/259949

Ale właściwie to ma niski priorytet, bo nie jest problemem takie przypadki obsłużyć ręcznie.

**Comment by PiotrIw** [comment]
Naprawione w file-to-text v0.1.09. W fedrowaniu v1.5.20+ można ponownie wystawić zadanie ("Odświerz treść") ocr załącznika.
