### ISSUE TITLE
"Brak odpowiedzi", "Nie dotyczy" i inne optymalizacje etapu normalizacji

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1678]
Etap kategoryzacji, który dzieje się już po etapie normalizacji, operuje na pojedynczym pytaniu, bez kontekstu. Więc jeśli znormalizowana odpowiedź jest nieprecyzyjna, to i na tym etapie też będzie błąd, co obserwuję sprawdzając wyniki "Sesji zdalnych - dogrywki".

I tak, chcąc nieco podkręcić etap normalizacji, zastanawiam się, czy do tego fragmentu prompta normalizującego:
> Jako wynik podaj poprawnie sformatowany json, bez żadnych dodatkowych wyjaśnień.
> Nie zmieniaj kluczy ani wartości pytań. Jeśli w pliku json z pytaniami istnieje już
> wartość odpowiedzi a tekst zawiera również informację dla odpowiedź na pytanie to
> uzupełnij wartość odpowiedzi w pliku json o brakujące informacje.

nie dodać czegoś w stylu:
> Jeśli pytanie nie ma sensu w odniesieniu do odpowiedzi udzielonych na poprzedzające pytania, to wpisz "Nie dotyczy".
> Jeśli odpowiedź miałaby sens w odniesieniu do poprzednich odpowiedzi, ale jej brak, to wpisz "Brak odpowiedzi".
> Jeśli udzielono odpowiedzi na to pytanie, to wpisz odpowiadający temu fragment.
> Jeśli odpowiedź polegała na wybraniu dostępnych opcji i nie jest jasne, które z nich wybrano, to wpisz "Trudno powiedzieć".

Przeklejałem przykładowe prompty z logów w adminie do playgrounda OpenAI i tę zmianę wypracowałem testując na 3.5-turbo-16k, zostawiając domyślną temperaturę (1, bo nie wiem, jak ustawiasz w systemie, więc nie ruszałem, ale swoją drogą z moich doświadczeń w takich zadaniach **lepiej sprawdza się zerowa**).

Efekt: wydaje się działać z proponowaną zmianą znacznie precyzyjniej niż bez niej.

Nie mówiąc o zmianie modelu na 4-turbo, bo wtedy to już odpowiedzi stają się niemalże perfekcyjne (wtedy to nawet bywa odporny na odpowiedzi wielokrotnego wyboru wybrane formatowaniem, którego nie widać i zamiast przeklejać wszystkie opcje pisze często "Brak odpowiedzi"; z drugiej strony poprzedza jsona ciągiem _```json_, czego akurat tutaj pewnie nie oczekujesz), ale to tylko nawiasem tu piszę, bo to inny wątek.

Nie upieram się przy tej zmianie, bo wiadomo, że to bywa przypadkowe i wymaga wielu testów. Zastanawiam się bardziej w kierunku takim, czy by elementów składowych prompta normalizującego (albo i całości) też jakoś nie wystawić do edycji per monitoring (dla superusera tylko), chociażby dlatego, że wniosek może mieć swoją specyfikę, którą można by wówczas uwzględniać na tym etapie.

**Comment by dzemeuksis** [comment]
Może tu podszedłem zbyt szczegółowo, ale jeśli w wyniku tego jest przykładowo "Brak", to potem kategoryzacja nie wie, czy to jest brak odpowiedzi, czy brak tego, czego dotyczy pytanie. Podobnie kategoryzacja widząc tylko jedno pytanie nie wie, że w kontekście poprzednich odpowiedzi tutaj należy rozumieć "Nie dotyczy" zamiast "Brak odpowiedzi". Dlatego jakieś zmiany wydają się tu być potrzebne, ale nie upieram się, że takie, jak zaproponowałem.

**Comment by dzemeuksis** [comment]
Może wystarczy tak:
> Jeśli pytanie nie ma sensu w odniesieniu do odpowiedzi udzielonych na poprzedzające pytania, to wpisz "Nie dotyczy".
> Jeśli odpowiedź miałaby sens, ale jej brak, to wpisz "Brak odpowiedzi"
> Jeśli udzielono odpowiedzi na to pytanie, to wpisz odpowiadający temu fragment.

**Comment by dzemeuksis** [comment]
@PiotrIw , trochę mieszałem w tym zgłoszeniu, ale już jest ustabilizowane. :)

**Comment by dzemeuksis** [comment]
@PiotrIw , do zamknięcia, bo zmiana, którą wdrożyłeś, umożliwia dodawanie tego typu zmian w ramach konfiguracji monitoringu.

**Comment by PiotrIw** [comment]
zaimplementowane w v1.5.11
