### ISSUE TITLE
Wyniki monitoringu z linkiem do sprawy i dokumentu

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1711]
W wynikach monitoringu generowanych z pomocą LLM przydałaby się kolumny z linkiem do sprawy oraz konkretnego dokumentu/wiadomości (w postaci źródłowej) na którym oparto daną odpowiedź. Jeśli to drugie jest trudne, to chociaż ten link do sprawy już bardzo ułatwi weryfikację.

**Comment by dzemeuksis** [comment]
Jak już mowa o polach, które by się przydało dodać, to tagi instytucji byłyby pomocne. Jeśli ten sam wniosek szedłby do różnych typów instytucji, ale analizować chciałoby się osobno, to bez tego ani rusz - trzeba by dzielić na osobne monitoringi.

**Comment by PiotrIw** [comment]
Zaimplementowane v1.5.18
