### ISSUE TITLE
Błąd 500 przy próbie ręcznego wysłania listu

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1806]
Przy próbie ręcznego wysłania listu występuje błąd 500. Chodzi o sytuację, kiedy jak jesteś w jakiejś sprawie i chcesz dodać list, np.:
![image](https://github.com/user-attachments/assets/cb3ce835-5860-4938-bcb7-0754ab8b2031)
![image](https://github.com/user-attachments/assets/e6594385-c16d-473c-8dd0-6ed0cb6980bb)
![image](https://github.com/user-attachments/assets/d0dc2467-1647-4168-9b84-e03782f8a3c7)

**Comment by PiotrIw** [comment]
Poprawione v1.5.21
