### ISSUE TITLE
"Page not found" przy próbie zeskanowania załącznika

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1829]
Użytkowniczki zgłaszają mi, że przy próbie skanowania załączników dostają "Page not found". Próbowałem zawęzić jakoś obszar występowania problemu, ale jest to trudne, bo:
1. Zgłaszają go różne osoby.
2. Czasem ta sama osoba odnotowuje ten problem w jednym monitoringu a w innym nie.
3. Czasem wydaje się pomagać próba rozszerzenia uprawnień globalnych (tych związanych z załącznikami do listu i skanowaniem antywirusowym)...
4. ...ale to bywa nietrwałe.
5. Czasem pomaga nadanie uprawnień na poziomie monitoringu...
6. ...ale to też bywa nietrwałe.

Generalnie problem wydaje się objawiać bardzo niedeterministycznie. Do tej pory wiązałem go z uprawnieniami i w ten sposób próbowałem zaradzać, ponieważ sam, chociaż często coś robię na Fedrowaniu, nigdy nie doświadczyłem tej sytuacji, co łączyłem z posiadaniem uprawnień superużytkownika.

Przykładowego problematycznego linka nie mam na razie, bo jak coś takiego się dzieje, to skanuję taki załącznik, żeby osoby, którego go potrzebują, nie stały w miejscu z robotą. Spróbuję jeszcze to jakoś badać dalej i dopiszę, jak coś odkryję.

**Comment by dzemeuksis** [comment]
Przykład (już nieaktualny):
![image](https://github.com/user-attachments/assets/c7d51a1b-fc72-40b5-84a9-86ece68e1d99)

**Comment by dzemeuksis** [comment]
Znaczy problem jest aktualny, tylko przykład nie, bo to nie może wisieć i czekać - jak dostaję sygnał, że potrzebny jest dostęp do załącznika, to go po prostu skanuję i staje się możliwy do pobrania dla użytkowniczek. Jednak to jest dla nich frustrujące i blokujące pracę, więc coraz bliższy jestem temu, żeby osobom, które potrzebują dostępu do załaczników dać po prostu superusera.

**Comment by dzemeuksis** [comment]
No tylko partnerom, to już na pewno nie mogę dać superusera. A też potrzebują dostępu do załączników.

**Comment by dzemeuksis** [comment]
Albo coś takiego: https://fedrowanie.siecobywatelska.pl/listy/zalacznik/149302/289578
Użytkowniczka Anna_Debon ma wszystkie uprawnienia do tego monitoringu plus kilka globalnych dodanych a i tak po kliknięciu dostaje "Page not found". Załącznik jest zaskanowany, powinna móc go pobrać.

**Comment by dzemeuksis** [comment]
@PiotrIw , próbowałem ten problem obejść przez API, to jest użyć skryptu, który kiedyś sobie napisałem do masowego ściągania załączników z monitoringu i udostepnić je na dysku sieciowym osobom, które potrzebują analizować dany monitoring. Niestety coś się chyba musiało zmienić na API, bo teraz dostaję 404. Efekt jest taki, że nikt poza superuserami nie ma dostępu do załączników a możliwe niegdyś obejście tego problemu przez masowe ściągnięcie załączników przez API też nie działa. Nie wiem, jak tam u Ciebie teraz z czasem i w czym akurat grzebiesz , ale z mojego punktu widzenia ten problem ma najwyższy priorytet. @AgnieszkaZdanowicz , potwierdzasz?

**Comment by AgnieszkaZdanowicz** [comment]
Potwierdzam, to poważny błąd

**Comment by PiotrIw** [comment]
Naprawione w v1.5.23 - już na prudukcji.
Błąd wynikał z innego algorytmu oceny uprawnień dostępu do lstu i załączników do tego listu. Ujawnił się jak załączniki przestały być widoczne dla wszystkich. Teraz jak uzytkownik widzi list to ma uprawnienia do jego załączników.

Do żądania skanowania i pobierania załączników uzytkownik musi mieć urawnienia jn:
![image](https://github.com/user-attachments/assets/2a77e414-4c4d-4456-b56d-fbc83a2788b2)
