### ISSUE TITLE
Utrata możliwości sterowania widocznością monitoringów

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1831]
Z jakiegoś powodu nie mogę zmieniać widoczności monitoringów, kiedyś mogłem. Teraz nie mam dostępu do przestawienia tej flagi. Właściwie na poziomie Django nie mogę zmienić nic w monitoringu. Potrzebuję móc sterować widocznością monitoringów.

**Comment by PiotrIw** [comment]
v1.5.23 (na produkcji) - dodałem to pole do edycji w formularzu monitoringu:

![image](https://github.com/user-attachments/assets/d25422b8-7da9-4f4b-8cf7-4771058aa8b8)
