### ISSUE TITLE
Zsumowanie liczby instytucji i spraw na głównej stronie

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1858]
Na stronie głównej mamy taką tabelę:
![image](https://github.com/user-attachments/assets/5307b01c-cf6c-4baa-86c3-c1e727febdee)
Pytanie, czy można łatwo dodać tam wiersz sumy?

**Comment by AgnieszkaZdanowicz** [comment]
To ja dodam, że fajnie by było, gdyby też tabele z poszczególnych monitoringów miały podsumowania - właśnie wczoraj o tym rozmawiałam z Kasią. Tutaj przykład:

![image](https://github.com/user-attachments/assets/600df29e-1e76-45ff-a913-277ac906a398)

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw właśnie dziś to zauważyłam i już mi się przydało. Wielkie dzięki - mała zmiana, a cieszy ;)
