### ISSUE TITLE
Wystawienie na API oceny LLM listu

### ISSUE THREAD

**Issue by dzemeuksis** [watchdogpolska/feder#1860]
Czy można by wystawić na [API](https://fedrowanie.siecobywatelska.pl/api/records/) ocenę LLM listu? Byłoby to przydatne, ponieważ jest to stosunkowo błędogenne a jednocześnie decydujące o dalszych krokach przetwarzania przez LLM. Gdybym miał to na API, to by mi było łatwiej wytypować sytuacje do poprawy ręcznej. Teraz robię to przechodząc ręcznie po wszystkich sprawach w monitoringach i sprawdzając organoleptycznie każdą wiadomość. No ale tak to się można bawić w monitoringach do powiedzmy 300-400 instytucji, więcej to jest już masakra.

**Comment by PiotrIw** [comment]
Zaimplementowane v1.5.24
