### ISSUE TITLE
Eksport i import ankiety

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#206]
Myślę, że powinien być opracowany import i eksport ankiet do pliku tekstowego.

**Comment by kbiernat** [comment]
O który model chodzi i jaką strukturę tego pliku potrzeba?

**Comment by ad-m** [comment]
@kbiernat , jest to cała aplikacja ``questionaries``. 

Jakbym miał to zaimplementować to pomyślałbym o użyciu [django-rest-framework](http://django-rest-framework.org/), aby eksportować do JSON-a / XML-a (oba wspiera), bo przygotowany serializer może być potem użyty także do wystawienia API REST.

**Comment by AgnieszkaZdanowicz** [comment]
to ankiety, których nie stosujemy, zamykam
