### ISSUE TITLE
Wykrywanie duplikatów e-maili przy imporcie

### ISSUE THREAD

**Issue by kbiernat** [watchdogpolska/feder#224]
Obecnie przy ponownym imporcie danych emaili via getmail, są one ponownie wrzucane do bazy.
Należy zrobić walidację na podstawie Message-ID czy dany mail już istnieje i ignorować

**Comment by ad-m** [comment]
Wprowadzono polecenie ``drop_duplicate_ids``, gdyż zasadniczo e-maile nie powinny docierać wielokrotnie, a jakiś wadliwy program pocztowy może ignorować Message-ID.
