### ISSUE TITLE
Obsługa kilku spraw w polu DO

### ISSUE THREAD

**Issue by kbiernat** [watchdogpolska/feder#226]
Vide mail z 2017-03-01 10:19
W odpowiedzi mamy 2 sprawy.

**Comment by ad-m** [comment]
To wynikało z problemu z wysyłką. Zawieszała się i nie wszystko rejestrowaliśmy co wysłaliśmy, a potem niekiedy wysyłaliśmy dwa razy. Myślę, że systemu nie warto tak komplikować. Dbamy o bazy adresowe, a każda instytucja odpowiada we własnym imieniu.
