### ISSUE TITLE
Zgłaszanie spamu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#283]
Zaczynamy otrzymywać wiadomości spam. Powinno wystarczyć je ukrywać po kilku zgłoszeniach od użytkowników.

**Comment by ad-m** [comment]
Można wprowadzić także automatyczne alertowanie na podstawie frazy w wiadomości, co początkowo powinno wystarczyć. Aby wykrywnie fraz działało dobrze należy uwzględnić, że wiadomości SPAM zawierają niewidoczne znaki kontrolne, które należy usuwać przed wyszukiwaniem frazy.

**Comment by ad-m** [comment]
Częściowo zrealizowane w 3fb4620abb59202b6190cec19e5c3617db109c6c .

**Comment by kbiernat** [comment]
issue co prawda zamknięte, ale generalnie czy nie lepiej iść w stronę odpowiedniej konfiguracji (z autolearningiem) antyspamu na MX?

**Comment by ad-m** [comment]
Nie korzystamy z własnego serwera pocztowego, bo nie wierzę w swoje umiejętności, a korzystamy z usług hostingowym Hekko, gdzie autolearning jest ograniczony. W Hekko wiadomości, które mają status spamu są oznaczone m. in. w nagłówkach.  Jednak dotychczasowe przypadki spamu nie były zbyt skutecznie wykrywane. Jednocześnie dotychczasowe przypadki spamu były schematyczne i ewidentne, więc dostrzegam duży potencjał dla stworzenia bazy słow kluczowych (taki ręczny autolearning). 

Nie bez znaczenia jest także okoliczność, że autolearning nie zwalnia nas z odpowiedzialności za przeglądanie takich wiadomości, więc jeżeli nie jest to absolutnie konieczne wolę nie wprowadzać tu automatyzacji. Warto w tym zakresie przywołać [wyrok WSA w Olsztynie z dnia 10 maja 2016 roku w sprawie sygn. akt. II SAB/Ol 7/16](http://orzeczenia.nsa.gov.pl/doc/206B41AB95):

> Z uwagi na powyższe, do obowiązków organu administracji publicznej należy taka organizacja pracy urzędu, w tym konfiguracja poczty elektronicznej i filtrów antyspamowych, oraz takie zorganizowanie obsługi technicznej poczty elektronicznej organu – aby zapewnić bezproblemowy i niezwłoczny odbiór przesyłanych na ten adres podań, wobec prawnej dopuszczalności ich wnoszenia także drogą elektroniczną (postanowienie NSA z dnia 10 września 2015 r., sygn. akt I OSK 1968/15; postanowienie NSA z dnia 3 listopada 2015 r., sygn. akt I OSK 1940/15, CBOSA). Skutki trudności, błędów czy nieprawidłowości w zakresie kształtowania i obsługiwania przez organy administracji publicznej oficjalnych systemów służących do komunikacji z tymi organami (np. poczty elektronicznej, systemu ePUAP) nie mogą być przerzucane na korzystających z tych systemów (postanowienie NSA z dnia 5 listopada 2015 r., sygn. akt I OZ 1414/15). Tym samym, ryzyko nieodebrania przez organ wysłanego do niego przy użyciu poczty elektronicznej listu, skierowanego na oficjalnie podany adres poczty elektronicznej organu, obciąża organ, a nie wnioskodawcę. Obowiązkiem organu jest bowiem przestrzeganie obowiązujących przepisów prawa (art. 7 Konstytucji RP), a w konsekwencji takie zorganizowanie swojej pracy i zatrudnienia, aby obowiązek ten – także w zakresie przepisów ustawy o dostępie do informacji publicznej – był zrealizowany i każdy z wpływających do organu na oficjalny adres jego poczty elektronicznej listów był odbierany i odczytany. Podanie do powszechnej wiadomości adresu poczty elektronicznej przez organ należy traktować jako jego zobowiązanie, że wiadomości wysłane na ten adres będą odbierane. Jednostka ma prawo działać w zaufaniu do władzy publicznej i oczekiwać, że skoro organ podaje do publicznej wiadomości adres swojej poczty elektronicznej, to będzie odbierał listy skierowane na ten adres, w tym także trafiające do "skrzynki SPAM" (zakwalifikowanie listu jako spam nie oznacza bowiem automatycznie, że podlega on usunięciu). Odmienne zapatrywanie czyniłoby w praktyce prawo do wnioskowania o informację publiczną za pomocą poczty elektronicznej iluzorycznym, którego skuteczność zależna byłaby od arbitralnej woli organu (zob. postanowienie NSA z dnia 18 listopada 2015 r., sygn. akt I OSK 2897/15, CBOSA).

Analogiczne rozumowanie należy wyprowadzić co do komunikacji urząd -> obywatel.
