### ISSUE TITLE
System metryczny

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#284]
Należy wydzielić system statystyk metrycznych z poradnia (zob. [stats](https://github.com/watchdogpolska/poradnia/tree/master/poradnia/stats)), zintegrować z fedrowaniem, a następnie zdefiniować kilka metryk, które pozwolą prezentować sposób rozwoju fedrowania.

**Comment by ad-m** [comment]
@pw-k, hej, masz może ochotę zająć się tym zagadnieniem? Miałeś kontakt z Django? Należy opracować wydzielenie modułu Python, a następnie zainstalować aplikacje w tym repozytorium i skonfigurować metryki.

Istnieje nasza aplikacja Poradnia ( https://poradnia.readthedocs.io/en/latest/ ), która napędza stronę [poradnia.siecobywatelska.pl](https://poradnia.siecobywatelska.pl/). Wprowadziłem w niej system statystyk oparty na cyklicznie generowanych metrykach. Dzięki temu mamy [dane o użyciu serwisu](https://porady.siecobywatelska.pl/statystyki/). Chciałbym podobne statystyki w Fedrowaniu.

Generowanie metryk w ``stats`` oparte jest na cyklicznym wywołaniu funkcji, które są wskazane w [STAT_METRICS](https://github.com/watchdogpolska/poradnia/blob/master/config/settings/common.py#L332). To są proste funkcje, które zwracają tylko liczby, dzięki czemu narzędzie łatwo się rozwija do nowych metryk.

Do zrobienia:
- [ ] utworzyć nowy pakiet,
- [ ] zadbać o obecność manage.py - zob. https://github.com/django-guardian/django-guardian/blob/devel/manage.py
- [ ] skonfigurować testy za pośrednictwem ``test-app`` - zob. https://github.com/django-guardian/django-guardian/tree/devel/guardian/testapp
- [ ] skonfigurować tox w repozytorium - https://github.com/django-guardian/django-guardian/blob/devel/tox.ini 
- [ ] skonfigurować Travisa w repozytorium - https://github.com/django-guardian/django-guardian/blob/devel/.travis.yml

**Comment by ad-m** [comment]
Pomocne https://github.com/kennethreitz/setup.py?utm_campaign=explore-email&utm_medium=email&utm_source=newsletter&utm_term=daily

**Comment by mik-laj** [comment]
Spróbowałem coś wyciągnać: https://github.com/mik-laj/django-metric

**Comment by ad-m** [comment]
@mik-laj , żadnego oznaczenia autorstwa, nie utworzyłeś jako organizacja repozytorium. Zwyczajne piractwo.

**Comment by mik-laj** [comment]
@ad-m. Robiłem to o 7 nad ranem. Nie miałem uprawnień. Czekałem, aż ty założysz repo i przejmiesz moja pracę. Jest repo?

**Comment by mik-laj** [comment]
Całkowicie nie zrozumiałeś moich intencji. Ją próbuje coś zrobić i pomóc w rozwoju aplikacji, a ty wyzywasz od piractwa.

**Comment by ad-m** [comment]
@mik-laj , nie wystąpiłeś o utworzenie repozytorium jako organizacja. Teraz [istnieje](https://github.com/watchdogpolska/django-metric).

**Comment by mik-laj** [comment]
Za chwilę bym musiał wystąpić o Travis i wszystkie pokolei usługi. Wygodniej było pracować z boku.

**Comment by ad-m** [comment]
@mik-laj , wymówki dla piractwa, bo w żaden sposób nie oznaczyłeś autorstwa.

**Comment by mik-laj** [comment]
@ad-m 
````
ERROR: Permission to watchdogpolska/django-metric.git denied to mik-laj.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
````

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m nie wiem, co to - czy to do zamknięcia?

**Comment by ad-m** [comment]
Tak, do zamknięcia. To było wynajdywanie na nowo bazy danych typu "time-series".
