### ISSUE TITLE
Polityka prywatności i regulamin usługi

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#285]
W celu pozyskiwania adresów e-mail od Twittera musimy w serwisie internetowym mieć określone:

- Privacy Policy URL
- Terms of Service URL 

To dokumenty o znaczeniu prawne. Powinny być zatem opracowane przez prawnika. @KatarzynaBatko , kto?

**Comment by mik-laj** [comment]
Na ostatnim spotkaniu w sprawię sądu było mówione, że warto ustalić również zasady wykorzystania danych.

**Comment by AgnieszkaZdanowicz** [comment]
po co nam był adresy od Twittera? Teraz nie zakładamy, że ludzie będą się masowo rejestrować, ale mogą to robić, więc w sumie polityka prywatności i regulamin są aktualne... To muszę do tego usiąść

**Comment by ad-m** [comment]
Może warto uniemożliwić rejestracje i pozostawić rejestracje przez administratora + GSuite (ograniczone do @siecobywatelska.pl)?

**Comment by AgnieszkaZdanowicz** [comment]
No tak mi się wydaje, chociaż nie wiem, czy to nie będzie za duże ograniczenie - bo czasem (bardzo rzadko jak dotąd, ale nie wiem, jakie są plany) udostępniamy fedrowanie do zrobienia wysyłki przez inną organizację. Dotąd akurat zdaje się to dotyczyło tylko naszych członków. Ale może w przyszłości chcielibyśmy poszerzyć ten krąg. Chyba, że na razie moglibyśmy zrobić to, co zaproponowałeś, a na spokojnie zastanowimy się nad przyszłością i wtedy ewentualnie wrócimy do obecnego rozwiązania?

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , rozumiem potrzeby wysyłki przez zewnętrzną organizacje, zatem chciałem pozostawić rejestracje przez administratora (logowanie wówczas przez login i hasło). Możemy wyłączyć dodatkowe mechanizmy w taki sposób, aby móc łatwo do nich w przyszłości wrócić.

**Comment by AgnieszkaZdanowicz** [comment]
ok, to jestem za takimi zmianami - za rejestracją przez administratora

**Comment by dzemeuksis** [comment]
@AgnieszkaZdanowicz , czy tu zostało coś do zrobienia?

**Comment by AgnieszkaZdanowicz** [comment]
nie, zamykam, dzięki :)
