### ISSUE TITLE
Tytuły podstron

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#287]
Wymagają aktualizacji tytuły (```<title>(…)</title>```) większości podstron w serwisie, aby odzwierciedlały podstronę na której użytkownik się znajduje. Coś bliskiego odwróconemu breadcrumbs bez linków może być.  To wymaga więdzy wyłącznie z zakresu HTML-a, a można poobcować z aplikacją. Django-debug-toolbar dokładnie wskazuje, który plik wymaga modyfikacji.

**Comment by jacekll** [comment]
@ad-m Mogę się tym zająć 
1. Zauważyłem, że "główne" podstrony mają title poprawny. Rozumiem, że chodzi o strony np. pojedynczej instytucji, sprawy, monitoringu itp.?

**Comment by ad-m** [comment]
@jacekll , tak, aby było na zakładce było widać czego dotyczy podstrona.
