### ISSUE TITLE
Tłumaczenie etykiet w fedrowaniu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#288]
Należy wprowadzić i18n. Wydaje mi się, że odpowiednie API wprowadziłem w ```django-filter```.
 
![zaznaczenie_0919](https://user-images.githubusercontent.com/3618479/29685745-ae6f9078-8916-11e7-80d8-b5aaefdf191a.png)

**Comment by ad-m** [comment]
Sprawdzić https://django-filter.readthedocs.io/en/develop/ref/filters.html#label

**Comment by jacekll** [comment]
otworzyłem pull request z tłumaczeniami dla django-filters: https://github.com/carltongibson/django-filter/pull/771

**Comment by ad-m** [comment]
Wciąż pole "Nazwa" lepiej, aby było po prostu "Nazwa", a nie "Nazwa zawiera".
