### ISSUE TITLE
API dla udostępniania danych

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#289]
Należy stworzyć API, aby wystawiać wszystkie istotne dane w postaci JSON

**Comment by ad-m** [comment]
Użyć do tego django-rest-framework. Wystarczy read-only w większości przypadków.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m  to aktualne?

**Comment by ad-m** [comment]
Do odczytu jest. Wojtek korzysta.
