### ISSUE TITLE
Eksport w CSV EmailLog 

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#291]
Wprowadziliśmy w ```feder.letters.logs``` statystyki dostarczania wiadomości. Należy wprowadzić zestawienie wszystkich danych z EmailLog dla danego monitoringu, aby można było zrobić statystykę czy coś.

**Comment by jacekll** [comment]
1. czy eksport powinien być autoryzowany? + Jakie uprawnienie?
2. jakie pola (z case, monitoring) powinny być zawarte w CSV?

**Comment by ad-m** [comment]
Generalnie dane w ```EmailLog``` są chronione poprzez ``monitorings.view_log``, więc uprawnienie nie niższe ( https://github.com/watchdogpolska/feder/blob/ae89d4a93ebb2f75025305758e6b988787db04f2/feder/letters/logs/views.py#L20 ). Nie ma także sensu wprowadzać dodatkowego uprawnienia dla samego eksportu.
2/ Myślę, że styknie ```Case.id, Monitoring.id, Case.email,Case.institution.name,Case.institution.id```.

**Comment by ad-m** [comment]
1/ Generalnie dane w ```EmailLog``` są chronione poprzez ``monitorings.view_log``, więc uprawnienie nie niższe ( https://github.com/watchdogpolska/feder/blob/ae89d4a93ebb2f75025305758e6b988787db04f2/feder/letters/logs/views.py#L20 ). Nie ma także sensu wprowadzać dodatkowego uprawnienia dla samego eksportu.
2/ Myślę, że styknie ```Case.id, Monitoring.id, Case.email,Case.institution.name,Case.institution.id``` + ```EmailLog```.
