### ISSUE TITLE
Zbiorcza wysyłka odpowiedzi

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#293]
Mamy logi doręczonych wiadomości. Jeżeli wiadomość nie dojdzie - musimy zaktualizować adres e-mail instytucji. Potem powinniśmy wysyłać wniosek ponownie. Należy wprowadzić odpowiednie mechanizmy wraz z notatką od Stowarzyszenia. Takich przypadków jest <10 na sprawę, więc można to realizować na poziomie konkretnego listu.

**Comment by AgnieszkaZdanowicz** [comment]
Teraz mamy sporo niedoręczonych, ale wychodzi, że to nie adresy email są niepoprawne, tylko wpadamy do spamu etc. Będziemy to wyjaśniać z poszczególnymi gminami przez ePUAP.

@ad-m Nie wiem, jakie mechanizmy tu miałeś na myśli - coś mogłoby się robić automatycznie (wysyłać wiadomość, jak zmieniamy adres email do gminy?)

**Comment by ad-m** [comment]
Mam na myśli jakąkolwiek efektywną metodę ponawiania wniosku, ale wydaje mi się, że po prostu wysyłacie ponaglenie klikając "Odpowiedź". Nie jest to masowe, ale chyba się sprawdza?

**Comment by AgnieszkaZdanowicz** [comment]
Tak, robimy to ręcznie, poprzez "odpowiedź". W aktualnym monitoringu musiałyśmy tak zrobić przy 600 gminach - we trzy dałyśmy radę, ale byłoby idealnie, gdyby system był w stanie wybrać instytucje, które nie odpowiedziały w ramach monitoringu i wysłać im masowo ponaglenie. To jest chyba trochę związane z moją uwagą tutaj #628

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi poklikałam sobie po masowej wysyłce. Ale nie ma sensu, żebym klikała "wyślij", prawda? Czy jak kliknę, to pojawią się te niby wysłane maile na fedrowaniu?

Jeszcze ustaliliśmy w środę, że w treści wysyłanej wiadomości będzie wklejone "Odpowiedź prosimy przesłać na adres {{EMAIL}}", więc to jest do dorobienia. 

A czy możesz mi przypomnieć, co ustaliliśmy w kwestii tego, co wyświetla się w polu "cytat"?

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Po kliknięciu "wyślij" wiadomości powinny się utworzyć, ale nie będą wysłane do odbiorców.

{{EMAIL}} w treści muszę jeszcze dodać.

W polu "cytat" wstawiana jest domyślnie treść wniosku.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi jak dla mnie wszystko wygląda i działa ok. Myślisz, że kiedy uda Ci się wrzucić to na produkcję? Bo już dziewczynom naopowiadałam i wszyscy chcą korzystać :D

**Comment by dzejkobi** [comment]
Jeśli wszystko pójdzie zgodnie z planem, to wrzucę dziś, zrobię finalny test na produkcji i dam znać, czy można korzystać.

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Masowa wysyłka jest już na produkcji. Zrobiłem mały test i wygląda na to, że działa poprawnie.
Na początek proponuję na wszelki wypadek wysłać do małej grupy odbiorców.

Brakuje tylko automatycznego dodawania do treści komunikatu _"Prosimy o odpowiedź na adres {{EMAIL}}."_ Użycie znacznika _{{EMAIL}}_ w treści zadziała, ale trzeba dodać go ręcznie, jak do tej pory. Proponuję założyć na to osobne zadanie, bo powinniśmy to wdrożyć w kilku miejscach (formularz nowego monitoringu, standardowej odpowiedzi i odpowiedzi masowej).

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi Wow, super! To zabieramy się za wysyłkę - spróbujemy na grupie 80 spółek

Założę nowe zadanie zaraz ws. automatycznego dodawania do treści komunikatu "Prosimy o odpowiedź na adres {{EMAIL}}. A to zadanie zamykam - gdyby coś nie działało jednak, to je otworzę.
