### ISSUE TITLE
Wykaz pism, które wymagają zatwierdzenia

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#294]
Mamy mechanizm projektu odpowiedzi, a potem wysyłania (osobne uprawnienie). Należy wprowadzić wykaz listów wymagających zatwierdzenia dla osoby z stosownymi uprawnieniami.

**Comment by jacekll** [comment]
1. Czy dobrze rozumiem, że to powinien być wykaz wszystkich projektów ze wszystkich monitoringów? 

2. Widzę dwie możliwości:
a. osobna w głównym menu (pod "Listy") i osobna strona
b. osobny filtr "projekt" w liście listów (w "Listy")
Którą opcję wybieramy?

**Comment by ad-m** [comment]
Wariant drugi jest ciekawy do wdrożenia, bo takie filtrowanie nie nie zaszkodzi, ale zasadniczo to issues dubluje #300. Mój błąd…

**Comment by AgnieszkaZdanowicz** [comment]
zamykam to, a zostawiam otwarte #300 co prawda nie korzystamy w ogóle z "projektów" - raz chciałyśmy, ale pojawił się problem, że ja zapisałam szkic, Katarzyna wysłała, a system pokazywał, że wysłane przeze mnie - ale może będziemy. Ale może opiszę to w osobnym wątku
