### ISSUE TITLE
Opisy na mapie

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#305]
Przydałoby się na mapie umieścić podpisy pod województwami od razu widoczne, a nie dopiero po załadowaniu. Mapa to plik SVG, więc nie powinno to być trudne w wykonaniu. 

![zaznaczenie_0972](https://user-images.githubusercontent.com/3618479/29896836-dd69d3e4-8dde-11e7-809a-b249a9873719.png)

**Comment by mik-laj** [comment]
Ja ostrzegam, że SVG zachowuje się bardzo dziwnie. 

W innym projekcie wykorzystuje kod 
````js
(function() {
	var svg = d3.select('#svg2');
	var tip = d3.tip()
		.attr('class', 'd3-tip')
		.html(function(d) {
			return d.title;
		});
	svg.call(tip);

	var paths = svg.selectAll('path');
	paths.datum(function(d){ return this.dataset })

	paths.filter(function (d) {return d.title;})
		.on('mouseover', tip.show)
		.on('mouseout', tip.hide)

	paths.filter(function (d) { return d.target; })
		.on('click', function(d) { document.location = d; })

}) ();
````
Do działania potrzebny potrzebne są biblioteki: 
https://cdnjs.cloudflare.com/ajax/libs/d3/4.9.1/d3.js
https://cdnjs.cloudflare.com/ajax/libs/d3-tip/0.7.1/d3-tip.js

**Comment by ad-m** [comment]
"dziwnie" to niezbyt precyzyjny opis.

**Comment by mik-laj** [comment]
Problem z wymiarami jakieś miałem. Nie pamiętam już dokładnie, ale teraz widzę, ze np. ``$($0).height()`` zwraca 0.
