### ISSUE TITLE
Brakuje favicon

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/feder#313]
Szanowni,

Brakuje w projekcie faviconek. Należy takie stworzyć/wygenerować i dodać do projektu

Przydatne: 
https://realfavicongenerator.net/
https://github.com/KlubJagiellonski/pola-backend/blob/ce2d595cbca92e109e16ee5f8a5e38e0c693c2f5/config/urls.py#L51-L69

Z wyrazami szacunku

**Comment by ad-m** [comment]
@jacekll , opracujesz? Mamy logo.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m czy to do zamknięcia?

**Comment by ad-m** [comment]
Nie, wciąż nie mamy favikonek.

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Potrzebuję grafiki, żeby się tym zająć.

**Comment by ad-m** [comment]
@dzejkobi , proszę żądane dane: https://files.jawne.info.pl/private_html/2020_08_leebahzahy4nei3eiTei8Loo2pohF6tooth8zahmee3eiv8zei

**Comment by dzejkobi** [comment]
@ad-m Ok, dzięki. Jak rozumiem, powinienem wykorzystać plik: http://cdn.files.jawne.info.pl/private_html/2020_08_leebahzahy4nei3eiTei8Loo2pohF6tooth8zahmee3eiv8zei/logo-fedrowanie.png

**Comment by ad-m** [comment]
Y

**Comment by ad-m** [comment]
Masz w różnych formatach to logo. Użyj dogodnego formatu z tym logo.

**Comment by dzejkobi** [comment]
Pull request: #809
