### ISSUE TITLE
Odebranie wszystkich uprawnień w monitoringu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#315]
Na https://fedrowanie.siecobywatelska.pl/monitoringi/monitoring-nadlesnictw/~uprawnienia nie ma opcji do usuwania wszystkich uprawnień danemu użytkownikowi.

**Comment by AgnieszkaZdanowicz** [comment]
Z dodawaniem uprawnień jest w ogóle problem #609

**Comment by dzejkobi** [comment]
Widget edycji uprawnień został podmieniony na bazujący na checkboxach. Pull request: #810 .

**Comment by AgnieszkaZdanowicz** [comment]
Tu dziś na spotkaniu z @dzejkobi ustaliliśmy, że na ekranie uprawnień użytkownika przypisanego do monitoringu zostaną dodane 2 przyciski/checkboxy o treści i funkcjonalności "przypisz wszystkie"/"usuń wszystkie"

**Comment by dzejkobi** [comment]
PR: #879

**Comment by dzejkobi** [comment]
Czy możemy zamknąć to zadanie?

**Comment by AgnieszkaZdanowicz** [comment]
tak, zamykam
