### ISSUE TITLE
brak zapytań w zakładce SQL w Django debug toolbar 

### ISSUE THREAD

**Issue by jacekll** [watchdogpolska/feder#321]
![image](https://user-images.githubusercontent.com/1237985/30499623-9559ddcc-9a5b-11e7-8225-0d7f6786960b.png)

**Comment by ad-m** [comment]
See jazzband/django-debug-toolbar#986 . Generalnie nie wiem co powoduje nieprawidłowe działanie tego elementu. Kiedyś to działało bardzo fajnie…
