### ISSUE TITLE
Wykrywanie Git-LFS

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#323]
Wykorzystujemy Git-LFS, a nie oznaczamy tego, przez co testy zawodzą, które wymagają danych z git-lfs i potem jest kłopot. Musimy proaktywnie wykrywać, gdy ktoś nie ma git-lfs i mu nakazać jego instalacje ewentualnie odpowiednie testy skippować do czasu instalacji git-lfs.

**Comment by jacekll** [comment]
Wygląda na to, że warto by także sprawdzić, czy testowe pliki (.eml + inne?) są wycheckoutowane poprawnie. W przypadku doinstalowania git lfs po wycheckoutowaniu repo .emlki zostają jako linki tekstowe.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m nie wiem, czy to aktualne?

**Comment by ad-m** [comment]
Aktualne.

**Comment by dzejkobi** [comment]
To zadanie jest dla mnie trochę kłopotliwe. U mnie lokalnie wszystkie testy przechodzą, więc ciężko mi odtworzyć problem.
Nie wiem, czy jest sens inwestować czas w kompleksowe rozwiązanie, bo skoro testy nie przechodzą, to użytkownik z treści komunikatu powinien być w stanie się domyślić, że brakuje mu git-lfs i sobie go doinstalować. Wartość dodana w tym przypadku jest wg mnie znikoma.

**Comment by ad-m** [comment]
W tym rzecz, że komunikat błędu w żaden sposób nie wskazywał, że problem wypływa z braku Git-LFS. Po prostu konkretne testy nie przechodzą, bo dane testowe (składowane w Git-LFS) były dla niego nieprawidłowe. To powodowało utratę czasu przez deweloperów nieświadomi wymagań. 

Wygląda na to, że zagadnienie zostało rozwiązane w https://github.com/watchdogpolska/feder/blob/f3a064c7aae46effbb3055170c59687102a9c2f5/feder/letters/tests/base.py , a w https://github.com/watchdogpolska/feder/commit/32d8d5aa59c8d7a6e4421c493c804de690d5c7d5#diff-aa96a1d1cc6a11828663724303fe9017 zostało unieważniony.
