### ISSUE TITLE
Oznaczenie projektu listu na widoku wykazu listów

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#325]
![zaznaczenie_1006](https://user-images.githubusercontent.com/3618479/30511787-84e1707e-9ae0-11e7-887c-f596bbfe7210.png)

Na stronie projektów np. https://fedrowanie.siecobywatelska.pl/monitoringi/monitoring-sadow-okregowych/projekty brak jest informacji o tym, że list jest projektem. To może wprowadzać w błąd.

**Comment by jacekll** [comment]
@ad-m @mik-laj Czy jest już jakiś sposób na wizualne oznaczanie szkiców? Jeśli nie, to co myślicie o oznaczeniu np. otwartą kopertą w innym kolorze, z podpisem po najechaniu kursorem, jak na obrazku:
![letter-draft](https://user-images.githubusercontent.com/1237985/30512404-32d63f6c-9aef-11e7-8199-2a9fd5e2fea5.png)
A może ikonka ``file-text`` albo `clipboard` albo `pencil-square` (tą ostatnią można by dodać nie zamiast, a obok zwykłej koperty)?

**Comment by ad-m** [comment]
Obecnie szkice są oznaczane notatką: https://fedrowanie.siecobywatelska.pl/listy/7892 
Podoba mi się jednak pomysł użycia do tego także ikonki. Preferencji nie mam.

**Comment by mik-laj** [comment]
Dodam nowa ikonkę, ale muszę ją najpierw narysować. Będzie koperta z ołówkiem.

**Comment by AgnieszkaZdanowicz** [comment]
komunikat przy szkicach się pojawia, chociaż nie ma (chyba) wyróżniającej ikonki. Moim zdaniem nie ma takiej konieczności, zamykam
