### ISSUE TITLE
Pytanie o datę powinno mieć kalendarz

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#331]
![zaznaczenie_1020](https://user-images.githubusercontent.com/3618479/30725941-5c7f496e-9f48-11e7-898e-8db4d2313f74.png)

W przypadku pytania o datę należy wyświetlać kalendarz, gdzie użytkownik może wybrać sobie datę. Należy wspierać także starsze przeglądarki Obecnie pole jest tekstowe i nawet nie ma poprawnego typu HTML5.

**Comment by AgnieszkaZdanowicz** [comment]
ankieta, zamykam
