### ISSUE TITLE
Nieobowiązkowe pole wyboru

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#336]
![zaznaczenie_1024](https://user-images.githubusercontent.com/3618479/30726306-585a0dc2-9f4a-11e7-954c-095b2cbcc5be.png)

W przypadku pola wyboru nieobowiązkowy charakter jest pozbawiony sensu, gdyż przeglądarki tego nie obsługują, skoro każą wybrać z listy. Należy albo dodawać nową pozycje do listy ("-") w przypadku opcjonalności, albo skasować wybór w ogóle.

**Comment by AgnieszkaZdanowicz** [comment]
ankieta, zamykam
