### ISSUE TITLE
Blokada ujemnej wiarygodności

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#338]
![zaznaczenie_1027](https://user-images.githubusercontent.com/3618479/30726423-02d25336-9f4b-11e7-97ce-0b62fe8e1e74.png)

Należy: 
- [ ] ukrywać przycisk zmniejszenia wiarygodności, gdy ```wiarygodność = 0```,
- [ ] blokować wywołanie akcji zmniejszenia wiarygodności, gdy ```wiarygodność = 0```.

**Comment by AgnieszkaZdanowicz** [comment]
ankieta, zamykam
