### ISSUE TITLE
Tłumaczenie komunikatu o aktualizacji pytania

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#340]
![zaznaczenie_1028](https://user-images.githubusercontent.com/3618479/30726494-6fe22b40-9f4b-11e7-87da-0c16cc3e0b1b.png)

Czy ```django-atom``` jest w ```INSTALLED_APPS```? Może to to?

**Comment by AgnieszkaZdanowicz** [comment]
to ankieta, zamykam
