### ISSUE TITLE
Call to action - przekierowanie do zadania z monitoringu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#343]
Należy wprowadzić duży przycisk wzywający do przetwarzania odpowiedzi. Jumbotron?
![zaznaczenie_1031](https://user-images.githubusercontent.com/3618479/30726685-a4e38298-9f4c-11e7-906c-cfece9d62549.png)

**Comment by AgnieszkaZdanowicz** [comment]
to ankieta, zamykam
