### ISSUE TITLE
Potwierdzenie doręczenia wiadomości

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#385]
>  Mogę także dopisać potwierdzenie doręczenia wiadomości.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m nie wiem, czy chodzi o to, żebyśmy my dostawali potwierdzenia, że nasza wiadomość doszła do urzędu (dostajemy), czy żeby urząd dostawał od nas potwierdzenie (to jest na to osobny issue #299)

**Comment by ad-m** [comment]
Duplikat.
