### ISSUE TITLE
Edycja załączników dla edycji pisma

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#39]

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m nie wiem, co to jest i czy można to zamknąć

**Comment by ad-m** [comment]
Wymaga weryfikacji czy przy edycji pisma możecie edytować w pełni tak jak potrzebujecie. Wydaje mi się, że nie, dlatego anonimizacje ja wykonuje.

**Comment by dzejkobi** [comment]
Z tego, co zrozumiałem, chodzi o edycję wychodzących i przychodzących przesyłek pocztowych dodawanych do sprawy.
Jeśli tak, to przetestowałem i jest możliwość edycji oraz podmiany pliku.
Czy dobrze rozumiem?

**Comment by ad-m** [comment]
@dzejkobi , sprawdzałeś przy załącznikach e-maili? Czy sprawdzałeś, że oryginalny plik nie pozostaje na serwerze?

**Comment by dzejkobi** [comment]
@ad-m Widzę, że jest możliwość usunięcia / podmiany / dodania załącznika w API.
Oryginalny plik zapewne pozostaje na serwerze, ponieważ Django domyślnie ma taką politykę względem plików. Z tego, co się orientuję, jest to podyktowane względami bezpieczeństwa, ponieważ nadal mogą do tego pliku istnieć jakieś referencje.
Jeśli takie jest wymaganie, aby oryginalny plik był usuwany, to można zrobić to w momencie zapisu instancji modelu (tak było we wczesnych wersjach Django) albo asynchronicznie, za pomocą skryptu, który szuka w modelach referencji do istniejących plików i usuwa te, do których takowej referencji nie znalazł. Nie znam projektu na tyle, żeby zdecydować, co będzie w tym przypadku lepsze.

**Comment by ad-m** [comment]
> Jeśli takie jest wymaganie, aby oryginalny plik był usuwany
Jest takie wymaganie prawne.
> można zrobić to w momencie zapisu instancji modelu
Myślę, że to jest wystarczające.

Nie wykorzystujemy tego samego pliku w wielu miejscach.

**Comment by ad-m** [comment]
Przeanalizowanie działanie obecnego stanu aplikacji w zakresie anonimizacja.

Przesłane załączniki wiadomości są przechowywane na dwa sposoby:
* w oryginale wiadomości jako jej załącznik 
* jako załącznik w systemie

Skuteczna anonimizacja wymaga rozpatrzenia wymaga redakcji obu. W przypadku oryginału wiadomości przyjęto, że jest ona niepraktyczna i oryginał będzie usuwany. W przypadku załącznika wprowadzono możliwość usunięcia / nadpisania załącznika.

1/ Dokonano weryfikacji sytuacji, gdy usuwany jest oryginał wiadomości poprzez oznaczenie pola "Wyczyść" przy polu "Plik":
![obraz](https://user-images.githubusercontent.com/3618479/134830999-dc34e8ec-d8ab-4052-9239-8d664844d89a.png)

Zweryfikowano, że po zaznaczeniu "Wyczyść" i zapisaniu zmian plik jest usuwany z aktywnej instancji Fedrowania. Innymi słowy, pierwotny plik nie istnieje dalej na serwerze.

Pole "Plik" jest dostępne od niedawna – zobacz #1086

2/ Dokonano weryfikacji, gdy usuwany jest załącznik poprzez oznaczenie pola "Usuń" przy załączniku:

![obraz](https://user-images.githubusercontent.com/3618479/134832996-e7104cc2-2f6d-4483-9828-635a9de8684b.png)

Zweryfikowano, że po zaznaczeniu "Wyczyść" plik jest usuwane z aktywnej instancji Fedrowania. Innymi słowy, pierwotny plik nie istnieje dalej na serwerze.

3/ Dokonano weryfikacji, gdy załącznik jest nadpisany poprzez nadpisanie załącznika listu:
![obraz](https://user-images.githubusercontent.com/3618479/134832985-e10819d0-e7ff-4820-81a8-1e609b5d7f11.png)

Uwzględniając rezultat scenariusz 1/ , 2/ i 3/ ustalono, że listy mogą być skutecznie anonimizowane, w zakresie treści przekazanych w załącznikach.
