### ISSUE TITLE
Ukrywanie pism

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#392]
Agnieszka Zdanowicz:

> a czy zastanowisz się nad wprowadzeniem takiego uprawnienia "ukryj wiadomość" - żeby było wykorzystywane, kiedy gmina wysłała do nas kilka takich samych odpowiedzi? To by się przydało, bo w niektórych odpowiedziach jest niezły bałagan.

Karol Breguła:

> Wprowadzę mechanizm do "zwijania" wiadomości, aby było mniej widać wiadomości powtórzone, ale - ponieważ ludzie są omylni - wolałbym nie ukrywać całkowicie. Na pierwszy rzut oka podobne wiadomości mogą się różnić, bo np. ktoś dołączy więcej skanów w jednej wiadomości. Takie wiadomości będą widoczne, ale na widoku sprawy trzeba będzie kliknąć w coś dodatkowego, aby zobaczyć, a na widoku monitoringu (te tabelki) nie będzie ich widać wcale.

**Comment by AgnieszkaZdanowicz** [comment]
Wydawało mi się, że to jest załatwione przez opcję "oznacz spam"

![image](https://user-images.githubusercontent.com/36925935/86231560-095e8f00-bb93-11ea-8136-5871278cc591.png)


Ale w dokumentacji znalazłam, że należy oznaczać jako spam tylko realny spam, a nie po prostu powtarzające się wiadomości:

"Wiadomość oznaczona jako spam – ze względów dowodowych i potencjalnego przyszłego wykorzystania np. uczenie maszynowego automatycznego oznaczania podejrzanych wiadomości – nie jest całkowicie z systemu usunięta. Jest ona wyłącznie wycofywana z publikacji. Z tego też względu nie należy wprowadzać niezgodne z stanem faktycznym oznaczenia wiadomości jako spam, gdyż może to w przyszłości zakłócić maszynowe wnioskowanie."

@ad-m dobrze rozumiem, że system do oznaczania spamu nie rozwiązuje problemu opisanego w tym wątku?

**Comment by ad-m** [comment]
Tak, nie rozwiązuje. Oznaczenie jako spam ukrywa, ale jak będziemy tak ukrywać także inne wiadomości to stracimy wiedzę jak wygląda przeciętny spam np. na potrzeby budowania reguł antyspamowych.

**Comment by AgnieszkaZdanowicz** [comment]
to załatwiane w tym wątku #991
