### ISSUE TITLE
Wyświetlać użyty adres e-mail dla pisma

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#4]

**Comment by ad-m** [comment]
See #42

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m to wydaje mi się, że pojawia się w metadanych dla osób zalogowanych? Jeśli to to, to wątek do zamknięcia

**Comment by ad-m** [comment]
Dla osób zalogownaych z odpowiednimi uprawnieniami w monitoringu.
