### ISSUE TITLE
Zaimportować dane na temat liczby mieszkańców

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#402]

**Comment by ad-m** [comment]
https://stat.gov.pl/obszary-tematyczne/ludnosc/ludnosc/powierzchnia-i-ludnosc-w-przekroju-terytorialnym-w-2016-r-,7,13.html

**Comment by AgnieszkaZdanowicz** [comment]
nie jest to pilne, ale aktualne

**Comment by AgnieszkaZdanowicz** [comment]
do opisania

**Comment by dzemeuksis** [comment]
@AgnieszkaZdanowicz , rozwiniesz? Chodzi o to, żeby tylko zaciągnąć takie dane do Fedrowania, czy również gdzieś prezentować? Na frontendzie? W raportach?

**Comment by AgnieszkaZdanowicz** [comment]
@dzemeuksis tego nie mieliśmy przemyślanego. Chodziło o to, żeby móc porównać, czy sposób odpowiedzi zależy od wielkości gminy pod kątem liczby mieszkańców. Ale czy tego nie ma być w Fajnych Danych? Bo tam chodzi o to właśnie, żebyśmy mogli dane pozyskane przez fedrowanie właśnie zestawiać z danymi zewnętrznymi i szukać zależności?

**Comment by dzemeuksis** [comment]
Mnie też brzmi to jak coś, co powinno być realizowane w FD.

**Comment by AgnieszkaZdanowicz** [comment]
to zamykam :)
