### ISSUE TITLE
Uporządkować nazwy gmin

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#403]

**Comment by ad-m** [comment]
Szanowna @AgnieszkaZdanowicz ,

Przesłałem Ci arkusz kalkulacyjny Google, który zawiera 4 arkusze:

- Feder - zawiera aktualne dane z Fedrowania,
- Dostarczone - zawiera dane dostarczone przez Ciebie,
- Nowe - zawiera nowe dane do wprowadzenia do fedrowania (tu należy edytować),
- Ludność - zawiera dane na temat ludności, które weryfikuje na potrzeby #402,
- TERYT - zawiera kopie bazy TERYT (może się przydać), może nie uwzględniać niektórych nowych zmian,

W arkuszu ```Nowe``` są kolumny:
- ```ID FEDER``` - identyfikator w systemie Feder (nie zmieniać!),
- ```Nazwa FEDER```- nazwa w systemie Feder wraz z linkiem (poglądowo),
- ```Nazwa NOWA``` - nazwa nowa (zaktualizować, skopiowałem z fedrowania),
- ```Aktualizacja nazwa?``` - porównanie czy nazwa zmienia się,
- ```REGON NOWY``` - kolumna do wypełnienia numerem REGON urzędu,
- ```Kod TERYT NOWY``` - kod TERYT, który mam wprowadzić do systemu (skopiowałem z fedrowania),
- ```E-mail NOWY``` - adres e-mail, który mam wprowadzić do systemu (skopiowałem z fedrowania)
- ```Aktualizacja e-mail?``` - porównanie czy adres e-mail się zmienia,
- ```Uwaga``` - ewentualne uwagi, wątpliwości, które roboczo będziemy wprowadzać.

**Comment by ad-m** [comment]
Ach, zwracam uwagę także na https://obywatelskie-fedrowanie-danych.readthedocs.io/en/latest/usage/institutions_database.html .

**Comment by AgnieszkaZdanowicz** [comment]
http://administracja.mswia.gov.pl/adm/baza-jst/baza-teleadresowa-jst-d/7788,Baza-teleadresowa-JST-do-pobrania.html

**Comment by AgnieszkaZdanowicz** [comment]
Tutaj wydaje mi się, że chodzi o to, że w fedrowaniu mamy wpisane nazwy miast i gmin np. Warszawa, a powinno być tak: oficjalnie Urząd Miasta Stołecznego Warszawy

@ad-m zgadza się? Wtedy byłoby nam łatwiej rozróżniać gminy, to teraz nazwy się czasem powtarzają i nam się mylą.

Kasia znalazłam zupełnie świeżą bazę - pobrałam ze strony http://administracja.mswia.gov.pl/adm/baza-jst/baza-teleadresowa-jst-d/7788,Baza-teleadresowa-JST-do-pobrania.html

I tutaj są zarówno takie nazwy, jak obecnie są w fedrowaniu, jak i te oficjalne. Czy wystarczyłoby podmienić te nazwy poprzez połączenie baz (z fedrowania i tej ze strony MSWiA) przez TERYT?

**Comment by ad-m** [comment]
Ta baza wygląda jak coś co możemy wykorzystać w naszych porządkach, ale wciąż bym ręcznie zweryfikował skąd mamy rozbieżności względem tej bazy.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m a napiszesz mi, gdzie mam szukać tych rozbieżności? Bo patrzę na ten plik, który mi kiedyś przesłałeś (nazywa się "fedrowanie - gminy") + na Twoją instrukcję powyżej, ale nie wiem, między czym a czym mają być rozbieżności. Bo w arkuszu "nowe" w kolumnie "nazwa nowa" jest wszystko to, co było dotąd w fedrowaniu poza dwoma przypadkami. W fedrowaniu mamy te nazwy gmin, a chcemy je podmienić na nazwy urzędów i wtedy nic nam się nie będzie zgadzało, bo wszystkie nazwy się zmienią. Niestety musisz mi podpowiedzieć, gdzie mam obecnie szukać rozbieżności.

**Comment by AgnieszkaZdanowicz** [comment]
do zastanowienia dla Agnieszki, bo są plusy (większa dokładność określenia) i minusy (odmiana nazw i ich wyszukiwanie) nazw własnych

**Comment by AgnieszkaZdanowicz** [comment]
#1155
