### ISSUE TITLE
Dopisać tooltip z metadanymi na LetterDetailView

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#42]
![zaznaczenie_418](https://cloud.githubusercontent.com/assets/3618479/9562630/74158af4-4e71-11e5-8c87-566c046f1840.png)
http://giodo.gov.pl/1520221/id_art/8813/j/pl/

**Comment by jacekll** [comment]
1. Z metadanych widzę "autor" i "data utworzenia" - czy te wystarczą?
2. ![image](https://user-images.githubusercontent.com/1237985/30117085-80d0043c-931f-11e7-8f05-d7a6ab8b37a7.png)
tak bym mniej więcej widział ikonkę

**Comment by ad-m** [comment]
@jacekll , obecnie "autor", "data utworzenia", "data modyfikacji" (niewidoczne, pochodzi z ```TimestampedModel```, a także #298. Będzie można też powrócić do #4. Po wprowadzeniu tej zmiany będzie prościej także o #301. 
Ikonka - ja zmysłu graficznego nie mam. Myślę, że jest ok.
