### ISSUE TITLE
prośba o wprowadzenie możliwości filtrowania gmin w monitoringach

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#422]
Chodzi o to, żeby po wejściu w dany monitoring gdzieś w okolicach zakładek "Instytucje, sprawy i zadania" i "listy" znalazła się opcja "Sortuj według" i dać możliwość posortowania gmin alfabetycznie - to byłaby opcja : "nazw", ale też trzeba dać możliwość powrotu do domyślnego sortowania, więc drugą opcją byłoby "daty wpłynięcia ostatniej odpowiedzi" (no trochę długa ta nazwa)

**Comment by ad-m** [comment]
Zamiast ""daty wpłynięcia ostatniej odpowiedzi" proponuje "ostatnia zmiana", gdyż możemy oprócz odpowiedzi mieć także np. wiadomość wychodzącą, przesyłkę przychodzącą, przesyłkę wychodzącą.

**Comment by AgnieszkaZdanowicz** [comment]
Trzeba to przemyśleć, bo ludzie mogą nie wiedzieć, co oznacza "ostatnia zmiana"

**Comment by ad-m** [comment]
Ewentualnie "ostatnia aktualizacja sprawy".

**Comment by AgnieszkaZdanowicz** [comment]
to aktualne

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz - na ekranie monitoringu takie sortowanie, ze względu na ilość stron byłoby mało użyteczne
sprawdź prosze czy to co jest w tabeli spraw dla monitoringu (np. https://staging.fedrowanie.siecobywatelska.pl/monitoringi/cyfryzacja-urzedow/monitoring_cases_table ) zaspokaja zgłoszone potrzeby, czy coś jeszcze by sie przydało

**Comment by AgnieszkaZdanowicz** [comment]
Jest super, dzięki!
