### ISSUE TITLE
umożliwienie ściągania wiadomości z fedrowania w formacie *.eml

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#423]
W tej chwili, kiedy chcę pobrać wiadomość z fedrowania, to pobiera się format eml.gz, który nie chce się otworzyć w outlooku

Karol wyjaśnił, że 
Przyczyna: Format *.gz to format skompresowany. Włączyłem kompresje dla e-maili, aby oszczędzić miejsce.

Mam prośbę o wprowadzenie takiego rozwiązania, żeby ściągał się plik *.eml (Karol proponował wprowadzenie automatycznej dekompresji plików *.gz przez przeglądarkę podczas pobierania. Ewentualnie włączenie automatycznego wypakowania przez serwer).

**Comment by ad-m** [comment]
Załatwione przez X-Accel-Redirect i odpowiednie zestrojenie nagłówków. Uprzejmie proszę o weryfikacje @AgnieszkaZdanowicz .

**Comment by AgnieszkaZdanowicz** [comment]
Nie działa mi, chociaż widzę, że tam czeka jakaś aktualizacja do wgrania - to może jeszcze nie jest na serwerze? Pojawia mi się taki komunikat:

![image](https://user-images.githubusercontent.com/36925935/38795910-0406fed0-415a-11e8-9854-142131e014c5.png)

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , naprawione.

@kbiernat , wykorzystałem ```sudo strace -e trace=file -p {{PID_of_nginx_worker}}``` w analizie, gdzie szuka nginx plików. Pełnej przyczyny nie odtworzyłem.

**Comment by ad-m** [comment]
Dodatkowo wprowadzam w Zabbixie monitoring załączników.
