### ISSUE TITLE
zmiana sposobu przewijania spraw z mailami z monitoringu

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#427]
W tej chwili można przeskakiwać tylko o jedną stronę do przodu i do tyłu, a chodziłoby o to, żeby można było przeskoczyć o kilka lub na sam koniec. Jest tak:

![image](https://user-images.githubusercontent.com/36925935/37586415-8c8a566c-2b5c-11e8-9262-bccfc63bea59.png)

A lepiej jakby było tak:

![image](https://user-images.githubusercontent.com/36925935/37586480-c96e5df8-2b5c-11e8-9090-487ecbd94ed6.png)

**Comment by ad-m** [comment]
To jest paginacja Dziś przygotuje.
