### ISSUE TITLE
sposób widzenia załączników do nas wysłanych

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#428]
Nie wiem czemu jest tak, że ja wchodzę w korespondencję z daną gminą w danym monitoringu, to przy mailach widzę załączniki:

![image](https://user-images.githubusercontent.com/36925935/37775670-d1d18a68-2de3-11e8-9787-af1c19084734.png)

A jak już wejdę z konkretną wiadomość, to ich nie ma:

![image](https://user-images.githubusercontent.com/36925935/37775701-ea66de2a-2de3-11e8-931c-cf61c2e5c964.png)

Czy to się da zmienić, żeby po wejściu z konkretną wiadomość też było widać te załączniki?

**Comment by ad-m** [comment]
Tak.
