### ISSUE TITLE
Automatyczne zgłaszanie spamu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#429]
Należy wprowadzić automatyczne zgłaszanie spamu, który otrzymujemy.

W nagłówkach występuje:
```
X-Spam-Checker-Version: SpamAssassin 3.3.2 (2011-06-06) on s50.hekko.net.pl
X-Spam-Flag: YES
X-Spam-Level: *****
X-Spam-Status: Yes, score=6.0 required=5.0 tests=BAYES_00,
```

**Comment by kbiernat** [comment]
Zgłaszanie gdzie? Komu?

**Comment by ad-m** [comment]
@kbiernat , mamy mechanizm zgłaszania do opiekunów monitoringu: https://obywatelskie-fedrowanie-danych.readthedocs.io/en/latest/usage/spam.html
