### ISSUE TITLE
Forma pytania TAK/NIE + komentarz

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#44]
> [K] czy może być pytanie do wyyboru tylko TAK lub NIE. Ewentualne z miejscem na kometarz?
> [A] Jakie sobie wymarzysz takie będzie 
> [K] wymarzam 
> [A]Tak, Nie + komentarz w ramach jednego pytania?
> [K] tak

**Comment by ad-m** [comment]
> tak bo ktoś może mieć problem ze stwerdzeniem tak lub nie, ale chcemy jednak zmuszać do jakiejś odpowiedzi

**Comment by ad-m** [comment]
Szanowna,

Po przeanalizowaniu zgłoszenia szczerze mówiąc mam mocną wątpliwość czy konieczne i po co nam jest dodatkowe pole (w ramach jednego pytania) na komentarz, jeżeli możemy rozdzielić to na na dwa pytania, gdzie drugie będzie służyć za komentarz i będzie nieobowiązkowe. W takim zakresie pytanie "komentarz" jest obecnie wspierane.

Mimo to dodałem taką możliwość, ale jestem za usunięcie, bo to tylko komplikuje system w użytkowaniu.

**Comment by ad-m** [comment]
Dodałem pole TAK/NIE pod postacią listy wielokrotnego wyboru. Bardziej wszechstronne myślę.

![zaznaczenie_432](https://cloud.githubusercontent.com/assets/3618479/9621561/472b5690-5128-11e5-8c75-a598cfa52b9f.png)

**Comment by ad-m** [comment]
Wołam @KatarzynaBatko .

**Comment by AgnieszkaZdanowicz** [comment]
to wprowadzone na sprawdzamyjakjest.pl
