### ISSUE TITLE
Pytanie o datę poproszę

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#45]

**Comment by KatarzynaBatko** [comment]
dodam jeszcze że i tu przyda się miejsce na komentarz.

**Comment by ad-m** [comment]
@mik-laj , zrobione w c20c3bf bez datepickera. Możesz dodać swój wybrany?

**Comment by AgnieszkaZdanowicz** [comment]
to do ankiet, które są na sprawdzamyjakjest.pl
