### ISSUE TITLE
odpowiedzi w fedrowaniu

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#452]
hejka, gdy chcę odpowiedzieć gminie zadającej pytanie o sprecyzowanie wniosku pojawia mi się taki błąd:
Ooops!!! 500
Looks like something went wrong! 
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.
You've encountered an error, oh noes!
If you need assistance, you may reference this error as a5b0a130aa2a4217b76a50beafd65b17.

Pomożecie?

**Comment by ad-m** [comment]
Tak, widziałem te próby. Albo wieczorem albo dziś w biurze rzucę na to
okiem.

pon., 23.07.2018, 08:42 użytkownik KatarzynaBatko <notifications@github.com>
napisał:

**Comment by KatarzynaBatko** [comment]
Dzięki.

**Comment by ad-m** [comment]
https://sentry.jawne.info.pl/watchdogpolska/watchdogpolskafeder/issues/1445/

Problem z kodowaniem. Do rozwiązania wieczorem,  bo wymaga drobna poprawka i wgranie nowej wersji.

**Comment by KatarzynaBatko** [comment]
dziękuję za rozwiązanie problemu z odpowiedziami. choć nie widzę by to było zamknięte, zaczęło działać. Więc sądzę, że działasz. Ale mam inny problem teraz, dam w innym wątku.
