### ISSUE TITLE
załączniki dodawane w fedrowaniu przeze mnie nie działają

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#453]
Po kliknięciu na Pobierz, otrzymuję komunikat: 
404 Not Found
nginx

**Comment by ad-m** [comment]
Możesz podać link do wiadomości? W sprawie https://fedrowanie.siecobywatelska.pl/listy/20780 utworzyłem i działa.

**Comment by KatarzynaBatko** [comment]
Tak, tutaj https://fedrowanie.siecobywatelska.pl/sprawy/monitoring-mediow-samorzadowych-525

**Comment by ad-m** [comment]
Tak, jest błąd. Naprawię niebawem.
