### ISSUE TITLE
dawanie maili do wiadomości 

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#458]
Niektóre gminy odsyłają po informację do innych jednostek. Chciałabym aby wątek tematyczny był utrzymany, w związku z tym piszę do tych jednostek z adresu biuro, ale daję do wiadomości adres z fedrowania dotyczący danej sprawy. Niestety, nie przychodzi ta odpowiedź do tej sprawy. Nic się nie pojawia.

Zastanawia mnie po pierwsze czy tak ma być, a po drugie czy nie jest to jakiś większy problem. Może gminy wysyłają odpowiedzi, a one nie dochodzą? Zaznaczam, że nie ma żadnej zwrotki.

Pozdrawiam,

kasia

**Comment by ad-m** [comment]
Możesz podać dane sprawy?

**Comment by KatarzynaBatko** [comment]
tak: 

sprawa-7705@fedrowanie.siecobywatelska.pl
sprawa-7651@fedrowanie.siecobywatelska.pl
sprawa-7673@fedrowanie.siecobywatelska.pl
7674@fedrowanie.siecobywatelska.pl (tu jest błąd, nie dodałam sprawy)

Mogę jakoś tu dodać zrzuty ekranu?

**Comment by ad-m** [comment]
Możesz dodać tu screenshoty w banalny sposób. Tak jak do Worda.

![zaznaczenie_074](https://user-images.githubusercontent.com/3618479/43994444-2a892462-9d9d-11e8-8a80-f88bc59c91c0.png)

**Comment by KatarzynaBatko** [comment]
<img width="322" alt="wschowa" src="https://user-images.githubusercontent.com/13284861/43994456-655e5fee-9d9d-11e8-9516-506ffc83ac65.PNG">
<img width="785" alt="nowasol" src="https://user-images.githubusercontent.com/13284861/43994457-6c20731c-9d9d-11e8-96e5-49e9a9f04a3d.PNG">
<img width="419" alt="nowasol1" src="https://user-images.githubusercontent.com/13284861/43994459-722070a0-9d9d-11e8-9374-b4d3d6e25c30.PNG">
<img width="375" alt="gubin" src="https://user-images.githubusercontent.com/13284861/43994475-8e61aad6-9d9d-11e8-8064-584f4dbd5a8a.PNG">

**Comment by ad-m** [comment]
Od momentu przeniesienia przychodzącej poczty fedrowania do Zenbox nie wykrywamy poprawnie wiadomości, gdzie występujemy w polu "Kopia", a nie "Do". Wcześniej wykrywaliśmy nawet umieszczenie nas w polu UDW, ale teraz serwer pocztowy nie dołącza tych informacji w sposób dla nas użyteczny. 

Nierozpoznane wiadomości (w tym te) są dostępne na https://fedrowanie.siecobywatelska.pl/listy/wiadomosci/dziennik/?processed=2 do ręcznego przypisania.

**Comment by ad-m** [comment]
Hmm...Podanie Ci tego linku do nieprzetworzonych wiadomości ujawniło pewien słaby punkt fedrowania, bo nieprzetworzone wiadomości są za każdym razem przetwarzane, gdy chodzisz po stronie. Dlatego są takie wolne. To dało impuls do tego, aby opracować inny mechanizm pobierania e-maili ( https://github.com/watchdogpolska/imap-to-webhook ), który będzie wydajniejszy. 

Prawidłowo wykrywać nas w polu "Kopia" będzie działać po wprowadzeniu nowego mechanizmu.
Znalazłem także sposób na ponowne rozpoznawanie wiadomości, nawet jeżeli np. jesteśmy wyłącznie w polu BCC, ale wymaga to zmian w zewnętrznej bibliotece, na co możemy chwilę poczekać ( https://github.com/SpamScope/mail-parser/pull/38 ).
