### ISSUE TITLE
pojedyncza sytuacja

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#461]
hejka, 

W dzienniku pojawia się mega rozformatowana wiadomość z urzędu gminy Stolno, która nie daje się przypisać. Powtarza się wiele razy i utrudnia mi przypisywanie innych wiadomości. Czy dacie ją raz przypisać do sprawy 7233 i wykasować resztę spamu?

**Comment by ad-m** [comment]
Możesz podać link?

**Comment by KatarzynaBatko** [comment]
https://fedrowanie.siecobywatelska.pl/listy/wiadomosci/dziennik/?page=1 tu się powtarza wiele razy

**Comment by KatarzynaBatko** [comment]
hej, mam wrażenie, że pozbyłeś się dwóch przypadków - stolno i kłaj. Cudnie, uławia mi to, ale przydałoby mi się wiedzieć co tam było i dołączyć to do tych spraw.

**Comment by ad-m** [comment]
Nic nie zmieniłem jeszcze.

**Comment by KatarzynaBatko** [comment]
tak, sorki. zmieniłam tę wiadomość, pomyliłam się bo byłam na innej stronie.
