### ISSUE TITLE
Czy możliwe jest dodanie pytań warunkowych?

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#47]
W ewidencji mało pradopodobne jest, że jeśli ktoś udzielił odpowiedzi w terminie to żada opłaty, twierdzi że przetworzona itp. Więc najlepiej, żeby kolejne pytania nie pojawiały sie w przypadku tych instytucji, ktore zrealizowały obowiązek.

**Comment by ad-m** [comment]
@mik-laj , czy złożone byłoby dopisanie takich pytań w JS? Nie musi być żadnego interfejsu dla nich.

**Comment by mik-laj** [comment]
Oczywiście, że nie. Javascript wszystko potrafi. Ja pisze bibliotekę do pytań warunkowych. Kiedyś można by ją wsadzić.

**Comment by mik-laj** [comment]
@ad-m może można wykorzystać w tym celu mechanizm z: https://github.com/watchdogpolska/bliski_publikator ?

**Comment by ad-m** [comment]
@mik-laj, trudno ocenić. To się mocno różni między sobą teraz.
