### ISSUE TITLE
znów pojedyncza sytuacja

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#471]
Zidentyfikowałyśmy z Agą P., że do tej gminy poszło na zły adres, ale w przypadku jednego z wniosków nie mogę poprawić ponieważ nie ma klawisza do ściągnięcia do outlooka. Można jakoś inaczej ustalić na jaki adres oni mają odsyłać? Albo podać mi numer do adresu? https://fedrowanie.siecobywatelska.pl/listy/13305

**Comment by KatarzynaBatko** [comment]
I jeszcze jeden podobny problem https://fedrowanie.siecobywatelska.pl/listy/13091

**Comment by ad-m** [comment]
Dodałem informacje dla osób, które mają odpowiednie uprawnienie, aby zobaczyć adres e-mail sprawy.
