### ISSUE TITLE
pojedynczy problem, ale kolejne razy

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#472]
Kolejne trzy listy, których nie mogę ściągnąć i zobaczyć numeru przy adresie
https://fedrowanie.siecobywatelska.pl/listy/13291
https://fedrowanie.siecobywatelska.pl/listy/13334
https://fedrowanie.siecobywatelska.pl/listy/13397

**Comment by ad-m** [comment]
Nie wiem dlaczego te wiadomości nie mają kopii wiadomości, tak jakby nie były wysłane. W dzienniku także tych wiadomości nie ma. Adres e-mail jest możliwy do ustalenia poprzez metrykę listu obecnie:

![obraz](https://user-images.githubusercontent.com/3618479/54890163-58a21400-4ea8-11e9-9260-0e661420c372.png)

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m na czym polegał tu problem? Te wiadomości miały status "nieznany", ale w kolejnych monitoringach już był "ok". Czy to jest aktualne?

**Comment by ad-m** [comment]
Zagadka co się stało z nimi.
