### ISSUE TITLE
Czy możliwy jest alert przy jakimś pytaniu?

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#48]
np. Czy pojawiają się błędy w anonimizacji danych osób prywatnych? Adam, czy tu można ustawić alert, który idzie na skrzynkę odbierającą korespondencję?

**Comment by ad-m** [comment]
Będzie możliwy.

**Comment by AgnieszkaZdanowicz** [comment]
nie robimy ankiet na fedrowaniu, więc zamykam
