### ISSUE TITLE
Wirtualny serwer FTP

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#505]
Można oprzeć na https://www.npmjs.com/package/ftp-srv#api i logice przesyłek pocztowych.

Pomysł jednego z Nadleśnictw: 
![obraz](https://user-images.githubusercontent.com/3618479/54890039-d6195480-4ea7-11e9-99ed-e13ba5f43c75.png)

**Comment by AgnieszkaZdanowicz** [comment]
to przydatne i aktualne

**Comment by ad-m** [comment]
Jak będzie API odpowiednie po stronie Fedrowania to nie powinno to być tak trudne do napisania. Warunkiem jest API...

**Comment by ad-m** [comment]
@dzejkobi jakbyś do tego podszedł?

**Comment by dzejkobi** [comment]
> @dzejkobi jakbyś do tego podszedł?

Nie wiem, czy dobrze rozumiem wymagania, ale z mojego punktu widzenia serwer FTP nie jest do tego konieczny. Możliwość odbierania załączników przypisanych do konkretnej korespondencji może być realizowana przez samą aplikację Fedrowania. Tzn. W treści wysyłanego maila znajdowałby się unikalny link, który po kliknięciu przenosiłby do odpowiedniego formularza, umożliwiającego upload plików. Po przesłaniu pliki byłyby automatycznie powiązane z odpowiednią korespondencją.
