### ISSUE TITLE
Raven JS API

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#56]
https://docs.getsentry.com/hosted/clients/javascript/
https://docs.getsentry.com/hosted/clients/python/integrations/django/

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m to aktualne?

**Comment by ad-m** [comment]
Aktualne. Do oceny Jakuba zostawiam czy potrzebuje tego.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi się upewni

**Comment by dzemeuksis** [comment]
@PiotrIw , możesz się do tego ustosunkować?

**Comment by PiotrIw** [comment]
Nieaktualne. Sentry zastąpiło Raven nowszymi bibliotekami, specjalizowanymi dla różnych frameworków JS, 
w tym ogólny `@sentry/browser`.
https://ravenjs.com/
