### ISSUE TITLE
nie mogę dodać osoby do monitoringu

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#609]
Próbowałam dodać użytkowniczkę katarzyna.witek@siecobywatelska.pl na fedrowaniu do monitoringu o sądach powszechnych. Wyskoczył mi taki błąd:

![image](https://user-images.githubusercontent.com/36925935/66819448-4a4c4000-ef3f-11e9-8ac3-801398b11955.png)

Czy ja coś źle zrobiłam?

**Comment by ad-m** [comment]
Rozumiem. Usalę przyczynę. Tymczasowo proponuje wykorzystać https://fedrowanie.siecobywatelska.pl/admin/monitorings/monitoring/18/permissions/ .

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , nadałem Ci uprawnienia i ww. link powinien być dla Ciebie dostępny.

**Comment by AgnieszkaZdanowicz** [comment]
aktualne

**Comment by ad-m** [comment]
Jakub, obejściem jest użycie django-admina, ale na to też warto by zerknąć i naprawić trwale.

**Comment by dzejkobi** [comment]
Podejrzewam, że problem pojawił się przy którejś z aktualizacji django-guardian, gdzie zmieniły się parametry przekazywane do metody `PermissionWizard.done()`. Teraz pobieram formularz z `kwargs` i wygląda na to, że błąd już nie występuje. Pull request: @ #810 .

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Wygląda na to, że problem został naprawiony. Czy możemy zamknąć to zadanie?

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi fakt, bo nawet ostatnio dopisałam Kasię i się zdziwiłam, że się udało :) dzięki, to zamykam
