### ISSUE TITLE
zapętlenie odpowiedzi na fedrowaniu - wielokrotne pobieranie tej samej wiadomości

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#623]
Problem był zgłaszany mailowo, ale wydaje mi się, że lepiej, żeby trafił też tutaj. Adam wyjaśniał problem tak:

"Importowanie się zapętliło, bo przesłane wiadomości przenoszę do folderu "SUCCESS", a następnie usuwam z "Odebrane". W momencie, gdy była próba przeniesienia do "SUCCESS" wiadomość nie mogła zostać zostać wykonana to skrzynka była pełna, więc nie była wiadomość usuwana z "Odebrane". W efekcie po chwili była ponowna próba."

A potem Martyna pisała tak:
"Wszystkie odpowiedzi ściągnęły się po raz kolejny i są pod datą 31 października, co mocno zaburza mi pracę nad tym monitoringiem (sprawdzam, kto odpowiedział, kiedy itd.). Szłam po kolei, umieszczając sobie dane exelu, a teraz zrobił się tam groch z kapustą. Czy da się usunąć te dodatkowe odpowiedzi, by została tylko ta właściwa z datą rzeczywistej odpowiedzi?"

Pytanie, jak powyżej - czy da się usunąć te odpowiedzi, które ściągnęły się w wyniku tego zapętlenia?

**Comment by ad-m** [comment]
To nie było tylko zapętlenie, a także moja weryfikacja starych odpowiedzi czy nie występowały pominięcia. Postaram się wykryć, gdyż takie deduplikowanie odpowiedzi realizowaliśmy wcześniej z @kbiernat .

**Comment by AgnieszkaZdanowicz** [comment]
To o tyle ważne dla nas, że sprawdzamy, jak jest, automatycznie pobiera wszystkie odpowiedzi z fedrowania i jakby pobrali po kilka tych samych odpowiedzi i ludziom by się powtarzały, to byłaby wtopa

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , bardzo dziękuje za zwrócenie na to uwagi i pomyślę jak na stałe wprowadzić takie zdeduplikowanie.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m Martyna dopytuje mailowo, a ja spróbuję tutaj - wydaje nam się, że część duplikatów udało Ci się usunąć, ale sporo jeszcze zostało. Ja wczoraj odrobinę ręcznie oznaczyłam jako spam. Czy będziesz jeszcze próbował automatycznie usunąć resztę duplikatów?

**Comment by ad-m** [comment]
Nic nie usuwałem. Nie zdołałem poświęcić na to dostatecznie dużo czasu w piątek. Zamierzam dziś wieczorem to posprzątać.

**Comment by AgnieszkaZdanowicz** [comment]
dzięki!

**Comment by Martyna18** [comment]
Adamie, widzę, że na razie nie udało się sprzątanie fedrowania, jest jakiś problem z tym?

**Comment by ad-m** [comment]
Nie problem techniczny.

Wskazany monitoring odnośnie szpitali posprzątany. Proszę o informacje zwrotną nim posprzątam ewentualnie inne monitoringi.

[duplicate_log.txt](https://github.com/watchdogpolska/feder/files/3847202/duplicate_log.txt)

**Comment by Martyna18** [comment]
teraz rzeczywiście posprzątany, dzięki
