### ISSUE TITLE
raport na temat stanu wniosków

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#628]
Martyna:

> Hej, pisałam o tym wcześniej, ale nie wiem, czy się do tego pytania ustosunkowałeś, nie mogę znaleźć. Chcę ustalić, które szpitale przeczytały wniosek i nie odpowiedziały, które w ogóle nie przeczytały itd. Generalnie muszę ustalić, co oznaczają poszczególne statusy szpitali, które nie odpowiedziały. Czy da się pobrać listę tych szpitali, z informacją, czy przeczytały, czy nie, czy muszę to wszystko ręcznie sprawdzać?

Bartosz:

> Dane z odpowiedzi mam zebrane (na piechotę, ale to od dawna było robione), ale przydałaby się taka tabelka:
> * nazwa gminy (podmiotu)
> * adres e-mail
> * data wysłania wniosku
> * status wniosku
> * data odpowiedzi (korespondencji)
> 
> Bo treść odpowiedzi (powiedzmy - ich analizę) mam, ale taka tabelka z systemu, którą bym skompilował z tym, co mam, pozwoliłaby mi zweryfikować, czy np. czegoś nie pominięto.

**Comment by ad-m** [comment]
W mojej ocenie najskuteczniej potrzebę zaspokoić poprzez odpowiedni raport w ramach BI.siecobywatelska.pl.

**Comment by AgnieszkaZdanowicz** [comment]
Tutaj moim zdaniem najważniejsze jest to, że w tej chwili system nie pozwala nam wyłuskać tych instytucji w ramach monitoringu, które nie zareagowały w ogóle na nasz wniosek. Trzeba je wyłuskiwać ręcznie (przy 2,5 tys. gmin to może być problem) i wysyłać ponaglenia/ponowne wnioski z palca.

Bo co do uwagi Martyny, to możemy już pobierać dzienniki:

![image](https://user-images.githubusercontent.com/36925935/86275834-2f585380-bbd4-11ea-90f3-ee74656077bb.png)

gdzie jest napisane, jaki status ma dany wniosek.

Co do uwagi Bartosza, to jak powyżej, możemy pobrać tabelę - brakuje w niej jedynie informacji o "dacie odpowiedzi"

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi ustaliłyśmy z dziewczynami, jakie dane byśmy chciały w raporcie:

- nazwa instytucji
- adres e-mail instytucji
- gmina
- powiat
- województwo
- data wysłania wniosku
- status wniosku (ok, open, spambounce etc)
- czy przyszła wiadomość od instytucji w ramach sprawy
- czy wniosek przeczytany

Mamy tylko wątpliwość, czy przy punkcie "czy przyszła wiadomość..." system rozróżni potwierdzenie przeczytania wiadomości, wysyłane automatycznie z maila, od wiadomości przesłanej przez kogoś z instytucji? Bo nam chodzi w tym punkcie o tę drugą opcję.

Dodatkowo Marzena napisała tak: _Przydałby się adres instytucji - tabela z adresami umożliwi automatyczne dodanie pinezek do mapy Google z nazwą instytucji i zaznaczeniem informacji np. odpowiedział na wniosek/nie odpowiedział._

My teraz nie mamy wgranych (chyba) adresów do fedrowania, ale adresy do urzędów gmin mamy w bazie pobranej ze strony ministerstwa, więc może można je dograć. Tylko w tej bazie jest kod TERYT, a nie REGON :/ Zastanawiam się też, czy adresy wyświetlać w tym raporcie akurat, bo to już będzie bardzo dużo danych. Czy nie lepiej byłoby zrobić dodatkowo możliwość pobrania raportu do excela i tam dodać adres?

**Comment by ad-m** [comment]
> Mamy tylko wątpliwość, czy przy punkcie "czy przyszła wiadomość..." system rozróżni potwierdzenie przeczytania wiadomości, wysyłane automatycznie z maila, od wiadomości przesłanej przez kogoś z instytucji? Bo nam chodzi w tym punkcie o tę drugą opcję.

To jest wymaganie do postawienia. Dobrze, że zaznaczasz dokładnie jakie informacje potrzebujesz. Do wypracowania jest jak oznaczyć w systemie wiadomości, które są automatycznymi odpowiedziami, ale z pewną dokładnością jest to wykonalne, kwestia wysiłku jaki w to włożymy.

> Przydałby się adres instytucji - tabela z adresami umożliwi automatyczne dodanie pinezek do mapy Google z nazwą instytucji i zaznaczeniem informacji np. odpowiedział na wniosek/nie odpowiedział.

To może pobierzmy te dane z REGON i niech Fedrowanie umożliwi udostępnianie mapy? Wtedy pozostaje tylko jak znaczyć instytucje pod mapę.

Adres nie wpływa na kwestie znaczników, więc proponowałbym go odłożyć i ewentualnie opisać w osobnym zagadnieniu.

**Comment by AgnieszkaZdanowicz** [comment]
Gdyby mogła być mapa uzupełniana przez fedrowanie i na fedrowaniu udostępniana, to byłoby super! To założyć osobny wątek ws. mapy, tak?

**Comment by ad-m** [comment]
Tak.

**Comment by ad-m** [comment]
#939 pokazuje, że przydałaby się informacja o liczbie pism.

**Comment by dzejkobi** [comment]
Uwagi po spotkaniu statusowym:

* raport dostępny tylko dla użytkowników z odpowiednim uprawnieniem
* tabela z wynikami powinna zostać poszerzona na całą dostępną szerokość, a prawy panel przeniesiony ponad tabelę
* dodanie możliwości filtrowania
* określanie odpowiedzi automatycznych na podstawie nagłówków

**Comment by ad-m** [comment]
> określanie odpowiedzi automatycznych na podstawie nagłówków

Określenie odpowiedzi automatycznych na podstawie nagłówków wymaga:
* zapisania tego w bazie danych (do rozważenia kwestia konsolidacji z statusem spamu) 
* oznaczenie w UI automatycznych odpowiedzi
* zarządzanie statusem automatycznego oznaczenia 
* uwzględnienie nowych danych w raporcie

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi dopisuję to, co mówiłam dziś na spotkaniu - mam prośbę, żeby w pliku csv, który pobieramy, był też numer REGON instytucji

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi na jakim etapie jest przygotowywanie raportu na instancji testowej?

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Jest wykonany update na staging i powinien zawierać funkcję wyświetlania raportu, o ile użytkownik ma odpowiednie uprawnienia. Ale baza danych wygląda na bardzo starą. Spróbuję załadować bardziej aktualną.

**Comment by dzejkobi** [comment]
@mrbojko @ad-m Czy mogę prosić o update bazy danych na staging, aby była możliwie zbliżona do produkcyjnej?

**Comment by dzejkobi** [comment]
Na podstawie testów z prawdziwymi danymi można już stwierdzić, że niestety oznaczanie stanu wniosku nie działa prawidłowo. Spróbuję się w to wgryźć i znaleźć przyczynę.

**Comment by AgnieszkaZdanowicz** [comment]
ok, to czekam

**Comment by dzejkobi** [comment]
W kolumnie "otrzymano odpowiedź" powinna już pokazywać się prawidłowa wartość. "potwierdzenie dostarczenia wniosku" jest określane na podstawie nagłówków w momencie, kiedy wiadomość jest przesyłana do Fedrowania, więc będzie się wyświetlać poprawnie tylko dla nowych wiadomości.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi a jak można się zalogować na instancję testową? Bo rozumiem, że nadal tylko tam są dostępne raporty?

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Tak, raporty są na instancji staging, można już filtrować po statusie odpowiedzi, ale nie można jeszcze masowo przypisać spraw do grupy.

Pull request #967 czeka na akcept od @ad-m. Mogę zmergować na produkcję bez akceptu, ale chciałem się upewnić, że nie ma poważniejszych błędów.

Są założone dla Was konta, hasła powinien posiadać @mrbojko . Ja też je dostałem e-mailowo, więc w razie potrzeby mogę podesłać.

Niestety, prawdopodobnie z uwagi na to dodatkowe uwierzytelnianie, nie chce poprawnie działać pobieranie plików CSV. Przypuszczam, że na produkcji ten problem nie wystąpi.

Na staging jest bardzo stara zawartość bazy danych. Próbowałem zaktualizować, ale przy próbie importu danych przez Django, kończy się błędem, trzeba tą operację wykonać bezpośrednio na bazie danych.

**Comment by ad-m** [comment]
@mrbojko , przerzucisz te bazy danych?

**Comment by mrbojko** [comment]
@ad-m ok

**Comment by dzejkobi** [comment]
@mrbojko Wystarczy skopiować całość. Dzięki.

**Comment by mrbojko** [comment]
@dzejkobi zrobione, na moje oko działa.

**Comment by dzejkobi** [comment]
@mrbojko Działa, dziękuję.

@AgnieszkaZdanowicz Można się logować i testować. Jak wspominałem, na staging nie zadziała pobieranie raportu do CSV, a "potwierdzenie dostarczenia wniosku" będzie się poprawnie wyświetlać tylko dla nowych wiadomości, dla pozostałych będzie miało wartość "nie".

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi zalogowałam się. Widzę, że w tabeli w raporcie brakuje jeszcze kolumny "status wniosku" (ok, open, spambounce etc). CSV rzeczywiście nie da się pobrać i w sumie to jest chyba największa bolączka. A w jakiej kolejności są ułożone instytucje w raporcie? Bo najpierw myślałam, że alfabetycznie po województwach, ale np. na samym końcu są warmińsko-mazurskie wymierzane z podkarpackim, więc już sama nie wiem :)

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Ok, kolumnę "status wniosku" trzeba będzie dodać. Kolejność jest w tej chwili domyślna, czyli po numerze sprawy. A jaką kolejność byśmy chcieli? Mogę ustawić np. po nazwie instytucji albo nazwie jednostki administracyjnej, ale żeby była dodatkowo uwzględniona hierarchia, czyli województwo / powiat / gmina, trzeba by skomplikować kwerendę i nie wiem, czy to za bardzo nie wpłynie na wydajność. Możemy też umożliwić wybór sposobu sortowania, ale musimy te sposoby sortowania najpierw określić.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi najlepiej by było ułożyć alfabetycznie z uwzględnioną hierarchią - tak jak napisałeś

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Ok, spróbuję tak zrobić i zobaczymy, czy wydajnościowo też będzie ok. Ma to znaczenie szczególnie przy generowaniu CSV, bo nie ma tam paginacji.

**Comment by AgnieszkaZdanowicz** [comment]
Jednak będę wrzucać tutaj od razu, jak znajdę, że raport w części "otrzymano odpowiedź" nie zgadza się z rzeczywistością (bo teraz nie mogę znaleźć moich poprzednich znalezisk):

1.
https://fedrowanie.siecobywatelska.pl/sprawy/jawnosc-w-spolkach-komunalnych-1228 - tutaj jest tylko potwierdzenie odebrania wiadomości, a w raporcie pokazuje się jako "otrzymano odpowiedź"

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-201 - tutaj Kasia wrzuciła przesyłkę, która przyszła pocztą tradycyjną (poprzez opcję "dodaj przesyłkę pocztową", więc jest odpowiedź. A raport pokazuje, że nie otrzymano odpowiedzi. To samo tutaj: https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-2405 

Więc chyba to jest ten problem, że raport nie uwzględnia przesyłek pocztowych, jako odpowiedź na wniosek, a powinien.

**Comment by ad-m** [comment]
Zawartość zawiera:

```
Reporting-UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Thunderbird/78.7.1
Final-Recipient: rfc822;biuro@likom.biz
Original-Message-ID: <161325720153.64106.4700763427910489390@fedrowanie.siecobywatelska.pl>
Disposition: manual-action/MDN-sent-manually; displayed
```

**Comment by AgnieszkaZdanowicz** [comment]
Kolejną sytuację znalazłam, że urząd odpowiedział, ale w raporcie jest oznaczenie "brak odpowiedzi": Olsztynek

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-2370

![image](https://user-images.githubusercontent.com/36925935/118106902-6abfd300-b3de-11eb-8b66-e706f5f8c708.png)

**Comment by AgnieszkaZdanowicz** [comment]
A tu z kolei jest, że otrzymaliśmy odpowiedź, a dostaliśmy tylko potwierdzenie dotarcia naszego wniosku: https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1138

**Comment by AgnieszkaZdanowicz** [comment]
Tu podobnie, chyba potwierdzenie dostarczenia system uznał za odpowiedź, więc w raporcie jest, że odpowiedziano, a odpowiedzi w rzeczywistości nie dostaliśmy: 

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-180

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1393

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-845

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1093

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1990

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1808

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-2007

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1694

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-2408

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-2168

**Comment by dzejkobi** [comment]
Ok, będę to sprawdzał.

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz 

1. Problem z ignorowaniem ręcznie dodanych przesyłek powinien być już rozwiązany.

2. Status sprawy aktualizuje się, kiedy przychodzi nowy list lub kiedy zostaje dodana przesyłka, stąd część spraw miała nieaktualny status (jeśli zostały utworzone przed dodaniem tej funkcjonalności i od tego czsu nie pojawiła się żadna nowa korespondencja) - zaktualizowałem wszystkie sprawy z konsoli i teraz status powinien być już poprawny oraz aktualizować się na bieżąco.

    Poprawione:
    https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-201
    https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-2405
    https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-2370

3. Zdarza się, że system uznaje potwierdzenie dostarczenia wiadomości za normalną odpowiedź. Te przypadki nadal pozostają nie rozwiązane:

https://fedrowanie.siecobywatelska.pl/sprawy/jawnosc-w-spolkach-komunalnych-1228
https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1138

https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-180
https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1393
https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-845
https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1093
https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1990
https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1808
https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-2007
https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-1694
https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-2408
https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-2168

Prawdopodobnie można uszczelnić wykrywanie wiadomości automatycznych, ale trzeba będzie ten problem dokładniej zbadać, bo w tej chwili korzystam z istniejącego mechanizmu wykrywającego i jak widać nie wszystko wyłapuje.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi dzięki!

Ad1. Wygląda, że już wszystko jest ok, sprawdziłam na jednym z monitoringów

Ad2. Jest ok

Ad3. to nie zamykam tego issue

**Comment by AgnieszkaZdanowicz** [comment]
hej, dorzucam kolejny przykład złego przyporządkowania przez raport odpowiedzi - to znaczy spłynęła odpowiedź (nawet 3 razy), a raport nadal pokazuje, że gmina nie odpowiedziała: https://fedrowanie.siecobywatelska.pl/sprawy/bitwa-o-wozy-strazackie-43

**Comment by dzemeuksis** [comment]
@AgnieszkaZdanowicz , w tym ostatnim przykładzie obecnie raport pokazuje, że gmina odpowiedziała (wprawdzie nadal ma tag "brak odpowiedzi", ale tagi użytkownik przypisuje a nie system).

Tutaj było wiele wątków w tym temacie i chyba większość (jak nie wszystkie) została zrealizowana. Może zamknijmy i ewentualne problemy zgłaszajmy jako nowe tickety?

**Comment by dzemeuksis** [comment]
Chodzi o to, że ze Szczecina tak naprawdę nie ma odpowiedzi w tym przypadku a jedynie potwierdzenie? To faktycznie problematyczne. @PiotrIw , zerkniesz? Porównaj stan faktyczny:
https://fedrowanie.siecobywatelska.pl/sprawy/cyfryzacja-urzedow-2023-pilotaz-42
Z raportowanym na zrzucie wyżej (albo [tutaj](https://fedrowanie.siecobywatelska.pl/monitoringi/cyfryzacja-urzedow-2023-pilotaz/raport?name=szczecin&voivodeship=&county=&community=&application_letter_date_after=&application_letter_date_before=&application_letter_status=&confirmation_received=unknown&response_received=unknown)).

**Comment by AgnieszkaZdanowicz** [comment]
@dzemeuksis dokładnie!

**Comment by PiotrIw** [comment]
@dzemeuksis @AgnieszkaZdanowicz to może dopóki nie znajdziemy metody lepszej klasyfikacji potwierdzenie/odpowiedzi to dodam w którymś miejscu (w sprawie?) możliwość zmiany oznaczenia (potwierdzenie tak/nie, odpowiedź tak/nie) nadanego przez automat? Oczywiście można takie akcje użytkowników logować podobnie jak zrobiłem to na poradni.

**Comment by dzemeuksis** [comment]
Według mnie, to dobry pomysł.

**Comment by PiotrIw** [comment]
możliwość zmiany oznaczenia (potwierdzenie tak/nie, odpowiedź tak/nie) nadanego przez automat zaimplementrowana w v1.1.14

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw nic więcej mi na razie nie przychodzi do głowy, ale wygląda to super i ta tabela to jest coś, o czym nie pomyśleliśmy, a to podsumowywania danych, czy nawet szybkiego spojrzenia na dane ilościowe, na pewno bardzo się przyda!

Co do oznaczania ręcznie, czy odpowiedzieli/potwierdzili odbiór w sytuacji, kiedy system źle zakwalifikuje daną wiadomość, to jestem jak najbardziej za.
