### ISSUE TITLE
nie można pobrać załączonej przesyłki pocztowej - pojedynczy przypadek

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#638]
W tym przypadku nie można pobrać załączonej przesyłki pocztowej:
https://fedrowanie.siecobywatelska.pl/sprawy/zywienie-w-szpitalach-512

Może coś z przesłanymi przez nich pdfami jest coś nie tak? Na razie próbowałyśmy tylko wgrać i Kasia i ja plus ja zmieniałam nazwę pliku. Nie pomaga. Co jeszcze można zrobić?

**Comment by ad-m** [comment]
Problem naprawiony. Z jakiegoś powodu uprawnienia do tych plików na serwerze były nieprawidłowe. Proponuje monitorować, bo mogło to wynikać z pokrycia się z aktualizacjami przeze mnie wprowadzanymi. Jeżeli problem się powtórzymy - spojrzymy na to głębiej.

Wykonano:

- ustalenie ścieżki w bazie danych,
- ustalenie ścieżki w Nginx poprzez error logi Nginx, które wskazały na brak uprawnień,
- zweryfikowanie uprawnień i stwierdzenie różnic w uprawnieniach pomiędzy plikami,
- wykonano ```sudo chmod +r /opt/feder/data/media/*.pdf```
