### ISSUE TITLE
wyświetlanie dat: utworzenia, modyfikacji i odbioru przesyłki pocztowej

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#639]
Nie mogę tego znaleźć w dokumentacji, więc piszę tutaj.

Jak jesteśmy zalogowani i mamy uprawnienia to możemy dodawać przesyłkę pocztową:

![image](https://user-images.githubusercontent.com/36925935/69535300-e70cef00-0f7b-11ea-8aae-8edf75de2510.png)

I tam w formularzu mamy do wpisania datę odbioru. W tej chwili, jak próbuję wgrać datę inną niż dzisiejsza, to wyrzuca błąd i nie dodaje tej przesyłki (a nie zawsze wgrywamy list tego samego dnia, kiedy do nas przyszedł):

![image](https://user-images.githubusercontent.com/36925935/69535973-57684000-0f7d-11ea-89f0-a0464178fb8f.png)

Próbowałam to teraz zrobić w tym wątku i się nie udało: https://fedrowanie.siecobywatelska.pl/sprawy/zywienie-w-szpitalach-453

No ale powiedzmy, że wgrałam przesyłkę pocztową z datą dzisiejszą i wszystko się udało. Potem mogę sobie wejść w ten list, który dodałam i zmienić datę odbioru, bo na to już system pozwala. Tylko, że data odbioru nie jest nigdzie widoczna dla osób bez uprawnień. Widoczne są za to data modyfikacji i data utworzenia:

- po wejściu w list: ![image](https://user-images.githubusercontent.com/36925935/69536266-f725ce00-0f7d-11ea-93d9-b2b6d9364f48.png)

- na stronie monitoringu: 
![image](https://user-images.githubusercontent.com/36925935/69536573-7fa46e80-0f7e-11ea-83cf-33a6537c7364.png)

Czy da się tak zrobić, żeby w przesyłkach pocztowych dodawanych przez nas wyświetlała się data odbioru, a nie data utworzenia?

**Comment by ad-m** [comment]
> Czy da się tak zrobić, żeby w przesyłkach pocztowych dodawanych przez nas wyświetlała się data odbioru, a nie data utworzenia?

To wymaga szerszego spojrzenia, bo powinniśmy sortować po jednym rodzaju dat, bo nie da się przecież różnych rzeczy porównywać. Zatem w tym zakresie należy wziąć pod uwagę także listy. W przypadku listów było oczekiwanie, abyśmy sięgali po daty zawarte w nagłówku wiadomości, które czasem (zwykle z powodu naszych przerw) nie są datami zaimportowania wiadomości. 
Moglibyśmy wprowadzić do przesyłki i do listu datę korespondencji, która:

- w przypadku przesyłki byłaby datą określoną przez Stowarzyszenia jako data odbioru,
- w przypadku poczty elektronicznej byłoby datą wskazaną w nagłówku wiadomości.
Data korespondencji byłaby widoczna w miejscu, gdzie obecnie posługujemy się datą utworzenia listu / przesyłki.

> Tylko, że data odbioru nie jest nigdzie widoczna dla osób bez uprawnień. 

Przeoczenie do szybkiej korekty.

**Comment by AgnieszkaZdanowicz** [comment]
To, co napisałeś, wydaje mi się jak najbardziej logiczne i o to mi właśnie chodziło

**Comment by AgnieszkaZdanowicz** [comment]
Moim zdaniem to aktualne

**Comment by ad-m** [comment]
Tak, aktualne.

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.15
na liście sprawy widać daty otrzymania lub wysłania, podobnie w szczegółach, tworzeniu i edycji przesyłek
dodane logowanie akcji użytkownika na przesyłkach w logu admina

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz  - przyjrzałem się również ostatnim datom maili i tam różnice są w minutach pomiędzy tym co na zenboksie i w fedrowaniu, więc stwierdziłem że nieistotne i zostawiłem jak jest.
