### ISSUE TITLE
skanowanie antywirusowe - blokada skanowania i domyślne skanowanie

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#661]
@AgnieszkaZdanowicz rozmawialiśmy na temat ograniczenia możliwości pobrania załączników, które nie zostały przeskanowane. Uzasadniłem, że nie będziemy domyślnie skanować ze względów na limity (100 plików na dzień). 

Spojrzałem jednak w dane: https://bi.siecobywatelska.pl/question/29 

Niezwykle rzadko mamy 100 załączników dziennie, głównie po usunięciu przeze mnie zatoru. To oznacza, że możemy przyjąć, że codziennie sami wyślemy do skanowania wieczorem 80 plików. W efekcie wszystkie pliki będą przeskanowane i gotowe do pobrania. Jeżeli nie zdołamy jakiegoś pliku przeskanować danego dnia to kiedyś w końcu zostanie on przeskanowany.

**Comment by ad-m** [comment]
Mamy 25,685 załączników, więc przy 80 dziennie zajmie nam to tylko 321 dni. Do tego będziemy musieli przetwarzać bieżące. Na https://bi.siecobywatelska.pl/question/30 widzimy postęp dla każdego z monitoringu.

**Comment by AgnieszkaZdanowicz** [comment]
To znaczy, że one się będą automatycznie jakoś po kolei skanować?

**Comment by ad-m** [comment]
Tak, ale musimy pierw nadrobić zaległości, co nam zajmie sporo czasu.

pon., 16.12.2019, 13:18 użytkownik AgnieszkaZdanowicz <
notifications@github.com> napisał:

**Comment by ad-m** [comment]
Wprowadzono.
