### ISSUE TITLE
gmina zgłasza, że dostała 2 wnioski

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#685]
@ad-m gmina Mściwojów zadzwoniła i powiedziała, że dostała 2 wnioski ws. raportu o stanie gminy. Z maila sprawa-17865@fedrowanie.siecobywatelska.pl oraz sprawa-17721@fedrowanie.siecobywatelska.pl Ja przy tej gminie znalazłam ten pierwszy adres. Nie wiem, jak namierzyć, na jaki adres poszedł mail z tego drugiego adresu. Czy ja mogę to jakoś sprawdzić czy Ty tylko możesz?

**Comment by ad-m** [comment]
Możesz. Wystarczy pobrać oryginał wiadomości.

**Comment by KatarzynaBatko** [comment]
Znowxwywala się system i wysyła A raporcie błąd. Niech wyślą na ten, który
widzisz

pon., 3 lut 2020, 10:44 użytkownik Adam Dobrawy <notifications@github.com>
napisał:

**Comment by ad-m** [comment]
Nie mam śladów po sprawie ```17721```.

**Comment by AgnieszkaZdanowicz** [comment]
ok, to im napisałam, żeby odpisali na ten 17856
