### ISSUE TITLE
Produkcyjna konteneryzacja aplikacji

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#733]
Obecnie aplikacja jest przystosowana do pracy w środowisku deweloperskim w kontenerach. Nie jest to jednak poprawne rozwiązanie dla potrzeb wykorzystania kontenerów w środowisku produkcyjnym. Wymagane jest zachowanie wygodnego wdrażania lokalnego.

Dostrzegalne zmiany:

- przechowywanie kodu aplikacji w obrazie, zamiast podmontowania z hosta,
- wdrożenie pushowania na quay.io
- budowanie front-endu podczas budowania aplikacji
- obsługa workera

Uwagi obecnie na temat produkcji:
- aplikacja działa na hoście w virtualenv (playbooki https://github.com/watchdogpolska/infra/tree/master/ansible/roles/watchdogpolska.django.deploy , https://github.com/watchdogpolska/infra/tree/master/ansible/roles/watchdogpolska.django.setup )
- serwer aplikacyjny to gunicorn,
- serwer bazodanowy jest na osobnym hoście (współdzielony dla wielu aplikacji - docelowo http://www.hyperone.com/services/storage/database/ ),
- serwer pocztowy to lokalny na hoście postfix, który działa jako smart-host, który wysyła wiadomości wiadomości do e-maillabs (lokalny bufor),
- przed hostem z serwerem aplikacyjnym jest HAProxy, który dodaje m. in. CSP i terminuje SSL  
- serwer Elasticsearch i Apache Tika jest na osobnym hoście w kontenerze aktualnie
- wsparcie dla xsendfile lub alternatywnych technologii pomijania serwowania plików przez Python, chyba że syscall ```snedfile``` problem rozwiązuje
- współpraca z imap-to-webhook ( github.com/watchdogpolska/imap-to-webhook ), zwłaszcza rozmiar żądania
- wsparcie dla zadań cron ( https://github.com/watchdogpolska/infra/blob/master/ansible/vars/instance/feder/vars.yml#L32-L75 ), albo wprowadzenia rozsądnego schedulera jako daemona,

Mile widziane:
- aktualizacja dokumentacji na temat wdrażania aplikacji,
- jeżeli to ułatwi, możemy pierw pomyśleć o zmianie storage na wykorzystaniu storage obiektowego (lokalny Minio, docelowo usługa HyperOne), ale ktoś to będzie musiał zaimplementować

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m to aktualne?

**Comment by ad-m** [comment]
Tak, produkcyjnie nie korzystamy z kontenerów.

**Comment by dzemeuksis** [comment]
@PiotrIw , coś chyba zmieniałeś tutaj, ale to w tym kierunku, czy w innym?

**Comment by PiotrIw** [comment]
Zaimplementowane
