### ISSUE TITLE
jak przepiąć list do innej sprawy?

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#737]
@ad-m może to nie na github, ale niech będzie w temacie. Wydaje mi się, że jest opcja przepięcia listu z jednej sprawy do innej, ale trzeba znać dokładną "ścieżkę":

![image](https://user-images.githubusercontent.com/36925935/81302787-196a5e80-907b-11ea-87f7-c2c93468922b.png)

A ja nie wiem, skąd ją wziąć - ściągnęłam sobie dziennik, ale tamte numery mi nie pasują.

A chciałabym tę odpowiedź: https://fedrowanie.siecobywatelska.pl/listy/79062 przenieść tu: https://fedrowanie.siecobywatelska.pl/sprawy/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow-2136

**Comment by AgnieszkaZdanowicz** [comment]
I czy jakkolwiek mogę sprawdzić, z jakiego adresu gmina odpisała?

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m sorry, ale pytanie o przepinanie listów jest dosyć pilne. A w dokumentacji nie mogę znaleźć odpowiedzi

**Comment by ad-m** [comment]
Nie obsługiwaliśmy tego wcześniej. Szczerze mówiąc z zaskoczyło mnie, że jest to dostępne. W weekend usiądę.

**Comment by AgnieszkaZdanowicz** [comment]
Aha... My możemy to obejść - Kasia W. zaproponowała, że pobierze te odpowiedzi, które są w niewłaściwych wątkach (nasz błąd - źle wpisywaliśmy adresy email w kilku gminach, których nazwy się pokrywały) i wgra jako przesyłkę tam, gdzie trzeba. Więc może skoro to kilka przypadków, to nie ma sensu, żebyś nad tym siedział?

**Comment by ad-m** [comment]
Jeszcze nie wiem jaka jest tego złożoność.

**Comment by AgnieszkaZdanowicz** [comment]
Już się nauczyłam, więc zamykam
