### ISSUE TITLE
Twój e-mail wymaga weryfikacji

### ISSUE THREAD

**Issue by Roksana90** [watchdogpolska/feder#738]
Gmina wysyła takie żądanie:
Twój e-mail wymaga weryfikacjiverify"
https://fedrowanie.siecobywatelska.pl/sprawy/mieszkancy-i-radni-wobec-raportu-o-stanie-gmi-1143  
Czy uda się ustawić automatyczne klikanie w odpowiedzi?

**Comment by ad-m** [comment]
Czy możesz mi zebrać więcej przypadków? Musimy w jakiś sprytny sposób zidentyfikować takie wiadomości, bo nie chcemy klikać w wszystkie linki, a tylko te, które są potwierdzeniem. Komputer języka polskiego nie rozumie, więc prawdpodobnie będę musiał się opierać na frazach.

**Comment by Roksana90** [comment]
Ja się natknęłam na ten problem tylko w tej jednej gminie. Więcej przypadków nie znam, ale ja mało działam z Fedrowaniem.

**Comment by AgnieszkaZdanowicz** [comment]
Ja działam dużo ostatnio na fedrowaniu i też tylko ten jeden przypadek kojarzę, więc chyba musimy zdać się na swoją czujność?

**Comment by ad-m** [comment]
Moglibyśmy zacząć od automatycznego alertowania. Może nawet na podstawie bazy fraz / wyrażeń regularnych. To nie powinno być trudne, a pozwoli nam uniknąć przeoczenia. Dobre dla Jakuba dość wcześnie.

**Comment by AgnieszkaZdanowicz** [comment]
to nam się nie zdarza już - może zamknąć ten issue?

**Comment by Roksana90** [comment]
To zamykam. :)
