### ISSUE TITLE
server error - strona obecnie 6 monitoringu gmin ws. danych wyborców

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#748]
@ad-m strona 6 zwraca błąd 

![image](https://user-images.githubusercontent.com/36925935/83501240-259ddc00-a4c0-11ea-8bee-01b3d091ea77.png)

Problem chyba bierze się stąd, że Martyna wykasowała wysłaną przez siebie wiadomość i ta wiadomość była w teczce, która aktualnie znajduje się na stronie 6.

**Comment by AgnieszkaZdanowicz** [comment]
To jest dla nas najpilniejszy błąd do rozwiązania w tej chwili, bo on występuje regularnie

**Comment by AgnieszkaZdanowicz** [comment]
Błąd się pojawia (chyba) zawsze, jak skasuje się jakąś wiadomość. Teraz sprawdzałam, jak działają szkice w "przykładowy monitoring". Zapisałam szkic, a potem go skasowałam. Dzięki czemu uzyskałam niezamierzenie taki efekt:

![image](https://user-images.githubusercontent.com/36925935/86279928-26b74b80-bbdb-11ea-9c24-935e950de262.png)

Czyli jak jestem na stronie głównej i wybieram z paska na górze "szukaj" -> "minitoringi" i chcę wejść w "przykładowy monitoring", to mi wywala ten ekran, co powyżej. W tym przykładowym monitoringu jest mało teczek/spraw i one wszystkie mieszczą się tylko na jednej stronie. I ta jedna strona jest wywalona teraz, dlatego w ogóle nie można wejść do monitoringu.

W innych monitoringach jest tak, że skasowaliśmy list z teczki/sprawy, która jest np. na stronie 6 i nie można wejść na stronę 6 w ogóle. Np. w monitoringu "Czy urzędy gmin przekazują bez podstawy prawnej listy wyborców?" nie można wejść obecnie na stronę 21: https://fedrowanie.siecobywatelska.pl/monitoringi/czy-urzedy-gmin-przekazuja-bez-podstawy-prawnej-listy-wyborcow/strona-21

**Comment by ad-m** [comment]
Więcej analizy w https://github.com/watchdogpolska/feder/issues/619 .

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , czy problem wciąż występuje?

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m wygląda na to, że nie. To zamykam
