### ISSUE TITLE
czy możesz mi wygenerować bazę maili do gmin z fedrowania z podziałem na województwa?

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#762]
> Potrzebuje nazwę gminy, województwo i adres e-mail
– @AgnieszkaZdanowicz

**Comment by dzejkobi** [comment]
Moja propozycja rozwiązania znajduje się w PR #800.
Po mergu pobranie instytucji byłoby możliwe w ten sposób: https://fedrowanie.siecobywatelska.pl/api/institutions/?tags=7&page_size=10000&format=csv
Czas odpowiedzi przy takim zbiorze danych jest długi, ponieważ określanie województwa jest kosztowne.

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz To zadanie zostało już zmergowane, więc bazę maili gmin można pobrać przez link: https://fedrowanie.siecobywatelska.pl/api/institutions/?tags=7&page_size=10000&format=csv

Jeśli wszystko ok, to proponuję zamknąć to zadanie.

**Comment by ad-m** [comment]
Dla mnie można zamknąć, ale powinniśmy utworzyć nowe zagadnienie na przycisk / wzmiankę w dokumentacji jak się dostać do takiego linku.

**Comment by AgnieszkaZdanowicz** [comment]
zgadzam się z Adamem, bo ja nie mam pojęcia, jak mam pobrać bazę instytucji. A link, który mi podałeś, pobrał mi jakiś plik, ale bez żadnego rozszerzenia, więc nie wiem, co mam z nim zrobić. Na razie proszę o wyjaśnienie, o co chodzi z linkiem, w tym wątku, a potem zrobię nowy wątek ws. przycisku do pobierania z narzędzia

**Comment by dzejkobi** [comment]
Ok, trzeba będzie napisać do tego dokumentację. Plik jest w formacie CSV, ale rzeczywiście nie ma nazwy i rozszerzenia, spróbuję stworzyć poprawkę, która nada plikowi wynikowemu odpowiednią nazwę, a póki co, można zmienić nazwę ręcznie, np. na `dane.csv`, po czym powinno się dać go otworzyć w Excelu, czy innym arkuszu kalkulacyjnym.

**Comment by ad-m** [comment]
Może łatwiej niż pisać dokumentacje jest dodać adekwatny przycisk gdzieś w UI?

**Comment by AgnieszkaZdanowicz** [comment]
teraz jasne, nie wiedziałam, jakie rozszerzenie dodać. @dzejkobi to czy mam założyć nowe issue w sprawie tego przycisku czy tutaj kontynuujemy?

**Comment by AgnieszkaZdanowicz** [comment]
To przycisk tutaj najlepiej wrzucić: https://fedrowanie.siecobywatelska.pl/instytucje/

**Comment by dzejkobi** [comment]
Do zrobienia pozostało:
- przycisk do eksportu - przekierowujący na odpowiedni URL w API
- nadanie plikowi wynikowemu nazwy oraz rozszerzenia CSV
