### ISSUE TITLE
pobieranie przesyłki pocztowej niemożliwe - w konkretnej sprawie

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#776]
Na fedrowaniu są wyświetlane wiadomości mailowe od urzędów, które piszą na adres sprawa-XXX@fedrowanie.siecobywatelska.pl, ale czasem urzędy zamiast mailowo wysyłają nam odpowiedź na wniosek pocztą tradycyjną. Wtedy możemy na fedrowanie dodać "przesyłkę pocztową":

![image](https://user-images.githubusercontent.com/36925935/86229357-e1b9f780-bb8f-11ea-9ca2-5187b28e3d4c.png)

Niestety w tej sprawie nie mogę pobrać tak dodanego załącznika: https://fedrowanie.siecobywatelska.pl/przesylki/incoming-121

Ale już w tej mogę: https://fedrowanie.siecobywatelska.pl/przesylki/incoming-101 i w kolejnej też.

Więc w tej, co jest błąd, to musiałyśmy my coś źle zrobić - chciałabym wiedzieć, żeby na przyszłość uniknąć takich błędów.

**Comment by dzejkobi** [comment]
Poprawione, proszę o przetestowanie.

**Comment by AgnieszkaZdanowicz** [comment]
jest ok, dzięki!
