### ISSUE TITLE
importowanie instytucji - RIO

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#801]

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi czy będziesz się zajmował tym tematem niebawem? Bo mam kolejną bazę do wgrania (tym razem dotyczy Samorządowych Kolegiów Odwoławczych): https://docs.google.com/spreadsheets/d/1iG8CkBGC2gyy8p8MoGs7l7hJC3AXO_x60wFT2DzS_Qw/edit?usp=sharing

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Udało mi się uruchomić import i importować bazę lokalnie. Jeszcze tylko chciałbym potwierdzić, że wszystko jest ok, zanim wrzucę na produkcję.

@ad-m Mam w związku z tym zadaniem dwa pytania.
- czy mogę dostać GUSREGON_API_KEY? Bo na razie udało mi się uruchomić tylko w trybie GUSREGON_SANDBOX.
- jaka powinna być nazwa tagu dla tej bazy, czy preferujemy skrót, pełną nazwę, liczbę mnogą czy pojedynczą? Widzę, że nie ma określonego standardu w obecnej bazie. Na razie ustawiłem "Samorządowe Kolegium Odwoławcze"

**Comment by ad-m** [comment]
> czy mogę dostać GUSREGON_API_KEY?

Naturalnie, prześlę Ci dziś bezpiecznym kanałem.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi super wiadomość, dzięki!

**Comment by dzejkobi** [comment]
> > czy mogę dostać GUSREGON_API_KEY?
> 
> Naturalnie, prześlę Ci dziś bezpiecznym kanałem.

Ok, odebrałem - dzięki.

**Comment by dzejkobi** [comment]
Obie bazy danych: SKO i RIO zostały załadowane na produkcję.
Przypisane tagi to `Samorządowe Kolegia Odwoławcze` i `Regionalne Izby Obrachunkowe`.

**Comment by AgnieszkaZdanowicz** [comment]
zgadza się, dzięki!
