### ISSUE TITLE
fedrowanie nie czyta jakiegoś znaku - podejrzewam, że podkreślenia

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#817]
@dzejkobi 

https://fedrowanie.siecobywatelska.pl/listy/84443
https://fedrowanie.siecobywatelska.pl/listy/84437

te gminy uważają, że odpowiedziały, ale tak naprawdę to jest kubek w kubek powtórzone pytanie.

**Comment by ad-m** [comment]
Nie uwzględniamy formatowania. W jednej z wiadomości widać, że stosują kolorki:
![obraz](https://user-images.githubusercontent.com/3618479/93272805-a73b2080-f7b6-11ea-9347-7134e9830ab2.png)

**Comment by KatarzynaBatko** [comment]
Kolejny wniosek wyślę z prośbą o wybranie odpowiedzi, a nie jej kolorowanie lub podkreślanie (to pilotaż był, więc poszło tylko do 65 gmin). A czy teoretycznie jest możliwość by przy pobieraniu do SJJ uwzględnić formatowanie? Bo widzę, że da się wyciągnąć taką informację z systemu.

**Comment by ad-m** [comment]
Ja pobrałem i otworzyłem oryginał wiadomości. Teoretycznie moglibyśmy w Fedrowaniu wyświetlać takie wiadomości z formatowaniem, bo robimy to już w Poradni.
