### ISSUE TITLE
Wyszukiwanie podobnych pism - problemy dokładnościowe

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#823]
W Fedrowaniu mamy mechanizm wyszukiwania podobnych pism. Niemal cały zamknięty w https://github.com/watchdogpolska/feder/tree/master/feder/es_search . 

Został on wyłączony, bo powodował on wydłużenie czasu odpowiedzi, gdy wyświetlamy podobne listy. 

Czy na podstawie kodu rzuca Ci się coś w oczy? Wydaje mi się, że stale indeksujemy do ES, więc możemy w każdej chwili uruchomić ponownie, aby łatwo badać takie przypadki, bo ES czasem odpowiada dość sprawnie.

**Comment by AgnieszkaZdanowicz** [comment]
niski priorytet

**Comment by PiotrIw** [comment]
Elasticsearch wyjety z kodu w v1.4.02
