### ISSUE TITLE
czy ktoś może sprawdzić, czy na fedrowanie docierają maile?

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#830]
@dzejkobi czy Ty jesteś w stanie sprawdzić, czy na fedrowanie są zaciągane maile z serwera? Bo mieliśmy podobny problem z poradnią przed chwilą i tam Adam napisał tak: z jakiegoś powodu połączenie do serwera IMAP zawisło

A ja od rana wysyłam maile na fedrowanie, bo część gmin odpowiada na niewłaściwego maila i widzę, że żaden z moich maili nie dotarł: https://fedrowanie.siecobywatelska.pl/monitoringi/cyfryzacja-urzedow

W ogóle nic nie spłynęło od 29.09, a to dziwne.

@ad-m czy może dodać do tego repozytorium Marcina Bójkę?

**Comment by ad-m** [comment]
watchdogpolska/poradnia#917
