### ISSUE TITLE
BARDZO PILNE - nie działa przycisk "M" (który pokazuje metadane)

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#831]
@dzejkobi czy jest możliwe, że jakieś zmiany, które wgrałeś na produkcję, spowodowały, że przestał działać przycisk "M", który pokazuje metadane dotyczące wiadomości?

![image](https://user-images.githubusercontent.com/36925935/95320005-1d541400-0899-11eb-83f8-6acda8462fe1.png)

Normalnie, jak klikałam ten przycisk, to pojawiały się informacje o tym, jaki jest adres zwrotny dla gminy oraz status wiadomości. Niektóre sądy nas wzywają do wykazania, że mail dotarł do gminy i wtedy robię im zrzut z ekranu. A znowu, jak gminy odpisują na adres: biuro@, to przesyłam ich wiadomości na fedrowanie i w tej sposób sprawdzam, na jaki adres wysłać.

No i dziś ten przycisk nie działa, a muszę wysłać potwierdzenie do sądu. Wczoraj działał na pewno, bo z niego korzystałam.

**Comment by rwakulszowa** [comment]
Nie wiem na ile to pomoże, ale z tego co widzę, (przynajmniej) część metadanych można pokazać ręcznie. Postaram się mniej więcej wyjaśnić w jaki sposób. Oczywiście rozumiem, że to dość kiepski sposób, ale jeśli sprawa jest pilna, może jakoś pomoże.

Z tego co widzę, przeglądarka to Chrome, więc:
1. Będąc na stronie danej sprawy, trzeba otworzyć narzędzia deweloperskie. Najprościej będzie kliknąć prawym przyciskiem myszy na guzik który nie działa i w menu kontekstowego wybrać Zbadaj / Inspect
https://developers.google.com/web/tools/chrome-devtools/open
![Zrzut ekranu z 2020-10-07 13-59-21](https://user-images.githubusercontent.com/10756296/95328802-5050d480-08a6-11eb-898a-698254194110.png)

2. Otworzy się menu z narzędziami, z detalami naszego przycisku.
![Zrzut ekranu z 2020-10-07 14-00-15](https://user-images.githubusercontent.com/10756296/95328821-55158880-08a6-11eb-8232-35b653215e80.png)

3. Dane, które nas interesują, znajdują się w elemencie `email_metadata`
Teraz opcji jest kilka, każda powinna zadziałać:
a) można kliknąć dwukrotnie na tekst `email_metadata metadata collapse` (powinna pojawić się możliwość edycji), ręcznie usunąć słowo `collapse` i zatwierdzić klawiszem Enter.
![Zrzut ekranu z 2020-10-07 14-02-01](https://user-images.githubusercontent.com/10756296/95328843-5c3c9680-08a6-11eb-9439-e4d2fdb1cb36.png)

Na stronie powinna pojawić się sekcja metadanych
![Zrzut ekranu z 2020-10-07 14-03-02](https://user-images.githubusercontent.com/10756296/95328851-5f378700-08a6-11eb-9aea-edc2946f35b0.png)

b) w zależności od ustawień narzędzi, powinna być widoczna sekcja Styles. Jeśli tak jest, można ręcznie kliknąć pole `.collapse { display } ` żeby przełączyć widoczność sekcji.
![Zrzut ekranu z 2020-10-07 14-03-27](https://user-images.githubusercontent.com/10756296/95328858-62cb0e00-08a6-11eb-9182-1fa6e59bb44c.png)

### notka
Nie jestem bardzo zaznajomiony z kodem projektu, więc nie jestem pewien czy mówimy o tej samej sekcji metadanych. Zakładam, że dla zalogowanych użytkowników znajduje się tam więcej danych (m.in email). Jeśli to coś innego, ewentualnie jeśli nie uda się ręcznie uwidocznić tych danych, proszę dać znać.

**Comment by ad-m** [comment]
W konsoli widać:
![obraz](https://user-images.githubusercontent.com/3618479/95332185-5a290680-08ab-11eb-9845-87e4dcf6a63d.png)
Jakbym miał zgadywać to problem wszedł wraz z #549 , ewentualnie #734 .

**Comment by AgnieszkaZdanowicz** [comment]
@rwakulszowa WOW,, zadziałało, ale magia :) dzięki!

**Comment by rwakulszowa** [comment]
W najbliższych dniach postaram się przyjrzeć problemowi i znaleźć poprawkę.

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Powinno być już naprawione ( #859).
Jeśli jest ok, to proszę o zamknięcie tasku.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi u mnie nadal nie działa

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi na firefox działa, na chrome nie

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi  przepraszam działa wszędzie, nie odświeżyłam strony wystarczająco skutecznie. Zamykam
