### ISSUE TITLE
zmiana nazw polskich na angielskie - powiat i województwo (prośba o ponowne przetłumaczenie)

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#833]
We wszystkich widokach stron, które pojawiają się po wybraniu z górnego menu opcji "szukaj" zmieniło się niedawno "powiat" i "gmina" na "county" i "community"

![Uploading image.png…]()

Chodzi o te widoki:
https://fedrowanie.siecobywatelska.pl/sprawy/
https://fedrowanie.siecobywatelska.pl/monitoringi/
https://fedrowanie.siecobywatelska.pl/instytucje/

@efefre czy byłabyś gotowa nam pomóc? Gdyby coś było niejasne, o co mi chodzi, to chętnie wyjaśnię :)

**Comment by ad-m** [comment]
Obraz się nie przesłał.

**Comment by AgnieszkaZdanowicz** [comment]
Ok, to jeszcze raz:

![image](https://user-images.githubusercontent.com/36925935/95374332-7db97480-08de-11eb-91b9-cfd6e4d69086.png)

**Comment by efefre** [comment]
@AgnieszkaZdanowicz postaram się zerknąć. 

@ad-m Na ten moment mam problem z uruchomieniem środowiska. Odpalam standardowo `make build` ale kończy się errorem.

**Comment by ad-m** [comment]
@efefre , jakim errorem? Utwórz proszę osobne zagadnienie, przyjrzymy się temu.

**Comment by efefre** [comment]
> @efefre , jakim errorem? Utwórz proszę osobne zagadnienie, przyjrzymy się temu.

Założyłam oddzielne zgłoszenie #835.

**Comment by ad-m** [comment]
@efefre , dziękuje za ogarnianie tych przystępnych, ale jednak czasochłonnych i widocznych zagadnień :)
