### ISSUE TITLE
ułożenie alfabetycznie tagów

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#870]
@dzejkobi przeszukałam fedrowanie i okazało się, że tylko tagi są ułożone niealfabetycznie. W nawiązaniu do dzisiejszego spotkania miałabym prośbę o ułożenie ich alfabetycznie. Z mojego punktu widzenia one pojawiają się w dwóch miejscach:

- przy edycji instytucji, gdzie przypisujemy tagi do instytucji np. tutaj: https://fedrowanie.siecobywatelska.pl/instytucje/sterdyn/~edytuj

- przy wyszukiwaniu instytucji tutaj: https://fedrowanie.siecobywatelska.pl/instytucje/ (jak się kliknie w "tag" to rozwija się lista)

Czy w obydwu miejscach da się je ułożyć alfabetycznie (bo rozmawialiśmy tylko o tym pierwszym miejscu)?

**Comment by ad-m** [comment]
@dzejkobi , myślę, że wystarczy to zmienić na modelu.

**Comment by dzejkobi** [comment]
Okazało się, że sortowanie tagów na stronie edycji działa poprawnie, ale kilka tagów miało nadmiarowe spacje przed nazwą, stąd dziwna kolejność. Już poprawiłem w bazie.

Natomiast sortowanie na rozwijanej liście to inna kwestia, bo te tagi ładowane są asynchronicznie na podstawie wprowadzonego tekstu. Tam z jakiegoś powodu ustawione jest sortowanie względem ilości przypisanych instytucji. @AgnieszkaZdanowicz Czy chcemy to zmienić na sortowanie alfabetyczne?

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi jeśli da się to zmienić, to tak

**Comment by dzejkobi** [comment]
> @dzejkobi jeśli da się to zmienić, to tak

Da się. Ok, to zmieniamy.

**Comment by ad-m** [comment]
Trzeba posortować bardziej.

**Comment by dzejkobi** [comment]
Nadal nie działa (przypomnienie dla mnie :-)).

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi wygląda na to, że tagi już są ułożone jak trzeba :) to mogę zamknąć to issue?

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Tak, jeśli działa prawidłowo, to można zamknąć. Wszystkie issues, które są gotowe do przetestowania na produkcji oznaczyłem tagiem "test".
