### ISSUE TITLE
Use urlencode to build csv_url

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#874]
We should use `django.utils.http.urlencode` instead of concatenating string to properly encode special character eg. spaces and `&`. 

```
>>> from django.utils.http import urlencode
>>> urlencode({'a':25, 'c':[2,3]})
'a=25&c=%5B%272%27%2C+%273%27%5D'
>>> urlencode({'a':25, 'c':[2,3]}, doseq=True)
'a=25&c=2&c=3'
```

We have code which does not apply that 

https://github.com/watchdogpolska/feder/blob/59709c5916761adad6129809b1292038b1bf7879/feder/institutions/views.py#L39-L51

**Comment by dzejkobi** [comment]
Ok, I will apply that.

**Comment by dzejkobi** [comment]
Applied at PR #876 .
I used list based query argument for urlencode which results with repeated definition for single GET parameter with multiple values. This is what DRF generates by default in web API.
