### ISSUE TITLE
Formatowanie w eksporcie do SJJ

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#875]
@dzejkobi 
Potrzebne jest wprowadzenie czytania formatowania w fedrowaniu, gdyż umykają nam odpowiedzi części gmin, które przesłały podkreślenia i kolory. Wojtek napisał mi tak: "ja używam record.json tam tych danych nie ma. Surowego maila raw_mail.eml nie byłem w stanie otworzyć"

@ad-m podesłał właśnie informację o wprowadzeniu formatowania przez @marcin-wicha w poradni. Wprawdzie dotyczy to wiadomości wysyłanym przez nas, ale - tak, jak rozmawialiśmy- mam opisać problem i nakierować Cię na kod do analizy. Więc sądzę, że albo trzeba szukać tu https://github.com/watchdogpolska/poradnia/issues/768 albo jednak prosić @ad-m o link do kodu lub skontaktować się z @marcin-wicha. Nie wiem czy opisuję to w zrozumiały sposób.

Przypisuję do @dzejkobi z prośbą o zrobienie do połowy listopada mniej więcej, albo do opisania. Dzięki!

**Comment by ad-m** [comment]
Przedstawiania wymagań co do kodu nie spodziewałem się, a raczej opisanie wymagań biznesowych. 

Od strony technicznej w Poradni ten problem mamy rozwiązany. Pierw jest zapisywany do bazy danych wiadomość ( https://github.com/watchdogpolska/poradnia/blob/master/poradnia/letters/views/cbv.py#L164 ), potem wyciągany jest z niej HTML, a potem jest wyświetlany ten kod HTML w bezpieczny sposób ( https://github.com/watchdogpolska/poradnia/blob/7e7429ce4344e280b81a3c6a14d91bb6261180db/poradnia/letters/templates/letters/_letter_list.html#L20 ). 

Mam wrażenie, że teraz można by ten kod zoptymalizować nie sięgając po wiadomość w celu odczytania kodu HTML. W Fedrowaniu nie jest akceptowalne takie podejście, gdyż było ono stosowane i sprawiało problemy wydajnościowe (inny wolumen danych).

Ten kod do Poradni przyniósł nie @marcin-wicha, a już jakiś czas temu @rwakulszowa w watchdogpolska/poradnia#531 . 

Zarówno Poradnia, jak również Fedrowanie wykorzystują do importowania imap-to-webhook ( https://github.com/watchdogpolska/imap-to-webhook ), który generuje webhooki dla przychodzących wiadomości. To jest dodatkowy kontener do postawienia i skierowania na dowolny serwer IMAP, aby pobierać z niego wiadomości.

Wojtek wiadomości pobiera z wykorzystanie downloadera ( https://github.com/watchdogpolska/feder-downloader ).

Potrzebujemy zatem zapisywać kod HTML z wiadomości do bazy danych (zaznaczając czy zapisaliśmy HTML, czy  TXT). Gdy zaczniemy zapisywać w bazie danych HTML to będziemy musieli kod HTML wystawić na API. Zgromadzone informacje odpowiednio udostępnić w API. Po zmianie API oszacować konieczność dostosowania downloadera.

Wszelkie przeprowadzone operacje należy dokonywać ostrożnie, aby nie doprowadzić do utraty danych, ani zakłócenia poprawności krytycznych procesów (por. [komentarz z 2020-10-16T12:52:24Z w zagadnieniu #860](https://github.com/watchdogpolska/feder/issues/860#issuecomment-710026425))

Na marginesie, Wojtek zgłaszał, że nie potrafi skorzystać z oryginałów wiadomości, które udostępniamy w formacie `*.eml`, bo na tej podstawie powinien być w stanie wszystko pobrać sam. Należałoby zweryfikować skąd się biorą trudności.

**Comment by dzejkobi** [comment]
@ad-m O ile udało mi się prawidłowo rozpoznać zagadnienie, zakładam, że rozwiązanie powinno się opierać na zmodyfikowaniu `imap-to-webhook` w taki sposób, aby przesyłał do API treść wiadomości oraz cytaty w dwóch wersjach: `HTML` i `plain text`.

Następnie trzeba zmodifikować endpoint `https://fedrowanie.siecobywatelska.pl/listy/webhook/` w taki sposób, żeby akceptował dane w obu formatach, a następnie uwzględnić tą zmianę w pozostałym kodzie Fedrowania. I teraz pojawia się ważne dla mnie pytanie: Czy endpoint powinien zapisywać wiadomość w obu formatach, czy tylko w jednym i zapisywać jego typ w dodatkowym polu? Ja skłaniam się w stronę zapisu w obu formatach, co prawda zwiększa się wtedy ilość zapisywanych danych, ale za to żadna informacja się nie gubi, bo z technicznego punktu widzenia zawartość tekstowa może być różna od zawartości HTML. Nie wiem na ile ograniczanie wielkości bazy danych jest istotne w tym projekcie, stąd moje pytanie.

Druga kwestia, to zacommitowanie zmian w `imap-to-webhook`. Jak rozumiem, jest on też używany w Poradni, chociaż Poradnia korzysta zdaje się z brancha `v2`. Więc, czy powinienem stworzyć PR do master, czy też stworzyć branch dedykowany pod Fedrowanie?

Trzecia sprawa to testowanie gotowego rozwiązania przed uruchomieniem na produkcji. Czy masz Adamie jakieś wskazówki w tym zakresie?

**Comment by ad-m** [comment]
> @ad-m O ile udało mi się prawidłowo rozpoznać zagadnienie, zakładam, że rozwiązanie powinno się opierać na zmodyfikowaniu `imap-to-webhook` w taki sposób, aby przesyłał do API treść wiadomości oraz cytaty w dwóch wersjach: `HTML` i `plain text`.

Tak.

> Następnie trzeba zmodifikować endpoint `https://fedrowanie.siecobywatelska.pl/listy/webhook/` w taki sposób, żeby akceptował dane w obu formatach, a następnie uwzględnić tą zmianę w pozostałym kodzie Fedrowania. I teraz pojawia się ważne dla mnie pytanie: Czy endpoint powinien zapisywać wiadomość w obu formatach, czy tylko w jednym i zapisywać jego typ w dodatkowym polu? Ja skłaniam się w stronę zapisu w obu formatach, co prawda zwiększa się wtedy ilość zapisywanych danych, ale za to żadna informacja się nie gubi, bo z technicznego punktu widzenia zawartość tekstowa może być różna od zawartości HTML. Nie wiem na ile ograniczanie wielkości bazy danych jest istotne w tym projekcie, stąd moje pytanie.

Rozmiar bazy danych w tym projekcie dotąd nie było ograniczeniem.

> Druga kwestia, to zacommitowanie zmian w `imap-to-webhook`. Jak rozumiem, jest on też używany w Poradni, chociaż Poradnia korzysta zdaje się z brancha `v2`. Więc, czy powinienem stworzyć PR do master, czy też stworzyć branch dedykowany pod Fedrowanie?

Czy zmiany mogą być wprowadzone w sposób wstecznie kompatybilny? Jeżeli potrzebujemy mieć breaking changes to proponuje zaplanować plan aktualizacji Poradni, abyśmy nie mnożyli bytów w organizujemy. Poradnię także kontrolujemy i możemy zaplanować wszelkie niezbędne aktualizacje.

> Trzecia sprawa to testowanie gotowego rozwiązania przed uruchomieniem na produkcji. Czy masz Adamie jakieś wskazówki w tym zakresie?

Można użyć środowiska przejściowego.

**Comment by ad-m** [comment]
W Fedrowaniu powinniśmy wykorzystywać w `v2`. Jeżeli nie wykorzystujemy - myślę, że to dobry moment na aktualizacje.

**Comment by dzejkobi** [comment]
> 
> Rozmiar bazy danych w tym projekcie dotąd nie było ograniczeniem.
> 

Ok, w takim razie będę zapisywał wersję `plain text` zawsze i `HTML` jeśli istnieje. Tak samo cytaty.

>
> Czy zmiany mogą być wprowadzone w sposób wstecznie kompatybilny? Jeżeli potrzebujemy mieć breaking changes to proponuje zaplanować plan aktualizacji Poradni, abyśmy nie mnożyli bytów w organizujemy. Poradnię także kontrolujemy i możemy zaplanować wszelkie niezbędne aktualizacje.
>

Może być wstecznie kompatybilnie, jeśli uznamy, że `content` i `quote` zawierają zawsze plain text, a dodatkowo opcjonalnie może pojawić się `html_content` i `html_quote`. Będzie odrobinę mniej przejrzyście, bo planowałem zmianę nazwy z `content` na `plain_content` i `html_content`, ale nie powinno nic popsuć wstecz.

> Można użyć środowiska przejściowego.

Ok, tylko pytanie, czy warto brnąć w konfigurowanie środowiska przejściowego? Jak dla mnie, architektura Fedrowania jest dość złożona, więc nie wiem, czy udźwignę taką konfigurację w rozsądnym czasie. Z drugiej strony środowisko testowe może się przydać na przyszłość. W każdym razie w przypadku tego zadania zalezy mi na możliwie sprawnym wdrożeniu, ale też bez dużego ryzyka.

**Comment by dzejkobi** [comment]
> W Fedrowaniu powinniśmy wykorzystywać w `v2`. Jeżeli nie wykorzystujemy - myślę, że to dobry moment na aktualizacje.

W repozytorium infra znalazłem wpis świadczący, że w Fedrowaniu używamy obrazu:
```
  - name: imap-to-webhook-feder
    image: quay.io/watchdogpolska/imap-to-webhook:latest
```
wersja `latest` jest zdaje się do tyłu względem `v2` o ile dobrze rozumiem wersjonowanie obrazów Dockera. Nie wiem jak obrazy  Dockera odpowiadają rewizjom Gita. Zakładam, że `quay.io/watchdogpolska/imap-to-webhook:v2` odpowiada `https://github.com/watchdogpolska/imap-to-webhook/tree/v2`, ale nie mam wiedzy, jak to potwierdzić, ani jak zaktualizować obraz. Więc @ad-m, przydała by się Twoja pomoc w skoordynowaniu tego procesu.

**Comment by ad-m** [comment]
`master` to `latest`, a `v2` to `v2`, co jest przypisywane automatycznie na quay.io (wystarczy stworzyć nowy branch).

Zrób PR. Przetestuj. Jak będziemy mieli wszystko to zaplanujemy wdrożenie.

> wersja latest jest zdaje się do tyłu względem v2 

Tak jak pisałem, jeżeli nie wykorzystujemy - myślę, że to dobry moment na aktualizacje.

> Ok, tylko pytanie, czy warto brnąć w konfigurowanie środowiska przejściowego? 

Możemy zaplanować jego stworzenie, skoro potrzebujesz. To jest także w zakresie odpowiedzialności @mrbojko .

**Comment by dzejkobi** [comment]
@ad-m Wstępna propozycja rozwiązania zawiera się w dwóch PR:

#902 i https://github.com/watchdogpolska/imap-to-webhook/pull/20

Niestety całościowo jeszcze nie udało mi się przetestować, bardziej traktuję to jako draft. Proszę o ewentualne uwagi i zaproponowanie, w jaki sposób będziemy chcieli to bezpiecznie wdrożyć.

Wersję HTML wiadomości wyświetlam oznaczając filtrem `|safe`, chociaż teoretycznie te treści mogą zawierać cokolwiek, więc nie są do końca bezpieczne. Jeśli chcemy się upewnić, że są bezpieczne, musielibyśmy zdefiniować, co to oznacza i dodatkowo sparsować wg tych wytycznych.

Gulp w wersji >= 4.0 oczekuje innej składni przy definicji tasku. Poprawiłem przy okazji, żeby dało się zbudować frontend.

**Comment by ad-m** [comment]
> Wersję HTML wiadomości wyświetlam oznaczając filtrem `|safe`, chociaż teoretycznie te treści mogą zawierać cokolwiek, więc nie są do końca bezpieczne. Jeśli chcemy się upewnić, że są bezpieczne, musielibyśmy zdefiniować, co to oznacza i dodatkowo sparsować wg tych wytycznych.

Zagadnienie rozwiązane w Poradni. Powyżej podlinkowane rozwiązanie.

**Comment by dzejkobi** [comment]
> Zagadnienie rozwiązane w Poradni. Powyżej podlinkowane rozwiązanie.

Ok, patrzyłem na to rozwiązanie, ale nie zauważyłem, że wszystko jest zawarte w tagu iframe. W takim razie zrobię podobną modyfikację.
