### ISSUE TITLE
Dziwne - wielokrotne potwierdzenia

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#888]
@dzejkobi spójrz - są takie wielokrotne potwierdzenia. Niby nic, ale wolę zasygnalizować, ponieważ może to jednak jest jakiś problem?

https://fedrowanie.siecobywatelska.pl/monitoringi/konsultacje-spoleczne-w-nadlesnictwach

**Comment by ad-m** [comment]
Pierwsze z góry https://fedrowanie.siecobywatelska.pl/sprawy/konsultacje-spoleczne-w-nadlesnictwach-409 ma trzy daty i dwa nazwiska, więc chyba ktoś odczytywał na różnych komputerach albo różne osoby, więć nie jest to dziwne, że każda wysyła potwierdzenie przeczytania w swoim imieniu.
