### ISSUE TITLE
nie działa pierwsze strona monitoringu Samorządy o liczbę wniosków 2017

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#890]
@dzejkobi nie można wejść w ten monitoring, klikając jego nazwę w spisie monitoringów:

![image](https://user-images.githubusercontent.com/36925935/98343558-48559300-2012-11eb-8875-03fcf5d38bcc.png)

Ale już jak się wpisze odpowiedni adres w pasku adresu przeglądarki, to działa:

![image](https://user-images.githubusercontent.com/36925935/98343719-85ba2080-2012-11eb-966e-73c5bcc04756.png)

Wydaje mi się, że po prostu jest problem z otworzeniem tylko pierwszej strony monitoringu. Wyskakuje wtedy błąd:

![image](https://user-images.githubusercontent.com/36925935/98343849-b7cb8280-2012-11eb-9826-2ca4519e2979.png)

Być może jest to związane ze starym błędem #619  ? Wtedy nie dało się otworzyć konkretnych stron monitoringu, na których były jakieś odpowiedzi od gmin, które powodowały problem (tak przynajmniej to zrozumiałam)

Tylko tam wyskakiwał błąd 500, a tu 504

**Comment by dzejkobi** [comment]
Błąd dotyczy zbyt długiego czasu odpowiedzi. Pierwsze moje skojarzenie to, że coś się tam zapętla i nie może z tej pętli wyjść. Trzeba będzie zrobić dochodzenie.

**Comment by dzejkobi** [comment]
Udało mi się znaleźć przyczynę, ten monitoring powinien się już poprawnie wyświetlać.
Wygląda na to, że podczas pobierania korespondencji coś poszło nie tak i jedna wiadomość została dodana do sprawy wielokrotnie. Oznaczyłem te zduplikowane wiadomości jako spam, dzięki czemu nie są brane pod uwagę przy renderowaniu strony.

**Comment by AgnieszkaZdanowicz** [comment]
działa, dzięki @dzejkobi! dzięki czemu odkryłam kolejny problem, ale to założę oddzielne issue
