### ISSUE TITLE
przy edycji instytucji tagi się rozjechały

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#905]
@dzejkobi może to mały błąd, prosty do naprawy? Jak wchodzę w edycję instytucji, to tagi nie są w takim polu, które miałoby suwak z boku, tylko są ciągiem i wjeżdżają na pole "aktualizuj", które bardzo ciężko jest wcisnąć:

![image](https://user-images.githubusercontent.com/36925935/99803019-001d9100-2b39-11eb-9878-ccd8643c47b0.png)

Czy dałbyś radę to naprawić w pierwszej kolejności, jeśli to mała sprawa?

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Jaka to przeglądarka i w jakiej wersji? Pytam, bo testowałem u siebie na Firefoxie i Chromie, i jest w porządku. Może na wszelki wypadek spróbuj wyczyścić cache przeglądarki.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi korzystam z Chrome

![image](https://user-images.githubusercontent.com/36925935/99819713-1be06180-2b50-11eb-926b-fdfcd88d4e1c.png)

Próbowałam przez ctrl + r i w trybie incognito - cały czas mam takie rozjechane

**Comment by dzejkobi** [comment]
Ok, na najnowszej wersji Chrome udało mi się ten problem odtworzyć. Muszę zrobić dochodzenie, co tam się dzieje.

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Z tego, co udało mi się ustalić, problem występuje tylko na najnowszej wersji Chrome. Podejrzewam, że może to być bug samej przeglądarki, ale wrzuciłem poprawkę, która powinna go wyeliminować. Natomiast nadal przeglądarka nie chce pozwolić na przewijanie wewnętrznej zawartości za pomocą suwaka, a jedynie za pomocą klawiatury albo rolki myszy.

Jeśli nie jest to akceptowalne rozwiązanie, to mogę całkowicie zrezygnować z wewnętrznego przewijania tagów i umieścić je na liście widocznej w całości.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi dzięki, jak dla mnie teraz jest lepiej, niech tak zostanie
