### ISSUE TITLE
czy jest możliwość postawienia instancji testowej fedrowania

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#920]
@ad-m @mrbojko dziś na spotkaniu o fedrowaniu z @dzejkobi rozmawialiśmy o tym, że kolejne zmiany, które sobie wymyślamy na fedrowanie wymagają delikatności w ich wprowadzaniu i bezpieczniej byśmy się wszyscy czuli, gdyby powstała instancja testowa, na której Jakub mógłby spokojnie testować zmiany. Ale nie wiemy, po pierwsze, czy mamy na to miejsce na serwerze, a po drugie, czy @ad-m znalazłbyś czas, żeby stworzyć takie środowisko, bo doszliśmy do wniosku, że jako autor produkcji, najlepiej ją odtworzysz. Tak więc tutaj potrzebujemy odpowiedzi i ewentualnie pomocy.

**Comment by mrbojko** [comment]
@AgnieszkaZdanowicz @dzejkobi z tego co widzę nie powinno być problemów, zwłaszcza, że rozluźniamy wykorzystanie civicrm, a on ma wciąż trzy instancje - dev, prod i stagging. @ad-m czy byłbyś na tyle miły, żeby napisać plan co trzeba zrobić aby uruchomić instancję testową - zmierzyłbym się z tym problemem. Rozumiem, że warto dopisać jakąś subdomenę, dodać dockera fedrowania, ustawić pewnie jakieś przekierowania na gateway? To pomogłoby mi w końcu w praktyce zmierzyć się z tymi wszystkimi rzeczami, które wiszą w dockerach - warto pozbyć się instancji testowch civicrm, ssh itp.

**Comment by ad-m** [comment]
@mrbojko , Fedrowanie nie korzysta z kontenerów w środowisku produkcyjnym. Kiedyś instancja testowa Fedrowania istniała. Load-balancer jest skonfigurowany: https://staging.fedrowanie.siecobywatelska.pl/. 

Należy dostosować plik https://github.com/watchdogpolska/infra/blob/master/ansible/vars/instance/feder_staging/vars.yml zgodnie z zmianami w pliku https://github.com/watchdogpolska/infra/tree/master/ansible/vars/instance/feder a także stworzyć wszelkie zasoby wspierające, a następnie wdrożyć to.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi czy to już możemy uznać za zakończonego? Bo bazę Marcin zaktualizował, jak rozumiem.

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Generalnie tak, ale prawdopodobnie przez dodatkowe uwierzytelnianie na poziomie serwera www, nie działają widoki RESTowe: https://staging.fedrowanie.siecobywatelska.pl/api/. @mrbojko @ad-m Znacie może jakieś rozwiązanie tego problemu?

**Comment by dzejkobi** [comment]
Dodatkowe uwierzytelnianie zostało wyłączone i problem zniknął.

Ewentualnie można jeszcze wydłużyć (około dwukrotnie) maksymalny czas obsługi żądania na serwerze, zarówno na staging jak i na produkcji, powieważ w przypadku raportów, około 1000 spraw jeszcze udaje się pobrać w zadanym czasie, ale przy ponad 2000 spraw już nie i serwer zwraca `504 Gateway Time-out`.
