### ISSUE TITLE
błąd przy usuwaniu wiadomości 

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#930]
@dzejkobi weszłam w monitoring "Samorządy - o liczbę wniosków" i zobaczyłam, że gmina Żarnów wysyła nam z automatu wiadomości o różnych szkoleniach, życzenia świąteczne etc. Najpierw zaczęłam te wiadomości oznaczać, jako spam, ale przestraszyłam się, że potem z automatu odpowiedzi od tej gminy będziemy traktować jako spam i postanowiłam po prostu usunąć te wiadomości za pomocą przycisku "usuń":

![image](https://user-images.githubusercontent.com/36925935/103994006-b47d8000-5196-11eb-8f33-d8d4c0fdf15b.png)

I wyskoczył mi taki błąd:

![image](https://user-images.githubusercontent.com/36925935/103994411-42596b00-5197-11eb-9f1f-3a71b10eff11.png)

Ustawiłam sobie uprawnienia, że mogę kasować list, więc błąd nie wynika z braku uprawnień. Czy możesz spojrzeć, co tu poszło nie tak?

**Comment by dzejkobi** [comment]
Ok, sprawdzę.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi widzę, że coś się tu działo i Adam zamknął sprawę. Napiszesz mi, co tutaj się działo i czy już powinno działać - albo możemy o tym w środę porozmawiać

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Tak, wrzuciłem poprawkę, a Adam dopisał test i zmergował, ale release na produkcję zrobiłem dopiero przed chwilą. Teraz usuwanie powinno już działać poprawnie. Proponuję sprawdzić ponownie.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi działa, dzięki!
