### ISSUE TITLE
prośba o wrzucenie bazy "spółki komunalne" na fedrowanie

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#936]
@dzejkobi wysyłam link do bazy z prośbą o wrzucenie do instytucji pod nazwą "spółki komunalne":

https://docs.google.com/spreadsheets/d/1KwaJed0a9_29N8tZ8W04C8SQyntwwFiHAEziUtOlHJM/edit#gid=948307435

Uporządkowane dane są w zakładce "fedrowanie". Zostawiłam kolumnę "typ gminy", ktora jest tylko informacją dla mnie, skąd brałam dane i nazwa urzędu, bo nie wiedziałam, na jakiej zasadzie my przypisujemy instytucje do gminy/powiatu/województwa (to się dodaje po REGONie?). Reszta kolumn to dane do wgrania do fedrowania.

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Tak, jednostkę terytorialną przypisujemy do instytucji na podstawie REGONu. Ale na przyszłość bardzo przydatna do walidacji byłaby kolumna z nazwą miejscowości, którą skrypt mógłby automatycznie porównywać z bazą REGON. Nazwa instytucji bardzo często jest różna od tej, która występuje w pliku, więc niezbyt się nadaje do walidacji, ale miejscowość powinna być zgodna. W tej bazie mogłem tylko sprawdzać, czy taki REGON istnieje.

Instytucje zostały zaimportowane: https://fedrowanie.siecobywatelska.pl/instytucje/?tags=158

Było trochę problemów z tym plikiem. Niektóre rekordy niekompletne, kilka zduplikowanych i trochę błędów w adresach e-mail. To, co byłem w stanie, uzupełniłem, pozostałe musiałem zignorować.

Pojawił się też problem, bo okazało się, że kilka z tych instytycji mieliśmy już w bazie pod innymi tagami (szpitale i media gminne), a import je nadpisał. Na szczęście udało mi się wyszukać te przypadki, przywrócić poprzednie dane z historii i ręcznie dodać tag `spółki komunalne`, ale będę musiał to uwzględnić w skrypcie przy kolejnym imporcie.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi wgranych jest 619 spółek, a w bazie jest 1859 podmiotów - aż tyle było niepoprawnych? Brałeś dane z zakładki "fedrowanie"?

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Niestety okazuje się, że nie. Gdzieś przy eksporcie do CSV musiała mi się przełączyć zakładka, a kolumny były takie same i nie zwróciłem uwagi, że to inne dane. Czyli będę musiał wyeksportować od nowa.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi przykro mi :( co do powtórzonych podmiotów, to rzeczywiście są powtórki, jak właścicielem spółki jest kilka gmin - ale oczywiście spółka powinna znaleźć się w bazie tylko raz, więc tutaj tym razem mam prośbę do Ciebie o wyłapanie duplikatów, a ja na przyszłość będę się starała o tym pamiętać. Co do niepełnych danych, to w zakładce "fedrowanie" powinny być tylko takie spółki, które mają uzupełnione dane, więc ten problem chociaż odpadnie.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi na jakim etapie jest wrzucanie pełnej bazy? Bo wolontariusz skończył uzupełniać ostatni rodzaj spółek i najchętniej bym je dorzuciła do odpowiedniego arkusza, żebyś wgrał całość - mogę?

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Tak, możesz zaktualizować arkusz. Będę to dziś wgrywał, ale jeszcze nie zacząłem.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi dorzuciłam, baza gotowa do wrzucania (nie przejmuj się kolorami komórek, to dla nas tylko oznaczenie)

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Zaimportowałem zaktualizowany arkusz. Uzupełniłem dane tam, gdzie brakowało i prawie wszystkie błędy udało mi się wyeliminować.

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi dzięki! A z czego wynika różnica ponad 100 w liczbie spółek w dokumencie google (2037 spółek) i fedrowaniu (1908 spółek)? Było aż tyle błędów w bazie?

**Comment by dzejkobi** [comment]
@AgnieszkaZdanowicz Błędów, których nie udało się poprawić było tylko kilka, zdaje się, że 3. A pozostała rozbieżność wygląda mi na powtórzenia, czyli rekordy z tym samym REGONem, ale potwierdzę to jeszcze.

**Comment by dzejkobi** [comment]
Przeanalizowałem arkusz i wyszło 128 powtórzeń nr REGON.
Więc to by się zgadzało: 2035 zaimportowanych rekordów - 128 powtórzeń = 1907 instytucji.

Rekordy zdublowane i liczba ich wystąpień:
```230443311 6; 592271246 2; 330897173 3; 272203933 2; 272203910 2; 270544647 4; 850490090 2; 80226740 3; 210396113 2; 230289940 4; 230820274 4; 142566480 2; 691766988 2; 310219626 2; 110608386 2; 510911089 2; 121842461 2; 17441290 2; 890572595 2; 250680024 5; 141246298 2; 130197766 2; 130018137 2; 130306652 2; 120730487 2; 770904455 2; 771486860 2; 770530530 3; 365469091 2; 770528472 2; 511433568 2; 70473920 2; 370346967 2; 570881401 2; 592164094 2; 730335959 2; 120392984 2; 371168663 2; 530593403 2; 871639992 2; 811847734 2; 90049393 2; 90523340 3; 192998920 2; 390760852 2; 890178579 2; 310018543 2; 20394147 2; 20286417 3; 270135328 2; 91230462 2; 870300040 2; 670688032 2; 15526348 2; 6375209 2; 193078050 2; 220639884 3; 192488478 3; 193113361 4; 192626265 4; 10365722 3; 191680713 3; 190563879 2; 240681155 2; 273741035 2; 270561663 8; 270563188 3; 272854582 5; 273073527 2; 273065841 2; 273298692 2; 276142230 2; 270504889 4; 278243543 2; 272157009 2; 273854704 2; 411416981 2; 410021476 2; 630999119 3; 364232731 2; 230189083 2; 385877319 2; 22186832 2; 366415810 2; 22116748 2; 20717998 2; 890591552 2; 891116936 2; 272661647 2;```

**Comment by AgnieszkaZdanowicz** [comment]
@dzejkobi dzięki! będę sprawdzać na przyszłość i teraz też sprawdzę i zaktualizuję naszą bazę
