### ISSUE TITLE
Omówienie - jak radzić sobie z widocznym spamem

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#940]
@dzejkobi Podrzucam temat do omówienia - co zrobić ze spamem, który sporadycznie pojawia się w widoczny sposób na fedrowaniu.

**Comment by AgnieszkaZdanowicz** [comment]
Agnieszka: Teraz musimy wejść w każdą wiadomość, wybrać "oznacz jako spam", potem potwierdzić i zamknąć okno. To jest bardzo czasochłonne.

Adam: 
Być może coś jesteśmy w stanie wyciągnąć z alertów o podejrzanej wiadomości? Na początek po samym słowie "spam", które już dodaje system i generować alerty - ktoś to ocenia potem.

Czy na podstawie samego tytułu jesteśmy w stanie ocenić, czy coś jest spamem?


Kuba: Dużą barierą jest interfejs, bo jest mało wygodny. Najlepiej byłoby przepisać całe narzędzie na dwuwarstwowe. Adam proponuje zagnieździć komponenty view w obecnym interfejsie. Można alerty przenieść na API.

**Comment by AgnieszkaZdanowicz** [comment]
Warto położyć nacisk na  UXDesign - może spróbować się z kimś skonsultować (czy nie mieliśmy chętnych wolo w tym temacie?)

**Comment by AgnieszkaZdanowicz** [comment]
Najpierw zamykamy inne tematy, a do tego wrócimy na spokojnie systemowo

**Comment by AgnieszkaZdanowicz** [comment]
Mam taką luźną myśl, którą zapiszę, żeby nie uciekła. Na fedrowanie często dostajemy spam w postaci maili zachęcających do wpłaty na jakąś zbiórkę - wtedy przychodzi jednocześnie 20-30 wiadomości o takim samym tytule i treści. Może da się ustawić jakoś system, żeby takie wiadomości wyłapywał jako podejrzane i żeby można było je bardziej masowo oznaczyć, że to spam?

I druga sprawa, która by mi ułatwiła usuwanie spamu ręcznie, to jakbym nie musiała wchodzić w każdą wiadomość, żeby oznaczyć spam, tylko żebym mogła je jakoś zaklikać i masowo oznaczyć, jako spam (ale to na przyszłość do przemyślenia - po prostu teraz to zabiera sporo czasu)

**Comment by ad-m** [comment]
Jak dla mnie pierwsze zagadnienie to jest do rozwiązania przez statyczne reguły i automatyczne zgłaszanie takich wiadomości. Przypuszczam, że prosty mechanizm w oparciu o frazy pozwoli sporo wyłapać.

Wówczas druga sprawa to będzie zagadnieniem dopracowania obecnego mechanizmu obsługi zgłoszeń.

**Comment by ad-m** [comment]
> Jak dla mnie pierwsze zagadnienie to jest do rozwiązania przez statyczne reguły i automatyczne zgłaszanie takich wiadomości. Przypuszczam, że prosty mechanizm w oparciu o frazy pozwoli sporo wyłapać.

Wiadomości mogą być:

* oznaczone jako spam – wymagana dodatkowego uprawnienia i powoduje ukrycie wiadomości
* zgłoszenie wiadomości – nie wymaga nawet zalogowania i przekazuje sygnał do zespołu monitoringu

Przykładowy wykaz alertów: https://fedrowanie.siecobywatelska.pl/alerty/monitoring-53

> Wówczas druga sprawa to będzie zagadnieniem dopracowania obecnego mechanizmu obsługi zgłoszeń.

Obecnie mamy mechanizm obsługi zgłoszeń. Jednakże wymaga on redukcji klikania. 

Możemy pójść w ujęcie podobne do Mailman: 

![obraz](https://user-images.githubusercontent.com/3618479/132583305-80786508-1b47-4e1d-b0b5-8e9f02042cbd.png)

Ważne jest to, że wybiera się akcje wobec każdej wiadomości, a potem zbiorczo zatwierdza. Jest także opcja "Zignoruj wszystkie wiadomości oznaczone jako Odłóż". 

Możemy to zrealizować na widoku podobnym do "Przypisz".

**Comment by dzemeuksis** [comment]
Za przynajmniej 237 listów ze spamem odpowiada jeden i ten sam nadawca, co sprawia, że w panelu Django bardzo łatwo je [wyszukać](https://fedrowanie.siecobywatelska.pl/admin/letters/letter/?q=fundacjadzieciom.org) i zbiorczo usunąć.

Czy jest jakiś powód, żeby tego w ten sposób nie zrobić? Czy usunięcie tych spamów z poziomu Django rozwaliłoby coś w logice spraw na Fedrowaniu, do których te listy są podpięte, albo coś w tym rodzaju?

**Comment by ad-m** [comment]
Wymaga sprawdzenia czy element "Record" jest odpowiednio usuwany po takim usunięciu listu. Jeżeli jest – nie ma większego problemu, aby tak usuwać listy.

**Comment by ad-m** [comment]
Aczkolwiek wolałbym mieć w Django Admin operacje zbiorczego oznaczenia jako spam. To nie powinno być trudne i powinieneś być w stanie sam to zaimplementować. Musisz podążać za https://docs.djangoproject.com/en/4.0/ref/contrib/admin/actions/ i zaimplementować logikę zgodną z https://github.com/watchdogpolska/feder/blob/09b8e0544942bf266f7384ac4df0a4d131734e9e/feder/letters/views.py#L486-L496 .

**Comment by dzemeuksis** [comment]
@KatarzynaBatko , @AgnieszkaZdanowicz , w zakresie mechanizmów sprzątania spamu @PiotrIw dorobił sporo przydatnych funkcji, dostępnych z poziomu Django. Sukcesywnie z nich korzystam i czyszczenie idzie znacznie sprawniej niż wcześniej a dodatkowo pewne rzeczy można automatyzować. Być może reguły automatyzujące oznaczanie jako spam można dalej rozwijać, natomiast może to już lepiej w nowych zgłoszeniach a to zamknąć?

**Comment by AgnieszkaZdanowicz** [comment]
@dzemeuksis Ty się teraz opiekujesz spamem, więc Tobie zostawiam do decyzji. A czy to zarządzanie spamem przez Django, to wymaga dużych zdolności technicznych? Czy myślisz, że byłaby szansa, żebyś spisał kiedyś tam, jakie są w ogóle te funkcje do zarządzania spamem, o których wspomniałeś?

Ja się jeszcze zastanawiam, czy jest sens i możliwość, żeby wyczyścić spam ze starych monitoringów? Np. tutaj są wiadomości o zablokowaniu karty: https://fedrowanie.siecobywatelska.pl/monitoringi/raport-o-stanie-gminny-jak-jest-tworzony

**Comment by dzemeuksis** [comment]
Nie wymaga żadnych zdolności technicznych, mogę napisać mały podręcznik, jak to robić.

Ależ czyszczę sukcesywnie spam również ze starych monitoringów, ale jeśli miałbym to zrobić w całości na raz, to potrzebowałbym tygodnia tylko na to i nie wiem, czy bym się wyrobił, bo mamy w bazie przeszło 100 000 listów.

**Comment by AgnieszkaZdanowicz** [comment]
A to jak czyścisz, to super :) podręcznik to dobry pomysł. W takim razie ten wątek już zamykam.

**Comment by dzemeuksis** [comment]
Przy okazji, usunąłem spam z tego monitoringu, co podlinkowałaś (mam nadzieję, że dodanie komentarza nie zrobi reopen).
