### ISSUE TITLE
Dodanie do API odpowiedzi udzielonych przez graczy SJJ

### ISSUE THREAD

**Issue by 52edc** [watchdogpolska/feder#955]
np
W przypadku ostatniej kampanii sjj. Dzięki dodaniu do API odpowiedzi udzielonych przez graczy SJJ będę mógł wyświetlić listę wszystkich gmin, które jednocześnie
- mają gminną gazetę
- na pytanie 7 była odpowiedź "mieszkańców"
- na pytanie 8 była odpowiedź "żadne z powyższych"

dzięki

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz czy to żądanie od użytkownika było rozpatrywane podczas statusu? Czy możesz udzielić w tym zakresie odpowiedzi?

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m a Ciebie nie było na ostatnim statusie? Nie mówiliśmy o tym i ja w ogóle nie rozumiem, o co chodzi niestety

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz to jest ze stycznia, więc mogłoby być wcześniej.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m nie rozmawialiśmy o tym

**Comment by ad-m** [comment]
Czy planujemy odnieść się do tego oczekiwania wobec aplikacji?

**Comment by dzejkobi** [comment]
Te dane posiada silnik crowdsourcingowy https://github.com/heolin123/funcrowd, którego używamy na potrzeby SJJ, więc silnik musiałby je udostępnić. Jest w planie duża aktualizacja silnika, więc możemy już na tym etapie zebrać wymagania i przekazać autorowi.

**Comment by KatarzynaBatko** [comment]
@52edc Wszystkie dane ze sprawdzamyjakjest.pl będą dostępne. Pracujemy nad tym by mozna je było pobierać dowolnie. Na pewno powstanie to do końca roku. Gdybyśmy nie wrócili z odpowiedzią, proszę nam przypomnieć
