### ISSUE TITLE
Eksport instytucji do CSV

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#96]

**Comment by kbiernat** [comment]
Jakich pól potrzeba w tym exporcie?

**Comment by ad-m** [comment]
@kbiernat, dostrzegam problem słabej bazy danych instytucji. Będziemy musieli poprawić nazwy instytucji i dodatkowo uzupełnić to o rejestr REGON, aby móc automatycznie aktualizować.  
Już w przygotowaniu jest monitoring sądów (p. branch [court](https://github.com/watchdogpolska/feder/tree/court)), który wykorzystuje poprawne nazwy instytucji. Zatem docelowo nazwa instytucji to nie jest nazwa JST.

Wyeksportowałbym wszystkie pola z Institution z brancha [court](https://github.com/watchdogpolska/feder/tree/court), w tym tagi i - w miarę możliwości - parents . Jakbym miał to realizować to bym wykorzystał ``django-import-export``, bo ma import, eksport, a nawet update z ładnym diffem zmian. Zobacz przykład użycia w [OrganizationResource](https://github.com/watchdogpolska/watchdog-kj-kultura/blob/master/watchdog_kj_kultura/organizations/resources.py#L69).

**Comment by ad-m** [comment]
@kbiernat , court jest już na masterze.

**Comment by AgnieszkaZdanowicz** [comment]
jest możliwość pobrania instytucji (i nie tylko) w csv z danego monitoringu przez "zobacz dzienniki". Więc zamykam

**Comment by ad-m** [comment]
Duplicate of #762
