### ISSUE TITLE
Prośba o nowy tag

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#965]
@dzejkobi - mam prośbę o dodanie nowego tagu "zakłady budżetowe". Część spółek okazała się takimiż, więc musimy to rozdzielić. Dzięki!

**Comment by ad-m** [comment]
Zrobione. Uprzejmie proszę o weryfikacje.

**Comment by AgnieszkaZdanowicz** [comment]
@KatarzynaBatko czy to zrobione i można zamknąć wątek?
