### ISSUE TITLE
automatyczne potwierdzanie odebrania wiadomości

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/feder#975]
@dzejkobi przy każdym monitoringu zdarza się, że dostajemy odpowiedzi mailem, ale jednocześnie pocztą. Niektóre instytucje tłumaczą, że nie dostały potwierdzenia, że dostaliśmy odpowiedź mailem, więc dla pewności wysyłają pocztą. Czy myślisz, że dałoby się zrobić jakiś mechanizm, który wysyłałby do instytucji automatycznie potwierdzenie, że mail do nas dotarł?

**Comment by dzejkobi** [comment]
Myślę, że jest taka możliwość. Proponuję to przedyskutować na następnym spotkaniu.

**Comment by ad-m** [comment]
Duplikat #299
