### ISSUE TITLE
Przetłumaczyć na polski te elementy strony, które są w języku angielskim

### ISSUE THREAD

**Issue by tradzik** [watchdogpolska/feder#98]

**Comment by ad-m** [comment]
Dziękuje. Obecnie znacząco modyfikuje kodc odpowiedzialny za ankiety (#24, #45 i inne). Część rzeczy zostałała już przetłumaczona, ale nie opublikowałem. Nie wiem ile zajmie mi praca nad przeprojektowaniem ankiet.

**Comment by ad-m** [comment]
Myślę, że podstawowe elementy już zostały przetłumaczone i mogę zamknąć. Pozostaje aktualne #288 i #104
