### ISSUE TITLE
Nie działa opcja listy

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#989]
Nie mogę wejść w listy, gdzie wcześniej znajdowałam zagubione odpowiedzi https://fedrowanie.siecobywatelska.pl/listy/?page=last @dzejkobi

**Comment by ad-m** [comment]
Czy to skutek #981?

Na https://fedrowanie.siecobywatelska.pl/listy/przypisz jest dostępne.

**Comment by dzejkobi** [comment]
@ad-m Jest to możliwe, chociaż wątpię, bo jest tam dodana tylko obsługa dodatkowego wyjątku. Ten paginator zachowuje się dla mnie dość niezrozumiale, np. generuje linki typu: `https://fedrowanie.siecobywatelska.pl/listy/?page=MjU%3D`, a kiedy podamy np. link: `https://fedrowanie.siecobywatelska.pl/listy/?page=1`, nie jest w stanie tego zrozumieć. Zajrzę do niego i spróbuję poprawić.

**Comment by ad-m** [comment]
@dzejkobi , paginator – ze względu na wydajność – wykorzystuje podejście "next page token" ( https://www.mixmax.com/engineering/api-paging-built-the-right-way/ ), więc nie wykorzystuje paginacji z wykorzystaniem numerowania stron. Podobnie jak wiele API dużych serwisów, aby pobrać kolejną stronę musisz mieć token ze strony poprzedniej (w tym momencie to jest base64 ID ostatniego elementu). Nie ma możliwości przejścia bezpośrednio do strony ostatniej.

Zostało to zaimplementowane w taki sposób, bo pobranie rekordów spełniających kryteriów w taki sposób nie wymaga pobrania wszystkich danych, a pobrania tylko tych, które są wymagane według indeksu. W mojej ocenie jeżeli chcesz mieć paginacje numerowaną to musisz posortować, a posortowanie wymaga przetworzenia w bazie danych pełnego zestawu danych (LIMIT tylko obcina co baza zwraca, ale przygotowuje całość).

**Comment by dzejkobi** [comment]
> Nie ma możliwości przejścia bezpośrednio do strony ostatniej.

Ok, tak też myślałem. Czyli problem polega na tym, że w menu znajduje się nieprawidłowy link, który trzeba poprawić na `https://fedrowanie.siecobywatelska.pl/listy/`, a sam paginator można pozostawić bez zmian.
