### ISSUE TITLE
Niektóre odpowiedzi powtarzają się kilka razy, czy jest możliwe eliminowanie?

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/feder#991]
@dzejkobi na następnym planowaniu może porozmawiamy. Bo np. tu jest trzy razy to samo, a potem userzy w sprawdzamyjakjest.pl mają tak samo https://fedrowanie.siecobywatelska.pl/sprawy/jawnosc-w-spolkach-komunalnych-269. Uwaga userki "biore udział w tej kampanii oznaczania dokumentów spółek- i tylko takie spostrzeżenie - 45 oznaczonych dokumentów 6 razy otrzymałam do oceny te same - pewnie jakiś system losujący jest czy coś, ale może można jakoś go udoskonalić żeby odrzucał z puli te ocenione." Wydaje mi się, że eliminowanie powinno być na poziomie fedrowania

**Comment by AgnieszkaZdanowicz** [comment]
jesteśmy w stanie wyłapywać odpowiedzi identyczne (po kilka razy zaciągane z serwera pocztowego) i je ignorować. Ale dobrze byłoby je jakoś oznaczać - mogą się przenosić do osobnego folderu na serwerze pocztowym.

**Comment by dzemeuksis** [comment]
@KatarzynaBatko , @AgnieszkaZdanowicz , mnie się wydaje, że ostatnio nikt nie podnosił tego typu trudności, zresztą chyba swego czasu @PiotrIw coś robił z takimi dublami. Czy możecie zaktualizować status tego? Nie jest przypadkiem do zamknięcia?

**Comment by AgnieszkaZdanowicz** [comment]
Ja nie potrafię ocenić - mogę się spytać działu komunikacyjnego, bo dziewczyny więcej odpowiedzi ostatnio przeglądają niż ja. No i pytanie, na ile to problem w SJJ - bo na samym fedrowaniu to nie szkodzi za bardzo. Ale Ty też Michale przeglądasz dane, więc jeśli mówisz, że to się raczej nie pojawia, to może nie ma za bardzo po co drążyć? A co @PiotrIw robił w sprawie dublikatów?

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz @dzemeuksis Webhook (endpoint) odbierający listy jest zabezpieczony przed mailami identycznymi po kilka razy zaciąganymi z serwera pocztowego (mail z takim samym ID i adresatami zduplikowany pomiędzy zenboxem a federem ze względu na zależności czasowe - był kiedyś taki błąd/issue). 

Powtarzają się wiadomości o tej samej treści wysyłane wielokrotnie przez różnych nadawców do różnych odbiorców, czyli klasyczny spam - na to mechanizmu obecnie nie ma. 
Jeśli chodzi o spam to zagęściłbym bardziej reguły automatycznego znakowania niż są teraz (kluczem jest domena oznaczona jako spamerska) - do przegadania bo jest spory wachlarz możliwości.

Podsumowując, w kontekście pierwotnym issue zamykam jako wykonane.
