### ISSUE TITLE
przypadkowo pobierające się załączniki na komputer

### ISSUE THREAD

**Issue by kasia-wit** [watchdogpolska/feder#999]
Podczas pracy na komputerze pobierają się do folderu pobrane odpowiedzi z Fedrowania z różnych monitoringów. Zadziało się już tak 3 razy w minionym tygodniu. Ostatnie pobranie 'dziwnych załączników' nastąpiło w piątek podczas pobierania korespondencji z ePUAP o godz. 09.37 Wśród pobranych załączników pojawiła się odpowiedź z Urzędy Miejskiego w Lubinie z monitoringu 'Mieszkańcy i radni wobec raportu o stanie gminy'. W tym czasie nie wchodziłam na Fedrowanie.
Skąd te załączniki biorą się na moim komputerze?

**Comment by kasia-wit** [comment]
@mrbojko proszę o pomoc.

**Comment by ad-m** [comment]
@mrbojko to nie jest żaden mechanizm wbudowany w Fedrowanie.

**Comment by AgnieszkaZdanowicz** [comment]
@kasia-wit czy sytuacja się powtórzyła?

**Comment by kasia-wit** [comment]
Cześć,
Nie. Sytuacja się nie powtórzyła.
Powinnam zamknąć zgłoszenie, Przepraszam.

Pozdrawiam
Katarzyna Witek

śr., 28 lip 2021, 19:24 użytkownik AgnieszkaZdanowicz <
***@***.***> napisał:
